;;; emacsvox-aural-voice-editor-tests.el --- Spoken voice editor interactions -*- lexical-binding: t; -*-
;;; Commentary:
;; Test visible scope, immutable comparison, save behavior and return navigation.
;;; Code:
(require 'ert)
(require 'emacsvox-aural-voice-drafts-tests)
(require 'emacsvox-aural-voice-editing-tests)
(require 'omnivox-preview-tests)
(require 'emacsvox-aural-voice-editor)
(defmacro emacsvox-test--with-voice-editor (&rest body)
  (declare (indent 0) (debug t))
  `(emacsvox-test--with-voice-save
    (let ((emacsvox-aural-voice-drafts--registry (make-hash-table :test #'equal))
          (emacsvox-aural-voice-editor--contexts (make-hash-table :test #'equal))
          (emacsvox-aural-voice-editor--preview-owner nil)
          (emacsvox-aural-voice-drafts--changed-hook '(emacsvox-aural-voice-editor--draft-changed))
          speech requests callbacks)
      (unwind-protect
          (cl-letf (((symbol-function 'tts-speak) (lambda (text &rest _) (push text speech)))
                    ((symbol-function 'tts-notify) (lambda (text &rest _) (push text speech)))
                    ((symbol-function 'emacsvox-icon) #'ignore)
                    ((symbol-function 'tts-voice-inventory) (lambda () nil))
                    ((symbol-function 'tts-stop) #'ignore)
                    ((symbol-function 'tts-preview-voices)
                     (lambda (entries &optional callback) (push entries requests) (when callback (funcall callback '(:status completed)))))
                    ((symbol-function 'tts-apply-voice-configuration)
                     (lambda (&optional callback) (push callback callbacks))))
            ,@body)
        (maphash (lambda (_ context)
                   (when (buffer-live-p (plist-get context :buffer))
                     (with-current-buffer (plist-get context :buffer)
                       (let ((kill-buffer-query-functions nil)) (kill-buffer)))))
                 emacsvox-aural-voice-editor--contexts)))))

(ert-deftest emacsvox-aural-voice-editor-manager-edit-retains-both-views ()
  (require 'emacsvox-aural-voice-palettes)
  (emacsvox-test--with-voice-editor
    (with-temp-buffer
      (emacsvox-aural-voice-palettes-mode)
      (emacsvox-aural-voice-palettes-refresh 'acss-default)
      (cl-letf (((symbol-function 'emacsvox-aural-voice-palettes--read-entry-name)
                 (lambda (_) 'bolden)))
        (save-current-buffer (call-interactively (key-binding (kbd "e")))))
      (should (derived-mode-p 'emacsvox-aural-voice-palettes-mode))
      (let ((editor (plist-get (gethash '(base acss-default bolden) emacsvox-aural-voice-editor--contexts) :buffer)))
        (with-current-buffer editor
          (should (derived-mode-p 'emacsvox-aural-voice-editor-mode))
          (should-not tabulated-list-entries)
          (should (eq (emacsvox-aural-voice-editor--get :voice) 'bolden)))))))

(ert-deftest emacsvox-aural-voice-editor-inherited-edit-reset-and-edit-again ()
  :tags '(voice-style-ui)
  (require 'emacsvox-aural-voice-palettes)
  (emacsvox-test--with-voice-editor
    (emacsvox-aural-register-voice-palette-data
     '(:schema-version 3 :id child :summary "Child" :parent reading-owned :routing owned :entries nil))
    (emacsvox-aural-save-user-data)
    (let ((parent (emacsvox-aural-voice-drafts--palette-data 'reading-owned))
          (original (emacsvox-aural-voice-runtime--resolve 'bolden 'child))
          (source (get-buffer-create "*Reset voice test*")))
      (unwind-protect
          (progn
            (with-current-buffer source
              (emacsvox-aural-voice-palette-previews-mode)
              (setq emacsvox-aural-voice-palette-previews-palette 'child)
              (emacsvox-aural-voice-palette-previews-refresh 'bolden)
              (call-interactively (key-binding (kbd "e"))))
            (set-buffer (plist-get (gethash '(base child bolden) emacsvox-aural-voice-editor--contexts) :buffer))
            (emacsvox-aural-voice-editor--put :automatic-sample nil)
            (emacsvox-aural-voice-editor--set 'average-pitch 8)
            (emacsvox-aural-voice-editor-save-to-collection)
            (should (assq 'bolden (plist-get (emacsvox-aural-voice-drafts--palette-data 'child) :entries)))
            (with-current-buffer source
              (emacsvox-aural-voice-palette-previews-refresh 'bolden)
              (should-error (call-interactively (key-binding (kbd "d"))) :type 'user-error)
              (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
                (call-interactively (key-binding (kbd "R"))))
              (should (eq (tabulated-list-get-id) 'bolden))
              (should-not (gethash '(base child bolden) emacsvox-aural-voice-editor--contexts))
              (call-interactively (key-binding (kbd "e"))))
            (set-buffer (plist-get (gethash '(base child bolden) emacsvox-aural-voice-editor--contexts) :buffer))
            (should-not (plist-get (emacsvox-aural-voice-drafts--palette-data 'child) :entries))
            (should (equal original (emacsvox-aural-voice-runtime--resolve 'bolden 'child)))
            (should (equal parent (emacsvox-aural-voice-drafts--palette-data 'reading-owned)))
            (should (equal (plist-get (emacsvox-aural-voice-editor--working) :definition)
                           (plist-get original :definition))))
        (when (buffer-live-p source) (kill-buffer source))))))

(ert-deftest emacsvox-aural-voice-editor-copy-built-in-is-a-personal-draft ()
  :tags '(voice-style-ui)
  (emacsvox-test--with-voice-editor
    (let ((before (emacsvox-aural-read-user-data))
          (root (emacsvox-aural-voice-drafts--palette-data 'acss-default))
          (selected (emacsvox-aural-effective-voice-palette)))
      (emacsvox-aural-voice-editor--copy 'acss-default 'bolden 'custom-copy (current-buffer) "Sample")
      (should (equal before (emacsvox-aural-read-user-data)))
      (should (eq (emacsvox-aural-effective-voice-palette) selected))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "copied-child")))
        (emacsvox-aural-voice-editor-save-to-collection))
      (let ((data (emacsvox-aural-voice-drafts--palette-data 'copied-child)))
        (should (eq (plist-get data :parent) 'acss-default))
        (should (equal (mapcar #'car (plist-get data :entries)) '(custom-copy)))
        (should (equal (plist-get (emacsvox-aural-voice-runtime--resolve 'custom-copy 'copied-child) :definition)
                       (plist-get (emacsvox-aural-voice-runtime--resolve 'bolden 'acss-default) :definition))))
      (should (equal root (emacsvox-aural-voice-drafts--palette-data 'acss-default)))
      (should (eq (emacsvox-aural-effective-voice-palette) selected)))))

(ert-deftest emacsvox-aural-voice-editor-opening-is-read-only-and-labels-shared-scope ()
  (emacsvox-test--with-voice-editor
   (let ((before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
     (emacsvox-aural-voice-editor-open 'source-child 'voice-bolden)
     (should (derived-mode-p 'emacsvox-aural-voice-editor-mode))
     (should (string-match-p "First save creates an independent copy" (buffer-string)))
     (should (string-match-p "every fallback choice" (buffer-string)))
     (should (eq emacsvox-aural-voice-palette-override 'reading-owned))
     (should-not callbacks)
     (should (equal before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file))))))

(ert-deftest emacsvox-aural-voice-editor-home-tuning-resumes-the-base-draft ()
  "The point action opens the existing named-voice editor without saving."
  (require 'emacsvox-aural-change-feedback)
  (emacsvox-test--with-voice-editor
   (save-window-excursion
     (with-temp-buffer
       (switch-to-buffer (current-buffer))
       (let ((source (current-buffer))
             (voice-setup-face-voice-table (copy-hash-table voice-setup-face-voice-table))
             (before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
         (puthash 'bold 'voice-bolden voice-setup-face-voice-table)
         (insert (propertize "Example heading" 'face 'bold))
         (goto-char 1)
         (emacsvox-aural-change-feedback--tune-at-point)
         (with-current-buffer (window-buffer (selected-window))
           (should (derived-mode-p 'emacsvox-aural-voice-editor-mode))
           (should (eq (emacsvox-aural-voice-editor--get :voice) 'bolden))
           (should (eq (emacsvox-aural-voice-editor--get :palette) 'reading-owned))
           (should (equal (emacsvox-aural-voice-editor--get :text) "Example heading"))
           (should (eq (marker-buffer (emacsvox-aural-voice-editor--get :origin)) source))
           (let ((draft (emacsvox-aural-voice-editor--draft)))
             (with-current-buffer source
               (emacsvox-aural-change-feedback--tune-at-point))
             (should (eq draft (emacsvox-aural-voice-editor--draft)))))
         (should-not callbacks)
         (should (equal before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file))))))))

(ert-deftest emacsvox-aural-voice-editor-new-standard-voice-saves-personal-child ()
  "New Voice is a retained neutral draft; save writes only a personal child."
  (emacsvox-test--with-voice-editor
   (let* ((root '(:schema-version 3 :id acss-default :summary "Standard"
                  :parent nil :routing owned
                  :entries ((bolden :personality voice-bolden :choices nil))))
          (before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
     (puthash 'acss-default (emacsvox-aural-compile-voice-palette-data root t)
              emacsvox-aural-voice-palette-registry)
     (emacsvox-aural-voice-editor-new 'acss-default 'custom)
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (let ((draft (emacsvox-aural-voice-editor--draft)))
       (should (emacsvox-aural-voice-drafts--dirty-fields draft))
       (should-not (plist-get (emacsvox-aural-voice-editor--working) :choices))
       (should (equal (plist-get (emacsvox-aural-voice-editor--working) :definition)
                      '(:family nil :average-pitch nil :pitch-range nil
                        :stress nil :richness nil)))
       (emacsvox-aural-voice-editor--set 'average-pitch 0)
       (emacsvox-aural-voice-editor-new 'acss-default 'custom)
       (should (eq draft (emacsvox-aural-voice-editor--draft)))
       (should (equal before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
       (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "personal")))
         (emacsvox-aural-voice-editor-save-to-collection))
       (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
       (should-not (emacsvox-aural-voice-editor--get :new))
       (let ((saved (emacsvox-aural-voice-drafts--palette-data 'personal)))
         (should (= (plist-get saved :schema-version) 3))
         (should (eq (plist-get saved :parent) 'acss-default))
         (should (equal (mapcar #'car (plist-get saved :entries)) '(custom)))
         (should (= (plist-get (emacsvox-aural-voice 'custom 'personal) :average-pitch) 0)))
       (should (equal root (emacsvox-aural-voice-drafts--palette-data 'acss-default)))
       (should (eq emacsvox-aural-voice-palette-override 'reading-owned))
       (should-not callbacks)
       (emacsvox-aural-voice-editor-open 'personal 'custom)
       (emacsvox-aural-voice-editor-save-to-collection)
       (should (eq draft (emacsvox-aural-voice-editor--draft))))
     (emacsvox-aural-voice-editor-new 'personal 'second-custom)
     (emacsvox-aural-voice-editor-save-to-collection)
     (should (assq 'second-custom
                   (plist-get (emacsvox-aural-voice-drafts--palette-data 'personal)
                              :entries)))
     (should (eq emacsvox-aural-voice-palette-override 'reading-owned)))))

(ert-deftest emacsvox-aural-voice-editor-new-rejects-existing-and-alias-names ()
  "New cannot overwrite an inherited voice or claim a reserved alias."
  (emacsvox-test--with-voice-editor
   (should-error (emacsvox-aural-voice-editor-new 'reading-owned 'bolden)
                 :type 'user-error)
   (should-error (emacsvox-aural-voice-editor-new 'reading-owned 'voice-bolden)
                 :type 'user-error)
   (should-error (emacsvox-aural-voice-editor-open 'reading-owned 'missing)
                 :type 'user-error)))

(ert-deftest emacsvox-aural-voice-editor-discard-new-voice-starts-clean ()
  "Discard removes an uncreated voice; reopening starts with a neutral draft."
  (emacsvox-test--with-voice-editor
   (with-temp-buffer
     (switch-to-buffer (current-buffer))
     (let ((before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
       (emacsvox-aural-voice-editor-new 'reading-owned 'custom)
       (emacsvox-aural-voice-editor--put :automatic-sample nil)
       (emacsvox-aural-voice-editor--set 'average-pitch 8)
       (let ((old (emacsvox-aural-voice-editor--draft)) (view (current-buffer)))
         (cl-letf (((symbol-function 'completing-read)
                    (lambda (&rest _) "Discard changes and return")))
           (emacsvox-aural-voice-editor-leave))
         (should-not (buffer-live-p view))
         (should-not (gethash '(base reading-owned custom) emacsvox-aural-voice-editor--contexts))
         (emacsvox-aural-voice-editor-new 'reading-owned 'custom)
         (should-not (eq old (emacsvox-aural-voice-editor--draft)))
         (should-not (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition)
                                :average-pitch)))
       (should (equal before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))))))

(ert-deftest emacsvox-aural-voice-editor-comparison-and-save-retain-newer-changes ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'average-pitch 8)
   (emacsvox-aural-voice-editor-compare)
   (let ((entries (car requests)))
     (should (= (length entries) 4))
     (should (= (plist-get (plist-get (nth 1 entries) :acss) :average-pitch) 0))
     (should (= (plist-get (plist-get (nth 3 entries) :acss) :average-pitch) (/ 8.0 9)))
     (should (equal (plist-get (nth 1 entries) :selectors) (plist-get (nth 3 entries) :selectors))))
   (emacsvox-aural-voice-editor-save)
   (should (= (length callbacks) 1))
   (let ((draft (emacsvox-aural-voice-editor--draft)))
     (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
     (emacsvox-aural-voice-editor--set 'average-pitch 9)
     (funcall (car callbacks) '(:status applied))
     (should (emacsvox-aural-voice-drafts--dirty-fields draft))
     (should (string-match-p "Unsaved changes" header-line-format))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-draft-original draft) :definition) :average-pitch) 8)))))

(ert-deftest emacsvox-aural-voice-editor-filter-direction-cancelled-picker-and-return-position ()
  (emacsvox-test--with-voice-editor
   (let ((origin (generate-new-buffer " *voice-editor-origin*")))
     (unwind-protect
         (progn
           (switch-to-buffer origin) (insert "row one\nrow two\n") (goto-char 12)
           (emacsvox-aural-voice-editor-open 'reading-owned 'bolden origin)
           (emacsvox-aural-voice-editor--put :automatic-sample nil)
           (emacsvox-aural-voice-editor--set 'low-pass 3)
           (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :low-pass) 6))
           (let ((before (emacsvox-aural-voice-editor--working)))
             (cl-letf (((symbol-function 'emacsvox-aural-voice-editor--pick) (lambda () (user-error "Cancelled"))))
               (should-error (emacsvox-aural-voice-editor-choose 0)))
             (should (equal before (emacsvox-aural-voice-editor--working))))
           (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Keep draft and return")))
             (emacsvox-aural-voice-editor-leave))
           (should (eq (current-buffer) origin))
           (should (= (point) 12)))
       (kill-buffer origin)))))

(ert-deftest emacsvox-aural-voice-editor-experiment-destination-preserves-fallbacks ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "new") (:voice-id "New voice" :language "en")) (current-buffer) "Sample")
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 8)
   (let ((answers '("reading-owned" "bolden" "Physical voice and shared adjustments — all inheriting choices" "Add as fallback")))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (pop answers))))
       (emacsvox-aural-voice-editor-keep-experiment)))
   (let ((working (emacsvox-aural-voice-editor--working)))
     (should (= (length (plist-get working :selectors)) 3))
     (should (equal (plist-get (car (plist-get working :selectors)) :engine-id) "dectalk"))
     (should (= (plist-get (plist-get working :definition) :richness) 8))
     (should-not callbacks)
     (should (equal (emacsvox-aural-voice-editor--get :voice) 'bolden)))))

(ert-deftest emacsvox-aural-voice-editor-both-named-entry-points-resume-the-same-draft ()
  (emacsvox-test--with-voice-editor
   (switch-to-buffer (with-temp-buffer
                       (emacsvox-aural-voice-palette-previews-mode)
                       (setq emacsvox-aural-voice-palette-previews-palette 'reading-owned)
                       (cl-letf (((symbol-function 'emacsvox-aural-voice-palette-previews--current-voice) (lambda () 'bolden)))
                         (emacsvox-aural-voice-palette-previews-tune))))
   (let ((first (emacsvox-aural-voice-editor--draft)))
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (emacsvox-aural-voice-editor--set 'richness 7)
     (switch-to-buffer (with-temp-buffer
                         (setq emacsvox-aural-voice-workbench-view 'logical)
                         (insert (propertize "Bolden" 'tabulated-list-id "voice-bolden"))
                         (goto-char (point-min))
                         (cl-letf (((symbol-function 'emacsvox-aural-voice-workbench--active-palette) (lambda () 'reading-owned)))
                           (emacsvox-aural-voice-workbench-tune))))
     (should (eq first (emacsvox-aural-voice-editor--draft)))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :richness) 7))
     (should-not callbacks))))

(ert-deftest emacsvox-aural-voice-editor-killed-draft-remains-discoverable-from-home ()
  (emacsvox-test--with-voice-editor
   (require 'emacsvox-aural-home)
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 7)
   (let ((context emacsvox-aural-voice-editor--context))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Keep draft and return"))) (kill-buffer))
     (should (memq context (emacsvox-aural-home--pending-drafts)))
     (emacsvox-aural-voice-editor--show context (current-buffer))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :richness) 7)))))

(ert-deftest emacsvox-aural-voice-editor-converted-draft-becomes-independent-on-first-save ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'source-child 'voice-bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 7)
   (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new-personal")))
     (emacsvox-aural-voice-editor-save))
   (funcall (car callbacks) '(:status applied))
   (should (eq (emacsvox-aural-voice-editor--get :palette) 'new-personal))
   (let ((source (emacsvox-aural-voice-drafts--palette-data 'source-child)))
     (setq source (plist-put source :summary "Changed source"))
     (puthash 'source-child (emacsvox-aural-compile-voice-palette-data source) emacsvox-aural-voice-palette-registry))
   (emacsvox-aural-voice-editor--set 'richness 8)
   (emacsvox-aural-voice-editor-save)
   (should (= (length callbacks) 2))
   (should (= (plist-get (cdr (assq 'bolden (emacsvox-aural-voice-palette-entries
                                             (gethash 'new-personal emacsvox-aural-voice-palette-registry)))) :richness) 8))))

(ert-deftest emacsvox-aural-voice-editor-picker-auditions-without-editing ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (let ((before (emacsvox-aural-voice-editor--working))
         (answers '("Candidate" "Audition candidate" "Cancel")))
     (cl-letf (((symbol-function 'emacsvox-aural-voice-workbench--physical-candidates)
                (lambda (&rest _) '(("Candidate" (:engine-id "test") (:voice-id "one")))))
               ((symbol-function 'completing-read) (lambda (&rest _) (pop answers))))
       (should-error (emacsvox-aural-voice-editor-choose 0)))
     (should (equal (plist-get (plist-get (caar requests) :selector) :voice-id) "one"))
     (should (equal before (emacsvox-aural-voice-editor--working))))))

(ert-deftest emacsvox-aural-voice-editor-return-after-refresh-and-standard-actions ()
  (emacsvox-test--with-voice-editor
   (let ((origin (generate-new-buffer " *voice-editor-table*")) column)
     (unwind-protect
         (progn
           (switch-to-buffer origin)
           (emacsvox-aural-voice-palette-previews-mode)
           (setq emacsvox-aural-voice-palette-previews-palette 'reading-owned)
           (emacsvox-aural-voice-palette-previews-refresh)
           (emacsvox-aural-ui-goto-row 'bolden)
           (move-to-column 25)
           (setq column (current-column))
           (emacsvox-aural-voice-editor-open 'reading-owned 'bolden origin)
           (should (eq (key-binding (kbd "C-c C-i")) #'emacsvox-aural-ui-open-manual))
           (emacsvox-aural-voice-editor--locate 'more)
           (call-interactively (key-binding (kbd "RET")))
           (should (emacsvox-aural-voice-editor--get :effects))
           (emacsvox-aural-voice-editor--put :automatic-sample nil)
           (emacsvox-aural-voice-editor--set 'richness 8)
           (emacsvox-aural-voice-editor-save)
           (funcall (car callbacks) '(:status applied))
           (should (cl-some (lambda (text) (string-match-p "Saved and applied" text)) speech))
           (emacsvox-aural-voice-editor-leave)
           (should (eq (current-buffer) origin))
           (should (eq (tabulated-list-get-id) 'bolden))
           (should (= (current-column) column)))
       (kill-buffer origin)))))

(ert-deftest emacsvox-aural-voice-editor-adjustment-sample-starts-with-displayed-value ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "test") (:voice-id "one")) (current-buffer) "The quick brown fox.")
   (emacsvox-aural-voice-editor--locate 'average-pitch)
   (setq speech nil)
   (emacsvox-aural-voice-editor-increase)
   (should (equal (plist-get (caar requests) :text) "1. The quick brown fox."))
   (should-not speech)
   (emacsvox-aural-voice-editor-increase)
   (should (equal (plist-get (caar requests) :text) "2. The quick brown fox."))
   (emacsvox-aural-voice-editor--set 'low-pass 3)
   (should (equal (plist-get (caar requests) :text) "3. The quick brown fox."))
   (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :low-pass) 6))
   (emacsvox-aural-voice-editor--set 'average-pitch nil)
   (should (equal (plist-get (caar requests) :text) "Adapter default. The quick brown fox."))
   (should (equal (emacsvox-aural-voice-editor--get :text) "The quick brown fox."))
   (emacsvox-aural-voice-editor-play)
   (should (equal (plist-get (caar requests) :text) "The quick brown fox."))))

(ert-deftest emacsvox-aural-voice-editor-adjustment-boundaries-preserve-the-draft ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (dimension '(rate-offset average-pitch pitch-range stress richness
                       gain low-pass high-pass pan reverb echo chorus))
     (emacsvox-aural-voice-editor--locate dimension)
     (dolist (bound (if (eq dimension 'rate-offset) '(-20 20) '(0 9)))
       (emacsvox-aural-voice-editor--set dimension bound)
       (let ((before (emacsvox-aural-voice-editor--working))
             (history (copy-tree (emacsvox-aural-voice-draft-history (emacsvox-aural-voice-editor--draft))))
             (count (length requests)))
         (emacsvox-aural-voice-editor-adjust (if (> bound 0) 1 -1))
         (should (equal before (emacsvox-aural-voice-editor--working)))
         (should (equal history (emacsvox-aural-voice-draft-history (emacsvox-aural-voice-editor--draft))))
         (should (= count (length requests)))
         (should (equal (car speech) (format "%s %s" (if (> bound 0) "Maximum" "Minimum") bound))))))))

(ert-deftest emacsvox-aural-voice-editor-invalid-entry-reports-control-range ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (dolist (entry '((average-pitch "10" "0 to 9") (low-pass "-1" "0 to 9")
                    (rate-offset "21" "-20 to 20")))
     (let ((before (emacsvox-aural-voice-editor--working)))
       (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (nth 1 entry))))
         (let ((error (should-error (emacsvox-aural-voice-editor-edit (car entry)) :type 'user-error)))
           (should (string-match-p (nth 2 entry) (error-message-string error)))))
       (should (equal before (emacsvox-aural-voice-editor--working)))))
   (should-not requests)))

(ert-deftest emacsvox-aural-voice-editor-automatic-sample-toggle-speaks-state ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--locate 'auto-sample)
   (call-interactively (key-binding (kbd "RET")))
   (should (equal (car speech) "Automatic sample after adjustment: off"))
   (emacsvox-aural-voice-editor--locate 'average-pitch)
   (emacsvox-aural-voice-editor-increase)
   (should-not requests)
   (should (string-prefix-p "Average Pitch:" (car speech)))
   (emacsvox-aural-voice-editor--locate 'auto-sample)
   (call-interactively (key-binding (kbd "RET")))
   (should (equal (car speech) "Automatic sample after adjustment: on"))
   (should-not requests)))

(ert-deftest emacsvox-aural-voice-editor-field-navigation-stops-at-both-ends ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--locate 'save)
   (let ((first (point)))
     (call-interactively (key-binding (kbd "<up>")))
     (should (= first (point)))
     (should (string-prefix-p "First field." (car speech)))
     (call-interactively (key-binding (kbd "<down>")))
     (should (> (point) first))
     (call-interactively (key-binding (kbd "<up>")))
     (should (= first (point))))
   (goto-char (button-start (previous-button (point-max))))
   (let ((last (point)))
     (call-interactively (key-binding (kbd "<down>")))
     (should (= last (point)))
     (should (string-prefix-p "Last field." (car speech)))
     (call-interactively (key-binding (kbd "TAB")))
     (should (= last (point)))
     (call-interactively (key-binding (kbd "<up>")))
     (should (< (point) last))
     (call-interactively (key-binding (kbd "<down>")))
     (should (= last (point))))))

(ert-deftest emacsvox-aural-voice-editor-toggle-keys-announce-state-after-distinct-cues ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (let (events)
     (cl-letf (((symbol-function 'emacsvox-icon) (lambda (icon) (push icon events)))
               ((symbol-function 'tts-speak) (lambda (text &rest _) (push text events))))
       (dolist (case '((more "More adjustments and effects" "expanded" "collapsed")
                       (auto-sample "Automatic sample after adjustment" "off" "on")
                       (fallbacks "Fallbacks" "expanded" "collapsed")))
         (emacsvox-aural-voice-editor--locate (car case))
         (should (eq (key-binding (kbd "RET")) #'emacsvox-aural-voice-editor-activate))
         (dolist (state (cddr case))
           (setq events nil)
           (call-interactively (key-binding (kbd "RET")))
           (if (eq (car case) 'auto-sample)
               (progn
                 (should (= (length events) 1))
                 (should (string-prefix-p (cadr case) (car events)))
                 (should (string-suffix-p state (car events)))
                 (should (eq (get-text-property 0 'auditory-icon (car events))
                             (if (equal state "on") 'on 'off))))
             (should (= (length events) 1))
             (should (string-prefix-p (cadr case) (car events)))
             (should (eq (plist-get (get-text-property 0 'emacsvox-aural-facts (car events)) :visibility)
                         (if (equal state "expanded") 'expanded 'folded)))
             (should-not (string-match-p "expanded\\|collapsed" (button-label (button-at (point))))))
           (should (eq (get-text-property (point) 'voice-field) (car case)))
           (let ((label (button-label (button-at (point)))))
             (call-interactively (key-binding (kbd "<down>")))
             (call-interactively (key-binding (kbd "<up>")))
             (should (equal (car events) label))))))
     (should-not requests))))

(ert-deftest emacsvox-aural-voice-editor-horizontal-arrows-navigate-nonnumeric-fields ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (let ((before (emacsvox-aural-voice-editor--working)))
     (dolist (field '(save primary family more auto-sample))
       (emacsvox-aural-voice-editor--locate field)
       (let ((position (point)))
         (call-interactively (key-binding (kbd "<right>")))
         (should (> (point) position))
         (should (equal (car speech) (button-label (button-at (point)))))))
     (emacsvox-aural-voice-editor--locate 'auto-sample)
     (call-interactively (key-binding (kbd "<left>")))
     (should (eq (get-text-property (point) 'voice-field) 'text))
     (goto-char (point-min))
     (call-interactively (key-binding (kbd "<right>")))
     (should (eq (get-text-property (point) 'voice-field) 'save))
     (should (equal before (emacsvox-aural-voice-editor--working)))
     (should-not requests))))

(ert-deftest emacsvox-aural-voice-editor-default-key-clears-zero-and-can-be-undone ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "test") (:voice-id "one")) (current-buffer) "Sample.")
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (dimension '(rate-offset average-pitch low-pass gain pan))
     (emacsvox-aural-voice-editor--locate dimension)
     (emacsvox-aural-voice-editor--set dimension 0)
     (let* ((key (emacsvox-aural--voice-dimension-key dimension))
            (stored (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key)))
       (should (numberp stored))
       (call-interactively (key-binding (kbd "d")))
       (should-not (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key))
       (should (string-match-p "adapter default" (button-label (button-at (point)))))
       (should (equal (plist-get (caar requests) :text) "Adapter default. Sample."))
       (emacsvox-aural-voice-editor-undo)
       (should (equal stored (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key)))))))

(ert-deftest emacsvox-aural-voice-editor-leave-dismisses-window-before-workbench-quit ()
  (emacsvox-test--with-voice-editor
   (save-window-excursion
     (let ((source (generate-new-buffer " *voice-quit-source*"))
           (workbench (generate-new-buffer " *voice-quit-workbench*")))
       (unwind-protect
           (cl-letf (((symbol-function 'emacsvox-speak-mode-line) #'ignore))
             (dolist (same-window '(t nil))
               (delete-other-windows)
               (switch-to-buffer source)
               (let ((display-buffer-overriding-action
                      (if same-window '(display-buffer-same-window)
                        '(display-buffer-pop-up-window))))
                 (pop-to-buffer workbench)
                 (emacsvox-aural-voice-workbench-mode)
                 (setq emacsvox-aural-voice-workbench-view 'engines)
                 (emacsvox-aural-voice-editor-experiment
                  '((:engine-id "test") (:voice-id "one")) workbench "Sample.")
                 (let ((editor (current-buffer))
                       (context emacsvox-aural-voice-editor--context))
                   (call-interactively (key-binding (kbd "q")))
                   (should (eq (current-buffer) workbench))
                   (should (buffer-live-p editor))
                   (should-not (get-buffer-window editor))
                   (call-interactively (key-binding (kbd "q")))
                   (should-not (eq (current-buffer) editor))
                   (should-not (get-buffer-window editor))
                   ;; Leaving retains the experiment, without making it the
                   ;; destination of a later workbench quit.
                   (should (eq (plist-get context :buffer) editor))))))
         (kill-buffer workbench)
         (kill-buffer source))))))

(defmacro emacsvox-test--with-layered-editor (&rest body)
  "Run BODY through the real private preview service with a synthetic draft."
  (declare (indent 0) (debug t))
  `(emacsvox-test--with-voice-editor
    (emacsvox-test--with-complete-preview
     (omnivox-preview-test--bundle speaker)
     (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (let* ((entry (omnivox-preview-test--layered))
            (voice (plist-get entry :voice))
            (snapshot (list :definition (plist-get voice :shared) :language (plist-get voice :language)
                            :choices (plist-get voice :choices)
                            :selectors (emacsvox-aural-voice-data--selectors (plist-get voice :choices))))
            (draft (emacsvox-aural-voice-editor--draft)))
       (setf (emacsvox-aural-voice-draft-baseline draft) (copy-tree snapshot)
             (emacsvox-aural-voice-draft-original draft) (copy-tree snapshot)
             (emacsvox-aural-voice-draft-working draft) (copy-tree snapshot))
       (emacsvox-aural-voice-editor--put :policy '(:engine-order ("eloquence") :disabled-engines ("winrt")
                                                 :fallback (:engines ("espeak"))))
       ;; Opening the interface configures punctuation before the tested action.
       (setq writes nil stops 0)
       ,@body))))

(ert-deftest emacsvox-aural-voice-editor-v2-connects-complete-draft-to-actual-evidence ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor-play)
   (let ((request (emacsvox-test--omnivox-decode-command (car writes))))
     (should (equal (plist-get request :type) "preview_voice_v2"))
     (should (= (length (plist-get (plist-get request :voice) :choices)) 3)))
   (should (emacsvox-aural-voice-editor--get :preview-operation))
   (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal))
   (should-not (emacsvox-aural-voice-editor--get :preview-operation))
   (should (string-match-p "last sample playback started on eloquence/Reed" (buffer-string)))
   (should (string-match-p "choice 2" (buffer-string)))
   (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-row-comparison-uses-original-id-after-reorder ()
  (emacsvox-test--with-layered-editor
   (let* ((snapshot (emacsvox-aural-voice-editor--working))
          (rows (emacsvox-aural-voice-data--move-choice (plist-get snapshot :choices) "alternate" 2)))
     (plist-put snapshot :choices rows)
     (plist-put snapshot :selectors (emacsvox-aural-voice-data--selectors rows))
     (emacsvox-aural-voice-drafts--edit draft snapshot))
   (emacsvox-aural-voice-editor--preview t "alternate")
   (dotimes (index 4)
     (let* ((request (emacsvox-test--omnivox-decode-command (car writes)))
            (position (if (< index 2) 1 2))
            (response (omnivox-preview-test--terminal (+ 41 index)))
            (identity (omnivox-preview-test--identity "alternate" position)))
       (should (equal (plist-get request :selection) '(:mode "choice" :choice_id "alternate")))
       (should (equal (plist-get (nth position (plist-get (plist-get request :voice) :choices)) :id) "alternate"))
       (plist-put response :last_started identity)
       (plist-put response :accepted_audio (vector (append identity '(:playback_started t))))
       (omnivox-preview-test--control-line speaker response)))
   (let ((entries (plist-get (emacsvox-aural-voice-editor--get :preview-result) :results)))
     (should (equal (mapcar (lambda (entry) (plist-get (plist-get entry :request-snapshot) :role)) entries)
                    '(label sample label sample))))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-new-row-has-no-original-comparison ()
  (emacsvox-test--with-layered-editor
   (let* ((snapshot (emacsvox-aural-voice-editor--working)) (row (car (plist-get snapshot :choices))))
     (plist-put row :id "new")
     (emacsvox-aural-voice-drafts--edit draft snapshot))
   (should-error (emacsvox-aural-voice-editor--preview t "new"))
   (should-not writes) (should (= stops 0))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-input-changes-retire-preview-before-late-replies ()
  (dolist (change '(text undo save))
    (emacsvox-test--with-layered-editor
     (emacsvox-aural-voice-editor--set 'richness 8)
     (emacsvox-aural-voice-editor-play)
     (let ((revision (emacsvox-aural-voice-draft-revision draft)))
       (pcase change
         ('text (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "New sample")))
                  (emacsvox-aural-voice-editor-text)))
         ('undo (emacsvox-aural-voice-editor-undo))
         ('save (emacsvox-aural-voice-editor-save-to-collection)))
       (unless (eq change 'text) (should (> (emacsvox-aural-voice-draft-revision draft) revision))))
     (omnivox-preview-test--clean speaker)
     (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal))
     (should-not (emacsvox-aural-voice-editor--get :preview-result)))))

(ert-deftest emacsvox-aural-voice-editor-v2-preflight-guard-observes-draft-revision ()
  (emacsvox-test--with-layered-editor
   (let ((prepare (symbol-function 'omnivox--preview-layered-request)))
     (cl-letf (((symbol-function 'omnivox--preview-layered-request)
                (lambda (&rest arguments)
                  (prog1 (apply prepare arguments) (emacsvox-aural-voice-editor--set 'richness 8)))))
       (should-error (emacsvox-aural-voice-editor-play))))
   (should-not writes) (should (= stops 0))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-preflight-keeps-old-token-until-admission ()
  (dolist (change '(reject stop))
    (emacsvox-test--with-layered-editor
     (emacsvox-aural-voice-editor-play)
     (let ((old (emacsvox-aural-voice-editor--get :preview-operation))
           (prepare (symbol-function 'omnivox--preview-layered-request)))
       (cl-letf (((symbol-function 'omnivox--preview-layered-request)
                  (lambda (&rest arguments)
                    (if (eq change 'reject) (error "Invalid later projection")
                      (prog1 (apply prepare arguments) (emacsvox-aural-voice-editor-stop))))))
         (should-error (emacsvox-aural-voice-editor-play)))
       (when (eq change 'reject)
         (should (= stops 1))
         (should (eq old (process-get speaker 'omnivox--preview-operation)))
         (should (eq old (emacsvox-aural-voice-editor--get :preview-operation)))
         (emacsvox-aural-voice-editor-stop)))
     (should (= stops 2))
     (should (= (length writes) 1))
     (omnivox-preview-test--clean speaker))))

(ert-deftest emacsvox-aural-voice-editor-v2-reentrant-startup-keeps-newest-view-owner ()
  (emacsvox-test--with-layered-editor
   (let (started)
     (let ((hook (lambda (_process)
                   (unless started (setq started t) (emacsvox-aural-voice-editor-play)))))
       (add-hook 'tts-stopped-hook hook)
       (emacsvox-aural-voice-editor-play)
       (remove-hook 'tts-stopped-hook hook)))
   (should (= (length writes) 1))
   (should (eq (emacsvox-aural-voice-editor--get :preview-operation)
               (process-get speaker 'omnivox--preview-operation)))
   (should-not (emacsvox-aural-voice-editor--get :preview-startup))
   (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal))
   (should (eq (plist-get (emacsvox-aural-voice-editor--get :preview-result) :status) 'completed))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-killed-view-cannot-write-into-the-return-buffer ()
  (emacsvox-test--with-layered-editor
   (let ((context emacsvox-aural-voice-editor--context)
         (prepare (symbol-function 'omnivox--preview-layered-request))
         (other (generate-new-buffer " *preview-return-buffer*")))
     (unwind-protect
         (progn
           (cl-letf (((symbol-function 'omnivox--preview-layered-request)
                      (lambda (&rest arguments)
                        (prog1 (apply prepare arguments)
                          (kill-buffer (current-buffer)) (set-buffer other)))))
             (should-error (emacsvox-aural-voice-editor-play)))
           (should-not (buffer-local-value 'emacsvox-aural-voice-editor--context other))
           (should-not (plist-get context :preview-startup))
           (should-not writes) (should (= stops 0))
           (omnivox-preview-test--clean speaker))
       (kill-buffer other)))))

(ert-deftest emacsvox-aural-voice-editor-v2-legacy-gates-before-stop ()
  (emacsvox-test--with-layered-editor
   (process-put speaker omnivox--control-capabilities-property
                '(:features ("voice_chain_preview_v1" "exact_voice_preview" "relative_rate_v1" "post_synthesis_effects_v1")))
   (should-error (emacsvox-aural-voice-editor-play))
   (should-error (emacsvox-aural-voice-editor--preview nil "soft"))
   (should (= stops 0)) (should-not writes)
   (let* ((snapshot (emacsvox-aural-voice-editor--working))
          (row (nth 1 (plist-get snapshot :choices))))
     (plist-put row :adjustments '(:richness 0))
     (emacsvox-aural-voice-drafts--edit draft snapshot))
   (emacsvox-aural-voice-editor--preview nil "alternate")
   (should (equal (plist-get (emacsvox-test--omnivox-decode-command (car writes)) :type) "preview"))
   (emacsvox-aural-voice-editor-stop)
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-old-view-stop-cannot-cancel-new-service-owner ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor-play)
   (omnivox--preview-layered-sequence (list (omnivox-preview-test--layered)) #'ignore)
   (let ((before stops) (new (process-get speaker 'omnivox--preview-operation)))
     (emacsvox-aural-voice-editor-stop)
     (should (= stops before))
     (should (eq new (process-get speaker 'omnivox--preview-operation))))
   (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal 42))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-v2-label-start-cannot-stand-in-for-sample ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor-compare)
   (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal))
   (let ((response (omnivox-preview-test--terminal 42)))
     (plist-put response :status "failed")
     (plist-put response :accepted_audio [])
     (plist-put response :last_started :null)
     (omnivox-preview-test--control-line speaker response))
   (let ((status (emacsvox-aural-voice-editor--preview-status (emacsvox-aural-voice-editor--get :preview-result))))
     (should (string-match-p "no sample start confirmed" status))
     (should-not (string-match-p "last sample playback started" status)))
   (should (= (length writes) 2))
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-row-states-preserve-shared-and-other-rows ()
  (emacsvox-test--with-layered-editor
   (let ((before (emacsvox-aural-voice-editor--working)))
     (emacsvox-aural-voice-editor--customize "alternate")
     (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
     (should (string-match-p "Customizing" (car speech)))
     (emacsvox-aural-voice-editor--locate 'richness)
     (emacsvox-aural-voice-editor--set 'richness 0)
     (should (equal (plist-get (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments) :richness) 0))
     (should (string-match-p "custom value" (button-label (button-at (point)))))
     (emacsvox-aural-voice-editor-default)
     (let ((patch (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments)))
       (should (plist-member patch :richness)) (should-not (plist-get patch :richness)))
     (should (string-match-p "explicit adapter default" (button-label (button-at (point)))))
     (call-interactively (key-binding (kbd "i")))
     (should-not (plist-member (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments) :richness))
     (should (string-match-p "use shared value" (button-label (button-at (point)))))
     (let ((after (emacsvox-aural-voice-editor--working)))
       (should (equal (plist-get before :definition) (plist-get after :definition)))
       (should (equal (car (plist-get before :choices)) (car (plist-get after :choices))))
       (should (equal (nth 2 (plist-get before :choices)) (nth 2 (plist-get after :choices)))))
     (emacsvox-aural-voice-editor-undo)
     (should (plist-member (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments) :richness))
     (emacsvox-aural-voice-editor--customize nil)
     (should (string-match-p "Shared adjustments" (buffer-string))))))

(ert-deftest emacsvox-aural-voice-editor-row-controls-submit-default-zero-inherit-and-low-pass ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--customize "alternate")
   (emacsvox-aural-voice-editor--put :automatic-sample t)
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (case '((low-pass 1 :low_pass "set" "1.") (richness 0 :richness "set" "0.")
                   (richness nil :richness "default" "Adapter default.")))
     (emacsvox-aural-voice-editor--set (nth 0 case) (nth 1 case))
     (let* ((request (emacsvox-test--omnivox-decode-command (car writes)))
            (rows (plist-get (plist-get request :voice) :choices))
            (operation (plist-get (plist-get (nth 1 rows) :adjustments) (nth 2 case))))
       (should (equal (plist-get request :selection) '(:mode "choice" :choice_id "alternate")))
       (should (= (length rows) 3))
       (should (equal (plist-get operation :op) (nth 3 case)))
       (should (string-prefix-p (nth 4 case) (plist-get request :text)))))
   (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments) :low-pass) 8))
   (emacsvox-aural-voice-editor--locate 'richness)
   (emacsvox-aural-voice-editor--inherit)
   (let* ((request (emacsvox-test--omnivox-decode-command (car writes)))
          (row (nth 1 (plist-get (plist-get request :voice) :choices))))
     (should-not (plist-member (plist-get row :adjustments) :richness))
     (should (string-prefix-p "Use shared value," (plist-get request :text))))
   (emacsvox-aural-voice-editor-stop)
   (omnivox-preview-test--clean speaker)))

(ert-deftest emacsvox-aural-voice-editor-row-tuning-follows-reorder-and-rejects-deletion ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--customize "alternate")
   (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Move later")))
     (emacsvox-aural-voice-editor-choice-actions "alternate"))
   (emacsvox-aural-voice-editor--set 'richness 2)
   (should (= (plist-get (plist-get (nth 2 (plist-get (emacsvox-aural-voice-editor--working) :choices)) :adjustments) :richness) 2))
   (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Remove")))
     (emacsvox-aural-voice-editor-choice-actions "alternate"))
   (should (string-match-p "fallback was removed" (buffer-string)))
   (let ((before (emacsvox-aural-voice-editor--working)))
     (should-error (emacsvox-aural-voice-editor--set 'richness 3))
     (should-error (emacsvox-aural-voice-editor-play))
     (should (equal before (emacsvox-aural-voice-editor--working))))
   (emacsvox-aural-voice-editor-undo)
   (should (equal "alternate" (plist-get (emacsvox-aural-voice-editor--tuning-row) :id)))))

(ert-deftest emacsvox-aural-voice-editor-row-ret-menu-guards-the-captured-target ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--customize "alternate")
   (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Adapter default")))
     (emacsvox-aural-voice-editor-edit 'richness))
   (should (plist-member (plist-get (emacsvox-aural-voice-editor--tuning-row) :adjustments) :richness))
   (cl-letf (((symbol-function 'completing-read)
              (lambda (&rest _) (emacsvox-aural-voice-editor--customize nil) "Use shared value")))
     (should-error (emacsvox-aural-voice-editor-edit 'richness)))
   (should (plist-member (plist-get (nth 1 (plist-get (emacsvox-aural-voice-editor--working) :choices)) :adjustments) :richness))
   (should-not writes)))

(ert-deftest emacsvox-aural-voice-editor-row-limits-and-shared-edits-retain-state ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--customize "alternate")
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (dimension '(rate-offset average-pitch pitch-range stress richness gain low-pass high-pass pan reverb echo chorus))
     (emacsvox-aural-voice-editor--locate dimension)
     (let* ((metadata (emacsvox-aural--voice-style-field dimension))
            (minimum (plist-get metadata :minimum)) (maximum (plist-get metadata :maximum)))
       (emacsvox-aural-voice-editor--set dimension maximum)
       (emacsvox-aural-voice-editor-increase)
       (should (equal (car speech) (format "Maximum %s" maximum)))
       (emacsvox-aural-voice-editor--set dimension minimum)
       (emacsvox-aural-voice-editor-decrease)
       (should (equal (car speech) (format "Minimum %s" minimum)))))
   (emacsvox-aural-voice-editor--set 'richness nil)
   (emacsvox-aural-voice-editor--set-choice 'average-pitch 'inherit nil)
   (emacsvox-aural-voice-editor--customize nil)
   (emacsvox-aural-voice-editor--set 'richness 8)
   (emacsvox-aural-voice-editor--set 'average-pitch 7)
   (emacsvox-aural-voice-editor--customize "alternate")
   (let ((style (emacsvox-aural-voice-editor--tuning-style (emacsvox-aural-voice-editor--working) 'reading-owned)))
     (should-not (plist-get style :richness))
     (should (= (plist-get style :average-pitch) 7)))))

(ert-deftest emacsvox-aural-voice-editor-field-details-use-frozen-started-sample ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor-play)
   (omnivox-preview-test--control-line speaker (omnivox-preview-test--terminal))
   (let ((before (emacsvox-aural-voice-editor--explain-playback (emacsvox-aural-voice-editor--get :preview-result))))
     (should (string-match-p "source choice" before))
     (should (string-match-p "explicit adapter default" before))
     (should (string-match-p "Unsupported by the engine" before))
     (emacsvox-aural-voice-editor--set 'richness 2)
     (let ((after (emacsvox-aural-voice-editor--explain-playback (emacsvox-aural-voice-editor--get :preview-result))))
       (should (string-match-p "Earlier preview" after))
       (should (equal after (replace-regexp-in-string "Preview completed" "Earlier preview completed" before)))))))

(ert-deftest emacsvox-aural-voice-editor-field-details-ignore-labels-and-accepted-audio ()
  (emacsvox-test--with-layered-editor
   (let* ((entry (omnivox-preview-test--layered))
          (result (list :preview-kind 'layered :status 'failed
                        :results (list (list :request-snapshot (plist-put (copy-tree entry) :role 'label)
                                             :last-started (omnivox-preview-test--identity))
                                       (list :request-snapshot entry :accepted-audio '(accepted))))))
     (should (string-match-p "No confirmed sample row" (emacsvox-aural-voice-editor--explain-playback result)))
     (should-not (string-match-p "source choice" (emacsvox-aural-voice-editor--explain-playback result))))))

(ert-deftest emacsvox-aural-voice-editor-individual-keep-merges-working-draft-and-retains-retry ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--set 'richness 7)
   (let* ((destination emacsvox-aural-voice-editor--context)
          (before (emacsvox-aural-voice-editor--working))
          (proposal (emacsvox-aural-voice-drafts--make-save :draft draft :state 'partial :completed '(local))))
     (setf (emacsvox-aural-voice-draft-proposal draft) proposal)
     (emacsvox-aural-voice-editor-experiment '((:engine-id "new") (:voice-id "new")) (current-buffer) "Sample")
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (emacsvox-aural-voice-editor--set 'richness 2)
     (let ((origin emacsvox-aural-voice-editor--context))
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (prompt collection &rest args)
                    (cond ((equal prompt "Destination palette: ") "reading-owned")
                          ((equal prompt "Use for named voice: ") "bolden")
                          ((equal prompt "Destination fallback: ") (car (nth 1 collection)))
                          ((equal prompt "Place physical voice: ") "Replace selected choice")
                          (t (nth 4 args))))))
         (emacsvox-aural-voice-editor-keep-experiment))
       (should (eq destination emacsvox-aural-voice-editor--context))
       (should (eq origin (emacsvox-aural-voice-editor--get :experiment)))
       (should (eq proposal (emacsvox-aural-voice-draft-proposal draft)))
       (should (eq (emacsvox-aural-voice-save-state proposal) 'partial))
       (let* ((after (emacsvox-aural-voice-editor--working)) (rows (plist-get after :choices)))
         (should (equal (plist-get before :definition) (plist-get after :definition)))
         (should (equal (car rows) (car (plist-get before :choices))))
         (should (equal (nth 2 rows) (nth 2 (plist-get before :choices))))
         (should (equal (plist-get (nth 1 rows) :id) "alternate"))
         (should (equal (plist-get (plist-get (nth 1 rows) :selector) :engine-id) "new"))
         (should (= (plist-get (plist-get (nth 1 rows) :adjustments) :richness) 2)))
       (emacsvox-aural-voice-editor-undo)
       (should (equal before (emacsvox-aural-voice-editor--working)))))))

(ert-deftest emacsvox-aural-voice-editor-experiment-keep-rejects-reentrant-input-changes ()
  (dolist (change '(origin destination cancel))
    (emacsvox-test--with-layered-editor
     (let ((destination draft) (before (emacsvox-aural-voice-editor--working)))
       (emacsvox-aural-voice-editor-experiment '((:engine-id "new") (:voice-id "new")) (current-buffer) "Sample")
       (emacsvox-aural-voice-editor--put :automatic-sample nil)
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (prompt _collection &rest args)
                    (cond ((equal prompt "Destination palette: ") "reading-owned")
                          ((equal prompt "Use for named voice: ") "bolden")
                          ((equal prompt "Place physical voice: ")
                           (pcase change
                             ('origin (emacsvox-aural-voice-editor--set 'richness 2))
                             ('destination (emacsvox-aural-voice-drafts--edit destination (plist-put (copy-tree before) :language "fr")))
                             ('cancel (user-error "Cancelled")))
                           "Add as fallback")
                          (t (nth 4 args))))))
         (should-error (emacsvox-aural-voice-editor-keep-experiment)))
       (should (= (length (plist-get (emacsvox-aural-voice-draft-working destination) :choices)) 3))
       (unless (eq change 'destination) (should (equal before (emacsvox-aural-voice-draft-working destination))))))))

(ert-deftest emacsvox-aural-voice-editor-adjustment-keep-selects-a-row-and-retains-its-physical-voice ()
  (emacsvox-test--with-layered-editor
   ;; The wire fixture has sparse shared fields; saving requires a full ACSS base.
   (emacsvox-aural-voice-editor--set 'richness 9)
   (let ((before (emacsvox-aural-voice-editor--working)))
     (emacsvox-aural-voice-editor-experiment '((:engine-id "new") (:voice-id "new")) (current-buffer) "Sample")
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (emacsvox-aural-voice-editor--set 'richness 2)
     (cl-letf (((symbol-function 'completing-read)
                (lambda (prompt collection &rest _)
                  (pcase prompt
                    ("Destination palette: " "reading-owned")
                    ("Use for named voice: " "bolden")
                    ("Keep from experiment: " "Adjustments only — selected choice")
                    ("Destination fallback: " (car (nth 2 collection)))
                    ("Destination has a draft: " "Add chosen changes to this draft")
                    (_ (error "Unexpected keep prompt: %s" prompt))))))
       (emacsvox-aural-voice-editor-keep-experiment))
     (let ((after (emacsvox-aural-voice-editor--working)))
       (should (equal (plist-get before :selectors) (plist-get after :selectors)))
       (should (equal (plist-get before :definition) (plist-get after :definition)))
       (should (= (plist-get (plist-get (nth 2 (plist-get after :choices)) :adjustments) :richness) 2)))
     (emacsvox-aural-voice-editor-save)
     (ert-info ((format "Save result: %S" (emacsvox-aural-voice-save-result
                                           (emacsvox-aural-voice-draft-proposal (emacsvox-aural-voice-editor--draft)))))
       (should (= (length callbacks) 1)))
     (funcall (car callbacks) '(:status applied))
     (should-not (emacsvox-aural-voice-drafts--dirty-fields (emacsvox-aural-voice-editor--draft)))
     (let* ((resolved (emacsvox-aural-voice-runtime--resolve 'bolden 'reading-owned))
            (patch (plist-get (nth 2 (plist-get resolved :choices)) :adjustments)))
       (should (= (plist-get patch :richness) 2))
       (should (plist-member patch :echo))
       (should-not (plist-get patch :echo))))))

(ert-deftest emacsvox-aural-voice-editor-physical-keep-requires-tuning-replacement-choice ()
  (dolist (replacement '(keep reset))
    (emacsvox-test--with-layered-editor
     (let ((before (emacsvox-aural-voice-editor--working)))
       (emacsvox-aural-voice-editor-experiment '((:engine-id "new") (:voice-id "new")) (current-buffer) "Sample")
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (prompt collection &rest _)
                    (cond ((equal prompt "Destination palette: ") "reading-owned")
                          ((equal prompt "Use for named voice: ") "bolden")
                          ((equal prompt "Keep from experiment: ") "Physical voice only")
                          ((equal prompt "Place physical voice: ") "Replace selected choice")
                          ((equal prompt "Destination fallback: ") (car (nth 1 collection)))
                          ((string-prefix-p "New physical voice" prompt)
                           (if (eq replacement 'keep) "Keep this row's custom settings" "Use shared settings"))
                          (t (error "Unexpected prompt: %s" prompt))))))
         (emacsvox-aural-voice-editor-keep-experiment))
       (let* ((after (emacsvox-aural-voice-editor--working)) (row (nth 1 (plist-get after :choices))))
         (should (equal (plist-get row :id) "alternate"))
         (should (equal (plist-get row :adjustments)
                        (when (eq replacement 'keep) (plist-get (nth 1 (plist-get before :choices)) :adjustments))))
         (should (equal (plist-get after :definition) (plist-get before :definition))))))))

(ert-deftest emacsvox-aural-voice-editor-experiment-can-resume-draft-without-merging ()
  (emacsvox-test--with-layered-editor
   (emacsvox-aural-voice-editor--set 'richness 7)
   (let ((destination emacsvox-aural-voice-editor--context)
         (before (emacsvox-aural-voice-editor--working)))
     (emacsvox-aural-voice-editor-experiment '((:engine-id "new") (:voice-id "new")) (current-buffer) "Sample")
     (cl-letf (((symbol-function 'completing-read)
                (lambda (prompt _collection &rest args)
                  (pcase prompt
                    ("Destination palette: " "reading-owned")
                    ("Use for named voice: " "bolden")
                    ("Place physical voice: " "Add as fallback")
                    ("Destination has a draft: " "Resume draft without adding")
                    (_ (nth 4 args))))))
       (should-error (emacsvox-aural-voice-editor-keep-experiment)))
     (should (eq destination emacsvox-aural-voice-editor--context))
     (should (equal before (emacsvox-aural-voice-editor--working))))))

(provide 'emacsvox-aural-voice-editor-tests)
;;; emacsvox-aural-voice-editor-tests.el ends here
