;;; emacsvox-emoji-integration-tests.el --- Emoji speech boundaries -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'emacsvox-emoji-tests)
(require 'emacsvox-aural-planner)
(require 'tts-speak)
(require 'emacsvox-aural-voice-editor)
(require 'emacsvox-aural-feedback-details)

(ert-deftest emacsvox-emoji-menu-path-retains-style-through-runtime-and-preview ()
  "The arrow-containing styled span reaches runtime and previews as named text."
  (let* ((emacsvox-emoji-naming-enabled t)
         (path (propertize "Aural Home → Sounds and output → Output volumes" 'face 'bold))
         (text (concat "Implemented under " path ":"))
         (expected "Implemented under Aural Home right arrow Sounds and output right arrow Output volumes:")
         (prepared (emacsvox-aural--prepare-emoji-text (emacsvox-aural-prepare-text text))))
    (should (equal prepared expected))
    (should (eq (get-text-property (string-match "right arrow" prepared) 'face prepared) 'bold))
    (let ((entries (tts--emoji-preview-entries
                    (list (list :text text :selector '(:voice-id "test"))))))
      (should (equal (plist-get (car entries) :text) expected)))
    (should (string-match-p "→" text))))

(ert-deftest emacsvox-emoji-decorated-text-matches-runtime-and-preview ()
  "Repeated emoji and arrow families keep style through both speech paths."
  (dolist (entry '(("🤔Dinner? 🍕🍕🍕" . "thinking face Dinner? pizza pizza pizza")
                   ("← ↑ → ↓ ⇒ ⟶"
                    . "left arrow up arrow right arrow down arrow rightwards double arrow long rightwards arrow")))
    (let* ((text (concat "Read " (propertize (car entry) 'face 'bold)))
           (expected (concat "Read " (cdr entry)))
           (prepared (emacsvox-aural--prepare-emoji-text
                      (emacsvox-aural-prepare-text text)))
           (preview (car (tts--emoji-preview-entries (list (list :text text))))))
      (should (equal prepared expected))
      (should (eq (get-text-property 5 'face prepared) 'bold))
      (should (equal (plist-get preview :text) expected))
      (should-not (plist-get (plist-get preview :emoji-naming) :diagnostics)))))

(ert-deftest emacsvox-emoji-planned-policy-survives-source-changes ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (text (emacsvox-aural-prepare-text "Forecast 🔮"))
         (original (get-text-property 0 emacsvox-aural-concrete-plan-property text))
         (emacsvox-emoji-naming-enabled nil)
         (output (emacsvox-aural--prepare-emoji-text text))
         (plan (get-text-property 0 emacsvox-aural-concrete-plan-property output)))
    (should (equal output "Forecast crystal ball"))
    (should-not (eq original plan))
    (should-not (plist-get (emacsvox-aural-concrete-plan-context original) :emoji-naming))
    (should (plist-get (emacsvox-aural-concrete-plan-context plan) :emoji-naming))
    (should (equal text "Forecast 🔮"))))

(ert-deftest emacsvox-emoji-object-limit-spans-style-runs ()
  (let ((emacsvox-emoji-naming-enabled t)
        (emacsvox-emoji-maximum-count 2))
    (let* ((text (concat (propertize "🔮 " 'face 'bold) "🔮 🔮"))
           (prepared (emacsvox-aural-prepare-text text)))
      (should (equal (emacsvox-aural--prepare-emoji-text prepared) text)))
    (let* ((text (concat (propertize "🔮 🔮 " emacsvox-aural-object-property 'one)
                         (propertize "🔮" emacsvox-aural-object-property 'two)))
           (prepared (emacsvox-aural-prepare-text text)))
      (should (equal (emacsvox-aural--prepare-emoji-text prepared)
                     "crystal ball crystal ball crystal ball")))))

(ert-deftest emacsvox-emoji-object-boundary-cannot-split-unknown-join ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (text (concat (propertize "🔮" emacsvox-aural-object-property 'one)
                       (propertize "‍🚀" emacsvox-aural-object-property 'two))))
    (should (equal (emacsvox-aural--prepare-emoji-text (emacsvox-aural-prepare-text text)) text))))

(ert-deftest emacsvox-emoji-original-count-survives-pronunciation-cleanup ()
  (let ((emacsvox-emoji-naming-enabled t)
        (emacsvox-emoji-maximum-count 2)
        (table (make-hash-table :test #'equal)))
    (puthash "✨" "sparkle" table)
    (with-temp-buffer
      (insert (emacsvox-aural-prepare-text "🔮 🔮 ✨"))
      (tts-apply-pronunciations table)
      (should (equal (emacsvox-aural--prepare-emoji-text (buffer-string)) "🔮 🔮 sparkle")))))

(ert-deftest emacsvox-emoji-preview-uses-attached-source-and-explicit-pronunciation ()
  (let ((source (generate-new-buffer " *emoji source*")))
    (unwind-protect
        (progn
          (with-current-buffer source
            (setq-local emacsvox-emoji-naming-enabled t)
            (setq-local emacsvox-pronounce-table (make-hash-table :test #'equal))
            (puthash "🔮" "prediction ✨" emacsvox-pronounce-table))
          (with-temp-buffer
            (setq-local emacsvox-emoji-naming-enabled nil)
            (setq-local emacsvox-aural-ui-interface-buffer t)
            (emacsvox-aural-inspection-attach-source source)
            (let* ((input '((:text "🔮" :selector (:voice-id "test"))))
                   (result (tts--emoji-preview-entries input)))
              (should (equal (plist-get (car result) :text) "prediction ✨"))
              (should (equal (plist-get (car (tts--emoji-preview-entries result)) :text) "prediction ✨"))
              (should (equal (plist-get (car input) :text) "🔮")))))
      (kill-buffer source))))

(ert-deftest emacsvox-emoji-preview-operation-freezes-text-before-callback ()
  (let ((emacsvox-emoji-naming-enabled t) submitted finish)
    (let ((tts-voice-preview-function
           (lambda (entries callback) (setq submitted entries finish callback))))
      (tts-preview-voices '((:text "🔮" :selector (:voice-id "test"))) #'ignore)
      (setq emacsvox-emoji-naming-enabled nil)
      (should (equal (plist-get (car submitted) :text) "crystal ball"))
      (funcall finish '(:status completed)))))

(ert-deftest emacsvox-emoji-retained-replay-and-proposal-keep-captured-expansion ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (emacsvox-emoji-custom-names '(("🔮" . "✨ prediction")))
         (output (emacsvox-aural--prepare-emoji-text (emacsvox-aural-prepare-text "🔮")))
         (plan (emacsvox-aural--freeze-presentation-plan
                (get-text-property 0 emacsvox-aural-concrete-plan-property output) output))
         (runs (list (list plan (substring-no-properties output) nil)))
         (emacsvox-emoji-custom-names nil)
         (proposal (emacsvox-aural-replan-runs runs)))
    (should (equal (cadar proposal) "✨ prediction"))
    (should (equal (emacsvox-aural-concrete-content-text (emacsvox-aural-concrete-plan-content plan))
                   "✨ prediction"))
    (should (plist-get (emacsvox-aural-concrete-plan-context (caar proposal)) :emoji-naming))))

(ert-deftest emacsvox-emoji-normal-and-notification-speech-match-preview ()
  (let ((emacsvox-emoji-naming-enabled t)
        (tts-stop-immediately nil) (tts-handle-unicode nil)
        (emacsvox-pronounce-table nil) (emacsvox-pronounce-personality nil)
        (tts-speaker-process 'main) (tts-notify-process 'notification)
        observed)
    (cl-letf (((symbol-function 'tts--protocol-sync) #'ignore)
              ((symbol-function 'tts--protocol-dispatch) #'ignore)
              ((symbol-function 'tts-audio-format)
               (lambda (start end)
                 (push (list tts-speaker-process (buffer-substring start end)) observed)))
              ((symbol-function 'tts-notify-process) (lambda () 'notification))
              ((symbol-function 'tts--speak) #'tts--speak-transaction))
      (tts-speak "Forecast 🔮")
      (tts-notify "Forecast 🔮" t))
    (dolist (lane '(main notification))
      (should (equal (mapconcat #'cadr (reverse (cl-remove-if-not
                                               (lambda (entry) (eq (car entry) lane)) observed)) "")
                     "Forecast crystal ball")))
    (should (equal (plist-get (car (tts--emoji-preview-entries '((:text "Forecast 🔮")))) :text)
                   "Forecast crystal ball"))))

(ert-deftest emacsvox-emoji-mail-seedling-reaches-speech-as-ascii-by-default ()
  (let ((tts-stop-immediately nil) (tts-handle-unicode nil)
        (emacsvox-pronounce-table nil) (emacsvox-pronounce-personality nil)
        (text "Would love to visit 🌱 (via example.org)")
        observed)
    ;; Exercise new-user defaults without enabling or restricting naming.
    (cl-letf (((symbol-function 'tts--protocol-sync) #'ignore)
              ((symbol-function 'tts--protocol-dispatch) #'ignore)
              ((symbol-function 'tts-audio-format)
               (lambda (start end) (push (buffer-substring start end) observed)))
              ((symbol-function 'tts--speak) #'tts--speak-transaction))
      (tts-speak text))
    (should (equal (mapconcat #'identity (nreverse observed) "")
                   "Would love to visit seedling (via example.org)"))
    (should (equal (plist-get (car (tts--emoji-preview-entries (list (list :text text)))) :text)
                   "Would love to visit seedling (via example.org)"))))

(ert-deftest emacsvox-emoji-source-can-disable-default-naming ()
  (with-temp-buffer
    (setq-local emacsvox-emoji-naming-enabled nil)
    (should (equal (emacsvox-aural--prepare-emoji-text
                    (emacsvox-aural-prepare-text "Forecast 🌱"))
                   "Forecast 🌱"))
    (should (equal (plist-get (car (tts--emoji-preview-entries '((:text "Forecast 🌱")))) :text)
                   "Forecast 🌱"))))

(ert-deftest emacsvox-emoji-fresh-simulation-and-explanation-use-captured-policy ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (plan (emacsvox-aural--make-concrete-plan
                :context (emacsvox-aural-capture-context)
                :content (emacsvox-aural--make-concrete-content :text "Forecast 🔮" :speak t)))
         (emacsvox-emoji-naming-enabled nil)
         (prepared (emacsvox-aural-preview--prepare-plan plan)))
    (should (equal (emacsvox-aural-concrete-content-text (emacsvox-aural-concrete-plan-content prepared))
                   "Forecast crystal ball"))
    (should (equal (emacsvox-aural-concrete-content-text (emacsvox-aural-concrete-plan-content plan))
                   "Forecast 🔮"))
    (with-temp-buffer
      (cl-letf (((symbol-function 'emacsvox-aural-feedback-details--plan) (lambda (_) prepared))
                ((symbol-function 'emacsvox-aural-feedback-details--insert-voice-links) #'ignore))
        (emacsvox-aural-feedback-details--insert-explanation '(0)))
      (should (string-match-p "Speech text: 🔮 spoken as crystal ball" (buffer-string))))))

(ert-deftest emacsvox-emoji-voice-editor-forwards-clean-wire-and-retains-evidence ()
  (let ((emacsvox-emoji-naming-enabled t)
        (tts-voice-preview-function #'ignore)
        wire received)
    (cl-letf (((symbol-function 'emacsvox-aural-voice-editing--legacy-preview) #'identity)
              ((symbol-function 'tts-preview-voices)
               (lambda (entries callback)
                 (should tts--emoji-preview-prepared)
                 (setq wire entries)
                 (funcall callback '(:status queued :results ((:status queued)))))))
      (emacsvox-aural-voice-editor--submit-preview
       '((:text "🔮" :role sample)) (lambda (result) (setq received result)) (lambda () t)))
    (should (equal (plist-get (car wire) :text) "crystal ball"))
    (should (plist-get (plist-get (car (plist-get received :results)) :request-snapshot) :emoji-naming))
    (let ((entry (car (tts--emoji-preview-wire-entries wire))))
      (should-not (plist-member entry :emoji-naming))
      (should-not (plist-member entry :emoji-prepared)))))

(ert-deftest emacsvox-emoji-context-preview-overrides-current-source-policy ()
  (let ((emacsvox-emoji-naming-enabled nil))
    (should (equal (plist-get (car (tts--emoji-preview-entries
                                   (list (list :text "🔮" :emoji-policy (emacsvox-emoji-test--policy))))) :text)
                   "crystal ball"))))

(ert-deftest emacsvox-emoji-expansion-preserves-transport-cue-byte-offsets ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (text (emacsvox-aural-prepare-text "é ⚠️ z"))
         (property emacsvox-aural-concrete-positioned-actions-property))
    (put-text-property 0 1 property '((:index before)) text)
    (put-text-property 2 3 property '((:index at-start)) text)
    (put-text-property 5 6 property '((:index after)) text)
    (with-temp-buffer
      (insert (emacsvox-aural--prepare-emoji-text text))
      (let ((actions (tts--concrete-positioned-actions (point-min) (point-max))))
        (should (equal (buffer-string) "é warning z"))
        (should (equal (mapcar (lambda (a) (plist-get a :utf8-offset)) actions) '(0 3 11)))
        (should (equal (mapcar (lambda (a) (plist-get (car (plist-get a :actions)) :index)) actions)
                       '(before at-start after)))))))

(ert-deftest emacsvox-emoji-graphical-explanation-is-visible ()
  (skip-unless (display-graphic-p))
  (let* ((emacsvox-emoji-naming-enabled t)
         (text (emacsvox-aural--prepare-emoji-text (emacsvox-aural-prepare-text "Forecast 🔮")))
         (plan (get-text-property 0 emacsvox-aural-concrete-plan-property text)))
    (save-window-excursion
      (with-temp-buffer
        (switch-to-buffer (current-buffer))
        (emacsvox-aural-feedback-details-mode)
        (let ((inhibit-read-only t))
          (cl-letf (((symbol-function 'emacsvox-aural-feedback-details--plan) (lambda (_) plan))
                    ((symbol-function 'emacsvox-aural-feedback-details--insert-voice-links) #'ignore))
            (emacsvox-aural-feedback-details--insert-explanation '(0))))
        (goto-char (point-min))
        (search-forward "Speech text: 🔮 spoken as crystal ball.")
        (beginning-of-line)
        (redisplay t)
        (should (pos-visible-in-window-p (point) (selected-window)))
        (should (eq (window-buffer (selected-window)) (current-buffer)))))))

(ert-deftest emacsvox-emoji-retained-voice-link-does-not-name-custom-output-again ()
  (let* ((emacsvox-emoji-naming-enabled t)
         (emacsvox-emoji-custom-names '(("🔮" . "✨ prediction")))
         (output (emacsvox-aural--prepare-emoji-text (emacsvox-aural-prepare-text "🔮")))
         (plan (emacsvox-aural--freeze-presentation-plan
                (get-text-property 0 emacsvox-aural-concrete-plan-property output) output))
         (content (emacsvox-aural-concrete-plan-content plan))
         sample)
    (setf (emacsvox-aural-concrete-content-voice-request content) 'bolden)
    (with-temp-buffer
      (cl-letf (((symbol-function 'emacsvox-aural-feedback-details--plan) (lambda (_) plan))
                ((symbol-function 'emacsvox-aural-voice-runtime--owned) (lambda (&rest _) '(:name bolden)))
                ((symbol-function 'emacsvox-aural-voice-editor-open)
                 (lambda (_palette _voice _source text) (setq sample text))))
        (emacsvox-aural-feedback-details--insert-voice-links '(0))
        (goto-char (point-min))
        (button-activate (button-at (point-min)))))
    (let* ((emacsvox-pronounce-table (make-hash-table :test #'equal))
           (_ (puthash "prediction" "changed" emacsvox-pronounce-table))
           (entry (car (tts--emoji-preview-entries
                        (list (list :text (concat "Pitch 7. " sample)))))))
      (should (equal (plist-get entry :text) "Pitch 7. ✨ prediction"))
      (should (equal (plist-get entry :emoji-naming)
                     (plist-get (emacsvox-aural-concrete-plan-context plan) :emoji-naming))))))

(provide 'emacsvox-emoji-integration-tests)
