;;; emacsvox-aural-feedback-details-tests.el --- Recorded field review tests -*- lexical-binding: t; -*-
;;; Commentary:
;; Exercise real Notmuch formatting and native planning with device-free playback.
;;; Code:
(require 'emacsvox-aural-change-feedback-tests)
(require 'package)
(package-initialize)
(require 'notmuch)
(require 'emacsvox-notmuch)

(defun emacsvox-test--feedback-record ()
  "Capture a real Notmuch search presentation, with a multivoice count."
  (let ((formatter (symbol-function 'emacsvox-notmuch--format-search-field))
        (emacsvox-notmuch-search-result-fields '(authors subject date count tags))
        (emacsvox-use-icons t)
        prepared)
    (cl-letf (((symbol-function 'emacsvox-notmuch--format-search-field)
               (lambda (field result)
                 (let ((text (funcall formatter field result)))
                   (when (eq field 'count)
                     (put-text-property 0 1 'personality 'voice-bolden text)
                     (put-text-property (1- (length text)) (length text) 'personality 'voice-lighten text))
                   text)))
              ((symbol-function 'tts-speak) (lambda (text) (setq prepared text))))
      (emacsvox-notmuch--submit-search-result
       '(:authors "Alice, Bob" :subject "Meeting arrangements" :date_relative "Yesterday"
                  :matched 2 :total 5 :tags ("inbox" "unread"))
       (append (emacsvox-notmuch-thread-facts nil nil) '(:states (unread)))
       'navigation 'select-object))
    (let ((position 0) plans)
      (while (< position (length prepared))
        (let* ((plan (emacsvox-aural-concrete-plan-at position prepared))
               (end (next-single-property-change position emacsvox-aural-concrete-plan-property
                                                 prepared (length prepared))))
          (push (emacsvox-aural--freeze-presentation-plan
                 plan (substring prepared position end)) plans)
          (setq position end)))
      (emacsvox-aural--make-history-record (nreverse plans) nil 421))))

(defmacro emacsvox-test--with-feedback-report (&rest body)
  "Run BODY with a native Notmuch RECORD and selected REPORT buffer."
  (declare (indent 0) (debug t))
  `(emacsvox-test--with-home-context
    (with-current-buffer source
      (setq major-mode 'notmuch-search-mode)
      (setq-local voice-lock-mode t))
    (let* ((record (with-current-buffer source (emacsvox-test--feedback-record)))
           (emacsvox-aural-presentation-history (list record))
           (report (progn (emacsvox-aural-list-recent-feedback source)
                          (emacsvox-aural-recent-feedback-explain))))
      ,@body)))

(defun emacsvox-test--feedback-field (field)
  "Move to FIELD's heading in the selected report, returning its run indices."
  (goto-char (point-min))
  (re-search-forward (concat "^" (regexp-quote field) " ("))
  (beginning-of-line)
  (emacsvox-aural-feedback-details--target))

(defun emacsvox-test--feedback-spans ()
  "Open the individual voice spans beneath the current expanded field."
  (search-forward "Individual voice spans")
  (beginning-of-line)
  (call-interactively (key-binding (kbd "RET"))))

(ert-deftest emacsvox-aural-feedback-details-enter-selects-quiet-pinned-report ()
  "Enter selects a readable report; q restores the exact history cell."
  (emacsvox-test--with-feedback-report
   (should (eq (current-buffer) report))
   (should (derived-mode-p 'emacsvox-aural-feedback-details-mode))
   (should buffer-read-only)
   (should (string-match-p "^Captured feedback\\.$" (buffer-string)))
   (should-not (string-match-p "^Record [0-9]" (buffer-string)))
   (emacsvox-aural-ui-help-quit)
   (emacsvox-aural-ui-goto-tabulated-column 3)
   (let ((origin (current-buffer)) (position (point)) spoken)
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (call-interactively (key-binding (kbd "RET"))))
     (should (eq (current-buffer) report))
     (should (< (length spoken) 150))
     (should (string-prefix-p "Feedback details" spoken))
     (let ((before (buffer-string)))
       (setq emacsvox-aural-presentation-history nil)
       (with-current-buffer (get-buffer-create "*Help*") (let ((inhibit-read-only t)) (erase-buffer) (insert "Other help")))
       (should (equal before (buffer-string))))
     (call-interactively (key-binding (kbd "q")))
     (should (eq (current-buffer) origin))
     (should (= (point) position)))))

(ert-deftest emacsvox-aural-feedback-details-groups-voices-and-replays-original ()
  "Fields retain native voice spans and original ordered replay remains frozen."
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Message count"))
          (runs (emacsvox-aural-presentation-record-runs record)) played spoken)
     (should (> (length indices) 1))
     (should (> (length (delete-dups
                         (mapcar (lambda (i)
                                   (emacsvox-aural-concrete-content-voice-style
                                    (emacsvox-aural-concrete-plan-content (car (nth i runs)))))
                                 indices))) 1))
     (emacsvox-aural-feedback-details-toggle)
     (should (search-forward "Voice:" nil t))
     (should (string-match-p "from the text's voice annotation" (buffer-string)))
     (emacsvox-test--feedback-field "Message count")
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (emacsvox-aural-feedback-details-next-line))
     (should (string-match-p "2 of 5" spoken))
     (let* ((plan (emacsvox-aural-concrete-plan-at 0 spoken))
            (original (car (nth (car indices) runs))))
       (should (equal (emacsvox-aural-concrete-content-voice-style
                       (emacsvox-aural-concrete-plan-content plan))
                      (emacsvox-aural-concrete-content-voice-style
                       (emacsvox-aural-concrete-plan-content original)))))
     (cl-letf (((symbol-function 'emacsvox-aural-preview-play-runs)
                (lambda (value &rest _) (setq played value)
                  (should emacsvox-aural--history-recording-inhibited))))
       (emacsvox-aural-feedback-details-play-field)
       (should (equal played (mapcar (lambda (i) (nth i runs)) indices)))
       (emacsvox-aural-feedback-details-play)
       (should (equal played runs)))
     (should (equal emacsvox-aural-presentation-history (list record))))))

(ert-deftest emacsvox-aural-feedback-details-blank-lines-use-normal-tones ()
  "Arrows and Space submit normal blank tones without recording report navigation."
  (require 'emacsvox-speak)
  (emacsvox-test--with-feedback-report
   (let ((history emacsvox-aural-presentation-history)
         (tts-quiet nil)
         (tts-speaker-process 'speaker)
         (emacsvox-show-point nil)
         (emacsvox-audio-indentation nil)
         (emacsvox-aural-history-record-interface-presentations nil))
     (goto-char (point-min))
     (re-search-forward "^$")
     (let ((blank (point)))
       (dolist (case '(("" 130.8) (" \t" 261.6)))
         (goto-char blank)
         (let ((inhibit-read-only t))
           (delete-region (line-beginning-position) (line-end-position))
           (insert (car case)))
         (dolist (key '("<down>" "<up>" "SPC"))
           (goto-char blank)
           (pcase key ("<down>" (forward-line -1)) ("<up>" (forward-line 1)))
           (let (events)
             (cl-letf (((symbol-function 'process-live-p) (lambda (process) (eq process 'speaker)))
                       ((symbol-function 'tts-stop) #'ignore)
                       ((symbol-function 'tts-speak)
                        (lambda (&rest _) (ert-fail "Blank report line entered text speech")))
                       ((symbol-function 'emacsvox-aural--protocol-presentation-tone)
                        (lambda (pitch duration mode) (push (list 'tone pitch duration mode) events)))
                       ((symbol-function 'tts--protocol-dispatch)
                        (lambda () (push 'dispatch events))))
               (call-interactively (key-binding (kbd key))))
             (should (equal (nreverse events)
                            (list (list 'tone (cadr case) 150 'overlay) 'dispatch)))
             (should (= (line-beginning-position) blank))
             (should (equal emacsvox-aural-presentation-history history)))))))))

(ert-deftest emacsvox-aural-feedback-details-links-distinct-recorded-voices ()
  "A multivoice field links each named voice without remapping the field."
  (emacsvox-test--with-feedback-report
   (emacsvox-test--feedback-field "Message count")
   (emacsvox-aural-feedback-details-toggle)
   (let ((before (emacsvox-aural--history-value record)) opened)
     (dolist (name '(bolden lighten))
       (goto-char (point-min))
       (search-forward (format "Edit named voice %s" name))
       (backward-char)
       (cl-letf (((symbol-function 'emacsvox-aural-voice-editor-open)
                  (lambda (&rest args) (setq opened args))))
         (call-interactively (key-binding (kbd "RET"))))
       (should (eq (nth 1 opened) name))
       (should (eq (nth 2 opened) report)))
     (should-not emacsvox-aural-feedback-details--drafts)
     (should (equal before (emacsvox-aural--history-value record))))))

(ert-deftest emacsvox-aural-feedback-details-offers-captured-mail-action-conditions ()
  "A boundary example exposes its action and event without changing draft scope."
  (emacsvox-test--with-home-context
   (with-current-buffer source
     (setq major-mode 'notmuch-search-mode))
   (let* ((record
           (with-current-buffer source
             (let (prepared)
               (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq prepared text))))
                 (emacsvox-notmuch--search-boundary-feedback 'forward))
               (emacsvox-aural--make-history-record
                (list (emacsvox-aural--freeze-presentation-plan
                       (emacsvox-aural-concrete-plan-at 0 prepared) prepared)) nil 422))))
          (report (emacsvox-aural-feedback-details record)))
     (pop-to-buffer report)
     (goto-char (text-property-not-all (point-min) (point-max) 'emacsvox-aural-feedback-target nil))
     (emacsvox-aural-feedback-details-change)
     (let ((initial (copy-tree emacsvox-aural-change-feedback-selector)))
       (emacsvox-aural-change-feedback-match)
       (should (equal emacsvox-aural-change-feedback-selector initial)))
     (dolist (criterion '((:mail-action-kind select) (:mail-view-kind search)
                          (:events (operation-failed))))
       (should (emacsvox-aural-ui-goto-row (list 'criterion criterion)))
       (should (equal (aref (tabulated-list-get-entry) 1) "Excluded"))
       (emacsvox-aural-change-feedback-open-row)
       (should (equal (aref (tabulated-list-get-entry) 1) "Included")))
     (emacsvox-test--guided-choose "Change the content voice" "lighten")
     (let ((rule (emacsvox-aural-compile-rule (emacsvox-aural-change-feedback--rule) 'user))
           (context '(:module notmuch :mode notmuch-search-mode :occasion navigation)))
       (should (emacsvox-aural-rule-matches-p
                rule (emacsvox-aural-normalize-input
                      (emacsvox-notmuch-view-facts 'search 'select 'operation-failed) context)))
       (dolist (facts (list (emacsvox-notmuch-view-facts 'search 'scroll 'operation-failed)
                            (emacsvox-notmuch-view-facts 'thread 'select 'operation-failed)
                            (emacsvox-notmuch-view-facts 'search 'select 'focus-entered)))
         (should-not (emacsvox-aural-rule-matches-p
                      rule (emacsvox-aural-normalize-input facts context)))))
     (emacsvox-aural-change-feedback-match)
     (should (emacsvox-aural-ui-goto-row '(criterion (:events (operation-failed)))))
     (emacsvox-aural-change-feedback-open-row)
     (emacsvox-aural-change-feedback-match)
     (emacsvox-aural-change-feedback-match)
     (should (emacsvox-aural-ui-goto-row '(criterion (:events (operation-failed)))))
     (should (equal (aref (tabulated-list-get-entry) 1) "Excluded"))
     (should-not (plist-get emacsvox-aural-change-feedback-selector :events))
     (should (eq (plist-get emacsvox-aural-change-feedback-selector :mail-action-kind) 'select)))))

(ert-deftest emacsvox-aural-feedback-details-preview-subject-and-after-count ()
  "Two field drafts preview together; the count cue occurs once at its boundary."
  (emacsvox-test--with-feedback-report
   (let* ((original (emacsvox-aural--history-value record))
          (baseline (emacsvox-aural-replan-runs (emacsvox-aural-presentation-record-runs record)))
          (subject-indices (emacsvox-test--feedback-field "Subject"))
          subject-editor count-indices proposed)
     (emacsvox-aural-feedback-details-change)
     (setq subject-editor (current-buffer))
     (should (equal (plist-get emacsvox-aural-change-feedback-selector :mode) 'notmuch-search-mode))
     (emacsvox-test--guided-choose "Change the content voice" "lighten")
     (pop-to-buffer report)
     (setq count-indices (emacsvox-test--feedback-field "Message count"))
     (emacsvox-aural-feedback-details-change)
     (emacsvox-test--guided-choose "Add a sound" "After content" "close-object")
     (should (eq (plist-get (car (plist-get (plist-get emacsvox-aural-change-feedback-render :after) :append)) :anchor)
                 'transition))
     (with-current-buffer report
       (setq proposed (emacsvox-aural-feedback-details--proposal-runs)))
     (should (= (length baseline) (length proposed)))
     (cl-loop for (plan . _) in proposed for index from 0
              for original-run in baseline
              do
              (let ((voice (emacsvox-aural-concrete-content-voice-request
                            (emacsvox-aural-concrete-plan-content plan))))
                (if (memq index subject-indices)
                    (should (eq voice 'lighten))
                  (should (equal voice (emacsvox-aural-concrete-content-voice-request
                                        (emacsvox-aural-concrete-plan-content (car original-run))))))))
     (let ((cue-positions
            (cl-loop for (plan . _) in proposed for index from 0
                     append (cl-loop for action in (emacsvox-aural-concrete-plan-after plan)
                                     when (eq (emacsvox-aural-concrete-action-cue action) 'close-object)
                                     collect index))))
       (should (equal cue-positions (last count-indices))))
     ;; Source adapters are re-resolved in place, not lost or duplicated.
     (should (equal (emacsvox-aural-concrete-plan-before (caar proposed))
                    (emacsvox-aural-concrete-plan-before (caar baseline))))
     (should (equal record original))
     (should-not emacsvox-aural-user-rules)
     (should-not emacsvox-aural-session-rules)
     (should-not (buffer-local-value 'emacsvox-aural-buffer-rules source))
     ;; Applying the count rule must have the same placement on a new native
     ;; presentation, not merely in our replay preview.
     (setq emacsvox-aural-change-feedback-scope 'buffer)
     (emacsvox-aural-change-feedback-apply)
     (should emacsvox-aural-change-feedback-applied)
     (let* ((next (with-current-buffer source (emacsvox-test--feedback-record)))
            (plans (emacsvox-aural-presentation-record-effective-plans next))
            (cues (cl-loop for plan in plans
                           append (cl-remove-if-not
                                   (lambda (action) (eq (emacsvox-aural-concrete-action-cue action) 'close-object))
                                   (emacsvox-aural-concrete-plan-after plan)))))
       (should (= (length cues) 1))
       (save-window-excursion
         (emacsvox-aural-feedback-details next)
         (emacsvox-test--feedback-field "Message count")
         (emacsvox-aural-feedback-details-change)
         (should (member "Replace a sound" (emacsvox-aural-change-feedback--operations)))
         (should (= (length (emacsvox-aural-change-feedback--components 'cue)) 1))))
     (pop-to-buffer report)
     (emacsvox-test--feedback-field "Subject")
     (emacsvox-aural-feedback-details-change)
     (should (eq (current-buffer) subject-editor))
     (should emacsvox-aural-change-feedback-render))))

(ert-deftest emacsvox-aural-feedback-details-span-targets-distinct-voice-only ()
  "A uniquely annotated span can change without broadening to its shared face."
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Message count"))
          (last-index (car (last indices))))
     (emacsvox-aural-feedback-details-toggle)
     (emacsvox-test--feedback-spans)
     (goto-char (point-min))
     (re-search-forward "^  Span 1\\.")
     (beginning-of-line)
     (should-error (emacsvox-aural-feedback-details-change) :type 'user-error)
     (re-search-forward (format "^  Span %d\\." (length indices)))
     (beginning-of-line)
     (emacsvox-aural-feedback-details-change)
     (should (eq (plist-get emacsvox-aural-change-feedback-selector :legacy-personality) 'voice-lighten))
     (should-not (plist-member emacsvox-aural-change-feedback-selector :legacy-face))
     (emacsvox-test--guided-choose "Change the content voice" "bolden")
     (with-current-buffer report
       (let ((proposal (emacsvox-aural-feedback-details--proposal-runs)))
         (should (eq (emacsvox-aural-concrete-content-voice-request
                      (emacsvox-aural-concrete-plan-content (car (nth last-index proposal)))) 'bolden))
         (should (eq (emacsvox-aural-concrete-content-voice-request
                      (emacsvox-aural-concrete-plan-content
                       (emacsvox-aural-feedback-details--plan last-index))) 'lighten)))))))

(ert-deftest emacsvox-aural-feedback-details-keeps-reports-and-drafts-separate ()
  "Opening another record cannot retarget an earlier field draft."
  (emacsvox-test--with-feedback-report
   (emacsvox-test--feedback-field "Subject")
   (emacsvox-aural-feedback-details-change)
   (let ((editor (current-buffer))
         (other (with-current-buffer source (emacsvox-test--feedback-record))))
     (emacsvox-aural-feedback-details other)
     (should-not (eq report (current-buffer)))
     (with-current-buffer editor
       (should (eq emacsvox-aural-change-feedback--review-buffer report))
       (should (eq emacsvox-aural-change-feedback-record record))))))

(ert-deftest emacsvox-aural-feedback-details-truncated-and-old-record-guards ()
  "Incomplete history cannot masquerade as comparable original/proposed output."
  (emacsvox-test--with-feedback-report
   (setf (emacsvox-aural-presentation-record-payload-truncated-p record) t)
   (emacsvox-aural-feedback-details--render)
   (should (string-match-p "Truncated preview; complete playback unavailable" (buffer-string)))
   (should-error (emacsvox-aural-feedback-details-play) :type 'user-error)
   (emacsvox-test--feedback-field "Subject")
   (should-error (emacsvox-aural-feedback-details-change) :type 'user-error)
   (setf (emacsvox-aural-presentation-record-payload-truncated-p record) nil)
   (dolist (plan (emacsvox-aural-presentation-record-effective-plans record))
     (setf (emacsvox-aural-concrete-plan-context plan)
           (cl-loop for (key value) on (emacsvox-aural-concrete-plan-context plan) by #'cddr
                    unless (eq key :aural-source-compatibility-actions) append (list key value))))
   (should-error (emacsvox-aural-replan-runs (emacsvox-aural-presentation-record-runs record)) :type 'user-error)
   (let (played)
     (cl-letf (((symbol-function 'emacsvox-aural-preview-play-runs)
                (lambda (runs &rest _) (setq played runs))))
       (emacsvox-aural-feedback-details-play))
     (should played))))

(ert-deftest emacsvox-aural-feedback-details-home-explain-keeps-record-and-return-cell ()
  "Home explains its captured item quietly and q restores the exact Home cell."
  (emacsvox-test--with-feedback-report
   (emacsvox-aural source)
   (emacsvox-aural-home--goto 'explain)
   (emacsvox-aural-ui-goto-tabulated-column 2)
   (let ((home (current-buffer)) (position (point)) spoken)
     (with-current-buffer source (goto-char (point-max)))
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (let ((noninteractive nil)) (call-interactively #'emacsvox-aural-home-explain)))
     (should (eq (window-buffer (selected-window)) report))
     (with-current-buffer report
       (should (eq record emacsvox-aural-feedback-details--record))
       (should-not emacsvox-aural-feedback-details--simulation)
       (should (string-match-p "Play original whole presentation" (buffer-string)))
       (should (< (length spoken) 150))
       (call-interactively (key-binding (kbd "q"))))
     (should (eq (window-buffer (selected-window)) home))
     (with-current-buffer home (should (= position (point)))))))

(ert-deftest emacsvox-aural-feedback-details-simulation-is-labelled-and-editable ()
  "An unrecorded shell item has a playable simulation, separate from history."
  (require 'shell)
  (require 'emacsvox-comint)
  (emacsvox-test--with-home-context
   (switch-to-buffer source)
   (erase-buffer)
   (shell-mode)
   (insert (propertize "user$ " 'font-lock-face 'comint-highlight-prompt))
   (goto-char 1)
   (let ((position (point)) report spoken played)
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text)))
               ((symbol-function 'completing-read) (lambda (&rest _) (error "No question expected"))))
       (let ((noninteractive nil)) (call-interactively #'emacsvox-aural-explain-presentation)))
     (setq report (window-buffer (selected-window)))
     (with-current-buffer report
       (should (derived-mode-p 'emacsvox-aural-feedback-details-mode))
       (should emacsvox-aural-feedback-details--simulation)
       (should (string-match-p "^Simulated feedback\\.$" (buffer-string)))
       (should (string-match-p "not recorded speech" spoken))
       (should (< (length spoken) 150))
       (should (string-match-p "Play simulation" (buffer-string)))
       (should (string-match-p "Open the raw snapshot in a separate buffer" (buffer-string)))
       (should-not (string-match-p "Play original\\|Submitted:\\|Exact retained" (buffer-string)))
       (cl-letf (((symbol-function 'emacsvox-aural-preview-play-runs)
                  (lambda (runs &rest _) (setq played runs))))
         (call-interactively (key-binding (kbd "P"))))
       (should (equal (cadar played) "user$ "))
       (goto-char (text-property-not-all (point-min) (point-max) 'emacsvox-aural-feedback-target nil))
       (emacsvox-aural-feedback-details-change))
     (with-current-buffer (window-buffer (selected-window))
       (should emacsvox-aural-change-feedback--simulation)
       (should (string-match-p "Play simulated field" (buffer-string)))
       (should-not (string-match-p "Play original\\|Recent Feedback" (buffer-string)))
       (save-window-excursion
         (cl-letf (((symbol-function 'emacsvox-aural-ui-speak)
                    (lambda (text) (setq spoken text))))
           (emacsvox-aural-change-feedback-help))
         (should (string-match-p "O plays the simulated baseline" spoken))
         (should-not (string-match-p "original" spoken)))
       (should (eq (plist-get emacsvox-aural-change-feedback-selector :legacy-face) 'comint-highlight-prompt))
       (emacsvox-test--guided-choose "Change the content voice" "bolden")
       (cl-letf (((symbol-function 'emacsvox-aural-preview-play-runs)
                  (lambda (runs &rest _) (setq played runs))))
         (emacsvox-aural-change-feedback-preview-whole))
       (should (equal (cadar played) "user$ "))
       (should (eq (emacsvox-aural-concrete-content-voice-request
                    (emacsvox-aural-concrete-plan-content (caar played))) 'bolden)))
     (should-not emacsvox-aural-presentation-history)
     (should-not emacsvox-aural-user-rules)
     (with-current-buffer report (emacsvox-aural-ui-help-quit))
     (should (eq (window-buffer (selected-window)) source))
     (with-current-buffer source (should (= position (point)))))))

(ert-deftest emacsvox-aural-feedback-details-prefix-forces-simulation ()
  "An explicit occasion uses a simulation even when a current record exists."
  (emacsvox-test--with-feedback-report
   (switch-to-buffer source)
   (let ((current-prefix-arg '(4)) asked)
     (cl-letf (((symbol-function 'completing-read)
                (lambda (prompt &rest _) (setq asked prompt) "navigation")))
       (let ((noninteractive nil)) (call-interactively #'emacsvox-aural-explain-presentation)))
     (should (string-match-p "occasion" asked))
     (with-current-buffer (window-buffer (selected-window))
       (should emacsvox-aural-feedback-details--simulation)
       (should-not (eq record emacsvox-aural-feedback-details--record))))))

(ert-deftest emacsvox-aural-feedback-details-folds-content-and-single-span-controls ()
  "Collapsed fields hide their content; one span never creates a duplicate section."
  (emacsvox-test--with-feedback-report
   (let ((subject (emacsvox-test--feedback-field "Subject")) spoken)
     (should-not (string-match-p "Meeting arrangements\\|^Play original field\\|  Span " (buffer-string)))
     (forward-line -1)
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (emacsvox-aural-feedback-details-next-heading))
     (should (string-match-p "Subject" spoken))
     (should (eq (plist-get (get-text-property 0 'emacsvox-aural-facts spoken) :visibility) 'folded))
     (should-not (string-match-p "Meeting arrangements" spoken))
     (call-interactively (key-binding (kbd "RET")))
     (should (equal subject (emacsvox-aural-feedback-details--target)))
     (should (eq (emacsvox-aural-ui--control-visibility) 'expanded))
     (should (string-match-p "Meeting arrangements\nPlay original field" (buffer-string)))
     (should-not (string-match-p "  Span " (buffer-string)))
     (should (= 1 (how-many "Meeting arrangements" (point-min) (point-max))))
     (call-interactively (key-binding (kbd "RET")))
     (should (equal subject (emacsvox-aural-feedback-details--target)))
     (should-not (string-match-p "Meeting arrangements\\|^Play original field" (buffer-string))))
   (let ((count (emacsvox-test--feedback-field "Message count")))
     (emacsvox-aural-feedback-details-toggle)
     (should-not (string-match-p "^  Span " (buffer-string)))
     (emacsvox-test--feedback-spans)
     (re-search-forward "^  Span 2\\.")
     (beginning-of-line)
     (call-interactively (key-binding (kbd "RET")))
     (should (equal count (emacsvox-aural-feedback-details--target)))
     (should (eq (emacsvox-aural-ui--control-visibility) 'folded))
     (should-not (string-match-p "  Span " (buffer-string))))))

(ert-deftest emacsvox-aural-feedback-details-explains-only-field-winners-and-limitations ()
  "Object-wide rule lists cannot masquerade as each field's voice source."
  (emacsvox-test--with-feedback-report
   (let* ((authors (emacsvox-aural-feedback-details--plan (car (emacsvox-test--feedback-field "Authors"))))
          (tags (emacsvox-aural-feedback-details--plan (car (emacsvox-test--feedback-field "Tags"))))
          (rules '((:id saved-tags :origin user) (:id unrelated-subject :origin session))))
     ;; Native plans carry object-wide provenance, but content tracks its winner.
     (setf (emacsvox-aural-concrete-plan-rule-provenance authors) rules
           (emacsvox-aural-concrete-plan-rule-provenance tags) rules
           (emacsvox-aural-concrete-content-provenance (emacsvox-aural-concrete-plan-content tags))
           '((voice . saved-tags))
           (emacsvox-aural-concrete-content-voice-provenance (emacsvox-aural-concrete-plan-content tags))
           '((preset . saved-tags))
           (emacsvox-aural-concrete-plan-degradations tags)
           '((:reason unsupported-voice-dimension :adapter omnivox :dimension family :requested outloud-v6)))
     (emacsvox-test--feedback-field "Authors")
     (emacsvox-aural-feedback-details-toggle)
     (should (string-match-p "from the visual face" (buffer-string)))
     (should-not (string-match-p "personal override\\|outloud-v6" (buffer-string)))
     (emacsvox-test--feedback-field "Tags")
     (emacsvox-aural-feedback-details-toggle)
     (should (string-match-p "from your personal override" (buffer-string)))
     (should (string-match-p "Limitation: omnivox could not use the requested family outloud-v6" (buffer-string)))
     (should-not (string-match-p "unrelated-subject\\|saved-tags\\|session override\\|Rules involved" (buffer-string)))
     (emacsvox-aural-feedback-details-toggle)
     (should-not (string-match-p "personal override\\|outloud-v6" (buffer-string))))))

(ert-deftest emacsvox-aural-feedback-details-debug-is-separate-pinned-and-quiet ()
  "Raw data opens quietly outside the report, and q restores its exact position."
  (emacsvox-test--with-feedback-report
   (goto-char (point-min))
   (search-forward "Debug details")
   (backward-char)
   (let ((position (point)) (contents (buffer-string)) debug spoken)
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (call-interactively (key-binding (kbd "RET"))))
     (setq debug (window-buffer (selected-window)))
     (should-not (eq debug report))
     (with-current-buffer debug
       (should buffer-read-only)
       (should (string-match-p "#s(emacsvox-aural-presentation-record" (buffer-string)))
       (should (string-match-p
                (format "^Record %s\\." (emacsvox-aural-presentation-record-id record))
                (buffer-string)))
       (should (< (length spoken) 100))
       (should (string-prefix-p "Debug details" spoken))
       (call-interactively (key-binding (kbd "q"))))
     (should (eq (window-buffer (selected-window)) report))
     (with-current-buffer report
       (should (= position (point)))
       (should (equal contents (buffer-string)))
       (should-not (string-match-p "#s(" (buffer-string)))
       (should (eq record emacsvox-aural-feedback-details--record))
       (emacsvox-aural-feedback-details-debug))
     (should (eq debug (window-buffer (selected-window))))
     (should (equal (list record) emacsvox-aural-presentation-history)))))

(ert-deftest emacsvox-aural-feedback-details-play-button-adds-no-confirmation-cue ()
  "Enter plays exactly the selected field, retaining only its captured sounds."
  (require 'emacsvox-advice)
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Subject"))
          (plan (emacsvox-aural-feedback-details--plan (car indices)))
          (cue (emacsvox-aural--make-concrete-action :kind 'cue :cue 'close-object)))
     (dolist (after (list nil (list cue)))
       (setf (emacsvox-aural-concrete-plan-after plan) after)
       (setq emacsvox-aural-feedback-details--expanded (list indices))
       (emacsvox-aural-feedback-details--render indices)
       (search-forward "Play original field")
       (backward-char 3)
       (let (events)
         (cl-letf (((symbol-function 'emacsvox-icon)
                    (lambda (icon) (push (list 'extra-cue icon) events)))
                   ((symbol-function 'emacsvox-aural-preview-play-runs)
                    (lambda (runs &rest _) (push (list 'play runs) events))))
           (let ((noninteractive nil))
             (call-interactively (key-binding (kbd "RET")))))
         (should (equal (mapcar #'car events) '(play)))
         (should (equal (cadar events)
                        (mapcar (lambda (i) (nth i (emacsvox-aural-presentation-record-runs record))) indices)))
         (should (equal (emacsvox-aural-concrete-plan-after (caar (cadar events))) after)))))))

(ert-deftest emacsvox-aural-feedback-details-visibility-is-aural-metadata ()
  "Headings carry visibility cues and optional speech without literal state labels."
  (require 'emacsvox-advice)
  (emacsvox-test--with-feedback-report
   (emacsvox-aural-register-workflow-provider)
   (let (prepared)
     (cl-letf (((symbol-function 'tts-speak)
                (lambda (text) (setq prepared (emacsvox-aural-prepare-text text)))))
       (cl-labels
           ((check (command visibility occasion)
              (setq prepared nil)
              (funcall command)
              (let* ((plan (emacsvox-aural-concrete-plan-at 0 prepared))
                     (cues (emacsvox-aural-concrete-plan-before plan)))
                (should (eq (plist-get (emacsvox-aural-concrete-plan-facts plan) :visibility) visibility))
                (should (eq (plist-get (emacsvox-aural-concrete-plan-context plan) :occasion) occasion))
                (should (equal (mapcar #'emacsvox-aural-concrete-action-cue cues)
                               (list (if (eq visibility 'expanded) 'open-object 'close-object)))))
              (should-not (string-match-p "\\b\\(expanded\\|collapsed\\)\\b" (buffer-string)))))
         (emacsvox-test--feedback-field "Subject")
         (forward-line -1)
         (check #'emacsvox-aural-feedback-details-next-heading 'folded 'navigation)
         (check (lambda () (call-interactively (key-binding (kbd "RET")))) 'expanded 'state-change)
         (forward-line -1)
         (check #'emacsvox-aural-feedback-details-next-heading 'expanded 'navigation)
         (check (lambda () (call-interactively (key-binding (kbd "RET")))) 'folded 'state-change)
         (forward-line -1)
         (check #'emacsvox-aural-feedback-details-next-line 'folded 'navigation)
         (emacsvox-test--feedback-field "Authors")
         (check #'emacsvox-aural-feedback-details-next-button 'folded 'navigation)
         (emacsvox-aural-set-enabled-feature-fragments '(aural-panel-state-labels))
         (check #'emacsvox-aural-feedback-details-speak-line 'folded 'navigation)
         (should (equal (mapcar #'emacsvox-aural-concrete-action-text
                                (emacsvox-aural-concrete-plan-after
                                 (emacsvox-aural-concrete-plan-at 0 prepared))) '("collapsed"))))))))

(ert-deftest emacsvox-aural-feedback-details-word-movement-does-not-repeat-state ()
  "Section entry and toggling cue state; words within the heading do not."
  (require 'emacsvox-advice)
  (emacsvox-test--with-feedback-report
   (emacsvox-aural-register-workflow-provider)
   (emacsvox-aural-set-enabled-feature-fragments '(aural-panel-state-labels))
   (let (prepared)
     (cl-letf (((symbol-function 'tts-speak)
                (lambda (text) (setq prepared (emacsvox-aural-prepare-text text)))))
       (cl-labels
           ((step (command expected)
              (setq prepared nil)
              (let ((this-command command)
                    (ems--interactive-fn-name command))
                (run-hooks 'pre-command-hook)
                (call-interactively command)
                (run-hooks 'post-command-hook))
              (should (stringp prepared))
              (let ((plan (emacsvox-aural-concrete-plan-at 0 prepared)))
                (ert-info ((format "%S at %d: %s" command (point) prepared))
                  (should (equal (mapcar #'emacsvox-aural-concrete-action-cue
                                        (emacsvox-aural-concrete-plan-before plan))
                                 (when expected (list expected))))))))
         (emacsvox-test--feedback-field "Message count")
         (forward-line -1)
         (step 'emacsvox-aural-feedback-details-next-line 'close-object)
         (step 'forward-word nil)
         (step 'backward-word nil)
         (should-not (emacsvox-aural-concrete-plan-after
                      (emacsvox-aural-concrete-plan-at 0 prepared)))
         (should (eq (emacsvox-aural-ui--control-visibility) 'folded))
         (step 'emacsvox-aural-feedback-details-toggle 'open-object)
         (step 'forward-word nil)
         (step 'backward-word nil)
         (step 'emacsvox-aural-feedback-details-next-line nil)
         (step 'emacsvox-aural-feedback-details-previous-line 'open-object)
         (step 'emacsvox-aural-feedback-details-toggle 'close-object)
         ;; Word movement across the heading boundary also restores the cue.
         (end-of-line)
         (step 'forward-word 'close-object)
         (step 'backward-word nil)
         (step 'backward-word 'close-object)
         (step 'backward-word nil))))))

(ert-deftest emacsvox-aural-feedback-details-compact-voice-keeps-field-draft ()
  "The compact voice route previews the field and resumes the same draft."
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Subject"))
          (original (emacsvox-aural--history-value record))
          editor proposed rule-id)
     (call-interactively (key-binding (kbd "r")))
     (setq editor (current-buffer))
     (should emacsvox-aural-change-feedback--voice-remap)
     (should (eq (plist-get emacsvox-aural-change-feedback-selector :field-kind) 'subject))
     (should (= 1 (cl-count 'original tabulated-list-entries :key #'car)))
     (should (= 1 (cl-count 'proposed tabulated-list-entries :key #'car)))
     (emacsvox-aural-change-feedback-change)
     (should (emacsvox-aural-ui-goto-row '(voice lighten)))
     (emacsvox-aural-change-feedback-open-row)
     (setq rule-id (plist-get (emacsvox-aural-change-feedback--rule) :id))
     (with-current-buffer report
       (setq proposed (emacsvox-aural-feedback-details--proposal-runs)))
     (dolist (i indices)
       (should (eq (emacsvox-aural-concrete-content-voice-request
                    (emacsvox-aural-concrete-plan-content (car (nth i proposed)))) 'lighten)))
     (emacsvox-aural-change-feedback--back)
     (emacsvox-aural-change-feedback--back)
     (should (eq (current-buffer) report))
     (should (equal indices (emacsvox-aural-feedback-details--target)))
     (emacsvox-aural-feedback-details-change)
     (should (eq (current-buffer) editor))
     (should-not emacsvox-aural-change-feedback--voice-remap)
     (should emacsvox-aural-change-feedback-render)
     (should (eq rule-id (plist-get (emacsvox-aural-change-feedback--rule) :id)))
     (emacsvox-test--guided-choose "Add a sound" "After content" "close-object")
     (let ((draft emacsvox-aural-change-feedback-render))
       (pop-to-buffer report)
       (emacsvox-test--feedback-field "Subject")
       (emacsvox-aural-feedback-details--choose-voice)
       (should (eq (current-buffer) editor))
       (should-not emacsvox-aural-change-feedback--voice-remap)
       (should (equal draft emacsvox-aural-change-feedback-render)))
     (should (equal original (emacsvox-aural--history-value record)))
     (should-not emacsvox-aural-user-rules)
     (should-not emacsvox-aural-session-rules))))

(ert-deftest emacsvox-aural-feedback-details-sound-route-is-limited-to-field ()
  "Sound replacement and restoration receive only the selected field's runs."
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Message count"))
          (original (emacsvox-aural--history-value record))
          selected)
     (cl-letf (((symbol-function 'emacsvox-aural-remap-earcon-at-point)
                (lambda (input) (setq selected input))))
       (call-interactively (key-binding (kbd "R"))))
     (should-not (eq selected record))
     (should (equal (emacsvox-aural-presentation-record-effective-plans selected)
                    (mapcar #'emacsvox-aural-feedback-details--plan indices)))
     (should (equal (emacsvox-aural-presentation-record-runs selected)
                    (mapcar (lambda (i) (nth i (emacsvox-aural-presentation-record-runs record))) indices)))
     (should (equal original (emacsvox-aural--history-value record)))
     (setf (emacsvox-aural-presentation-record-payload-truncated-p record) t)
     (should-error (emacsvox-aural-feedback-details--change-sound) :type 'user-error))))

(ert-deftest emacsvox-aural-feedback-details-sound-override-can-be-restored ()
  "A field's exact sound override is prepared, applied, and restored separately."
  (emacsvox-test--with-feedback-report
   (let* ((indices (emacsvox-test--feedback-field "Message count"))
          (plan (emacsvox-aural-feedback-details--plan (car (last indices))))
          (operation "suppress it"))
     (setf (emacsvox-aural-concrete-plan-after plan)
           (list (emacsvox-aural--make-concrete-action
                  :id 'count-cue :kind 'cue :cue 'button :anchor 'transition)))
     (emacsvox-aural-feedback-details-toggle)
     (search-forward "Sound overrides: replace, suppress, or restore")
     (backward-char)
     (let ((position (point)))
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (prompt &rest _)
                    (if (string-prefix-p "Change " prompt) operation
                      "this Emacs session")))
                 ((symbol-function 'emacsvox-aural-preview-play-cues) #'ignore))
         (call-interactively (key-binding (kbd "RET")))
         (should (derived-mode-p 'emacsvox-aural-scheme-editor-mode))
         (should emacsvox-aural-editor-dirty)
         (should-not emacsvox-aural-session-rules)
         (should (eq (plist-get (plist-get (car emacsvox-aural-editor-rules) :match) :field-kind) 'count))
         (emacsvox-aural-editor-save)
         (should (= 1 (length emacsvox-aural-session-rules)))
         (emacsvox-aural-quit)
         (should (eq (current-buffer) report))
         (should (= (point) position))
         (setq operation "restore inherited behavior")
         (call-interactively (key-binding (kbd "RET")))
         (should emacsvox-aural-editor-dirty)
         (should-not emacsvox-aural-editor-rules)
         (should emacsvox-aural-session-rules)
         (emacsvox-aural-editor-save)
         (should-not emacsvox-aural-session-rules))))))

(ert-deftest emacsvox-aural-feedback-details-spans-fold-independently ()
  "Span details stay optional and their section announces no repeated content."
  (emacsvox-test--with-feedback-report
   (let ((indices (emacsvox-test--feedback-field "Message count")) spoken)
     (should-not (string-match-p "voice span" (thing-at-point 'line t)))
     (emacsvox-aural-feedback-details-toggle)
     (search-forward "Individual voice spans")
     (beginning-of-line)
     (should (eq (emacsvox-aural-ui--control-visibility) 'folded))
     (forward-line -1)
     (cl-letf (((symbol-function 'tts-speak) (lambda (text) (setq spoken text))))
       (emacsvox-aural-feedback-details-next-heading))
     (should (string-prefix-p "Individual voice spans" spoken))
     (should-not (text-property-not-all 0 (length spoken) 'emacsvox-aural-recent-feedback-voice nil spoken))
     (call-interactively (key-binding (kbd "RET")))
     (should (eq (emacsvox-aural-ui--control-visibility) 'expanded))
     (should (string-match-p "^  Span 1\\." (buffer-string)))
     (call-interactively (key-binding (kbd "RET")))
     (should (equal indices (get-text-property (point) 'emacsvox-aural-feedback-span-section)))
     (should-not (string-match-p "^  Span " (buffer-string)))
     (should (member indices emacsvox-aural-feedback-details--expanded))
     (should (string-match-p "Play original field" (buffer-string))))))

(ert-deftest emacsvox-aural-feedback-details-draft-status-keeps-return-button ()
  "Live draft labels preserve field actions and the editor's exact return marker."
  (emacsvox-test--with-feedback-report
   (emacsvox-test--feedback-field "Subject")
   (emacsvox-aural-feedback-details-toggle)
   (search-forward "Change field")
   (backward-char)
   (let ((offset (- (point) (button-start (button-at (point)))))
         (original (emacsvox-aural--history-value record)))
     (call-interactively (key-binding (kbd "RET")))
     (emacsvox-test--guided-choose "Change the content voice" "lighten")
     (with-current-buffer report
       (should (string-match-p "1 field with unsaved changes" (buffer-string)))
       (emacsvox-test--feedback-field "Subject")
       (should (string-match-p "unsaved change" (thing-at-point 'line t)))
       (should (button-at (point)))
       (should (eq (emacsvox-aural-ui--control-visibility) 'expanded)))
     (dotimes (_ 3) (emacsvox-aural-change-feedback--back))
     (should (eq (current-buffer) report))
     (should (equal (button-label (button-at (point))) "Change field"))
     (should (= offset (- (point) (button-start (button-at (point))))))
     (call-interactively (key-binding (kbd "RET")))
     (setq emacsvox-aural-change-feedback-scope 'session)
     (emacsvox-aural-change-feedback-apply)
     (with-current-buffer report
       (should (string-match-p "No unsaved field changes" (buffer-string)))
       (emacsvox-test--feedback-field "Subject")
       (should-not (string-match-p "unsaved change" (thing-at-point 'line t))))
     (emacsvox-aural-change-feedback--back)
     (should (eq (current-buffer) report))
     (should (equal (button-label (button-at (point))) "Change field"))
     (should (equal original (emacsvox-aural--history-value record))))))

(ert-deftest emacsvox-aural-feedback-details-graphical-folding-and-draft-return ()
  "A real graphical report keeps its span control and returning change visible."
  (skip-unless (display-graphic-p))
  (emacsvox-test--with-feedback-report
   (let ((window (selected-window)))
     (should (eq (window-buffer window) report))
     (emacsvox-test--feedback-field "Message count")
     (call-interactively (key-binding (kbd "RET")))
     (search-forward "Individual voice spans")
     (beginning-of-line)
     (call-interactively (key-binding (kbd "RET")))
     (redisplay t)
     (should (pos-visible-in-window-p (point) window))
     (should (get-text-property (point) 'emacsvox-aural-feedback-span-section))
     (call-interactively (key-binding (kbd "RET")))
     (redisplay t)
     (should (pos-visible-in-window-p (point) window))
     (should-not (string-match-p "^  Span " (buffer-string)))
     (emacsvox-test--feedback-field "Subject")
     (call-interactively (key-binding (kbd "RET")))
     (search-forward "Change field")
     (backward-char)
     (call-interactively (key-binding (kbd "RET")))
     (emacsvox-test--guided-choose "Change the content voice" "lighten")
     (dotimes (_ 3) (emacsvox-aural-change-feedback--back))
     (redisplay t)
     (should (eq (selected-window) window))
     (should (eq (window-buffer window) report))
     (should (equal (button-label (button-at (point))) "Change field"))
     (should (pos-visible-in-window-p (point) window))
     (should (string-match-p "1 field with unsaved changes" (buffer-string))))))

(ert-deftest emacsvox-aural-feedback-details-sound-only-keeps-relevant-actions ()
  "Feedback without spoken content keeps its meaning and offers sound changes."
  (emacsvox-test--with-feedback-report
   (let* ((plan (copy-emacsvox-aural-concrete-plan
                 (emacsvox-aural-presentation-record-plan record)))
          (content (copy-emacsvox-aural-concrete-content
                    (emacsvox-aural-concrete-plan-content plan))))
     (setf (emacsvox-aural-concrete-content-text content) ""
           (emacsvox-aural-concrete-content-speak content) nil
           (emacsvox-aural-concrete-plan-content plan) content
           (emacsvox-aural-concrete-plan-facts plan) '(:role heading :events (state-changed))
           (emacsvox-aural-concrete-plan-before plan)
           (list (emacsvox-aural--make-concrete-action
                  :id 'event-cue :kind 'cue :cue 'button :anchor 'transition))
           (emacsvox-aural-presentation-record-plan record) plan
           (emacsvox-aural-presentation-record-plans record) (list plan))
     (setq emacsvox-aural-feedback-details--expanded '((0)))
     (emacsvox-aural-feedback-details--render '(0))
     (should-not (equal "Separator" (emacsvox-aural-feedback-details--label '(0))))
     (should (string-match-p "no spoken content" (thing-at-point 'line t)))
     (should (string-match-p "Sound overrides: replace, suppress, or restore" (buffer-string)))
     (should-not (string-match-p "Choose another voice for matching items" (buffer-string)))
     (should-error (call-interactively (key-binding (kbd "r"))) :type 'user-error)
     (should-not emacsvox-aural-feedback-details--drafts)
     (should (eq (current-buffer) report)))))

(provide 'emacsvox-aural-feedback-details-tests)
;;; emacsvox-aural-feedback-details-tests.el ends here
