;;; emacsvox-emoji-tests.el --- Emoji preparation tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'emacsvox-emoji)

(ert-deftest emacsvox-emoji-bundled-trial-names ()
  (dolist (entry '(("🔮" . "crystal ball") ("✨" . "sparkles")
                   ("✅" . "check mark button") ("⚠️" . "warning")
                   ("🚀" . "rocket") ("💡" . "light bulb")
                   ("👩‍💻" . "woman technologist")
                   ("👍🏽" . "thumbs up: medium skin tone")))
    (let ((result (emacsvox-emoji--lookup (car entry))))
      (should (equal (plist-get result :name) (cdr entry)))
      (should (plist-get result :data-file))
      (should (equal (plist-get result :emacs-version) emacs-version)))))

(ert-deftest emacsvox-emoji-lookup-does-not-name-unknown-components ()
  (should (eq (plist-get (emacsvox-emoji--lookup "🔮‍🚀") :diagnostic)
              'missing-name)))

(ert-deftest emacsvox-emoji-text-right-arrow-uses-bundled-name ()
  "Ordinary menu-path arrows are named without changing the source text."
  (let* ((text "Aural Home → Sounds and output → Output volumes")
         (policy (emacsvox-emoji-test--policy))
         (result (emacsvox-emoji--prepare text policy)))
    (should (equal (plist-get result :text)
                   "Aural Home right arrow Sounds and output right arrow Output volumes"))
    (should (equal text "Aural Home → Sounds and output → Output volumes"))
    (should (= (length (plist-get result :replacements)) 2))
    (dolist (replacement (plist-get result :replacements))
      (should (equal (plist-get replacement :sequence) "→"))
      (should (equal (plist-get replacement :name-sequence) "➡"))
      (should (plist-get replacement :data-file)))))

(ert-deftest emacsvox-emoji-text-right-arrow-preserves-policy-boundaries ()
  "Text arrows follow restrictions, counts, custom names and sequence ownership."
  (dolist (text '("→ → →" "→‍🚀" "→́"))
    (should (equal (plist-get (emacsvox-emoji--prepare text (emacsvox-emoji-test--policy)) :text)
                   text)))
  (dolist (policy (list (emacsvox-emoji-test--policy :enabled nil)
                        (emacsvox-emoji-test--policy :approved '("➡"))))
    (should (equal (plist-get (emacsvox-emoji--prepare "→" policy) :text) "→")))
  (should (equal (plist-get (emacsvox-emoji--prepare
                            "→" (emacsvox-emoji-test--policy :names '(("→" . "then")))) :text)
                 "then")))

(ert-deftest emacsvox-emoji-lookup-data-failures-are-bounded ()
  (require 'emoji-labels)
  (dolist (table (list nil '(invalid) (make-hash-table :test 'eq)))
    (let ((emoji--names table))
      (should (equal (emacsvox-emoji--lookup "🔮")
                     '(:diagnostic unavailable-data)))))
  (let ((emoji--names (make-hash-table :test 'equal)))
    (puthash "🔮" 42 emoji--names)
    (should (equal (emacsvox-emoji--lookup "🔮") '(:diagnostic missing-name))))
  (cl-letf (((symbol-function 'require) (lambda (&rest _) (error "missing"))))
    (should (equal (emacsvox-emoji--lookup "🔮")
                   '(:diagnostic unavailable-data)))))

(defun emacsvox-emoji-test--policy (&rest overrides)
  "Return a policy with a small explicit limit for boundary tests."
  (let ((emacsvox-emoji-naming-enabled t)
        (emacsvox-emoji-maximum-count 2))
    (append overrides (emacsvox-emoji--snapshot))))

(ert-deftest emacsvox-emoji-default-limit-handles-decorated-subjects ()
  "Repeated symbols no longer suppress naming for an ordinary mail subject."
  (let* ((text "🤔Dinner? 🍕🍕🍕")
         (policy (emacsvox-emoji--snapshot))
         (frozen (emacsvox-emoji--item-policy text policy)))
    (should-not (plist-get frozen :count-exceeded))
    (should (equal (plist-get (emacsvox-emoji--prepare text frozen) :text)
                   "thinking face Dinner? pizza pizza pizza"))
    (let ((excess (make-string 65 ?🍕)))
      (should (equal (plist-get (emacsvox-emoji--prepare excess policy) :text)
                     excess)))
    (should (equal (plist-get (emacsvox-emoji--prepare
                              text (emacsvox-emoji-test--policy)) :diagnostics)
                   '(count-exceeded)))))

(ert-deftest emacsvox-emoji-arrows-use-bundled-and-unicode-names ()
  "Name ordinary directions and arrows outside the emoji repertoire."
  (dolist (entry '(("←" . "left arrow") ("↑" . "up arrow")
                   ("→" . "right arrow") ("↓" . "down arrow")
                   ("↔" . "left-right arrow") ("↕" . "up-down arrow")
                   ("↗" . "up-right arrow") ("↖" . "up-left arrow")
                   ("↘" . "down-right arrow") ("↙" . "down-left arrow")
                   ("⇒" . "rightwards double arrow")
                   ("⟶" . "long rightwards arrow")
                   ("➜" . "heavy round-tipped rightwards arrow")
                   ("⮕" . "rightwards black arrow")
                   ("🡆" . "rightwards heavy arrow")
                   ("↼" . "leftwards harpoon with barb upwards")
                   ("⤴" . "right arrow curving up")))
    (dolist (suffix '("" "︎" "️"))
      (let* ((text (concat (car entry) suffix))
             (result (emacsvox-emoji--prepare text (emacsvox-emoji--snapshot))))
        (should (equal (plist-get result :text) (cdr entry)))
        (should-not (plist-get result :diagnostics))
        (should (equal (plist-get (car (plist-get result :replacements)) :sequence)
                       text)))))
  (let ((result (emacsvox-emoji--lookup "⟶")))
    (should (eq (plist-get result :source) 'unicode-arrow))
    (should (equal (plist-get result :unicode-name) "LONG RIGHTWARDS ARROW"))))

(ert-deftest emacsvox-emoji-arrow-names-preserve-sequences-and-restrictions ()
  "Unicode arrow names must not expand unrelated text or unknown sequences."
  (dolist (text '("⇒‍🚀" "←́" "⟶🏽" "⮕️‍🚀" "é ∑ 日本語 ⊢"))
    (should (equal (plist-get (emacsvox-emoji--prepare
                              text (emacsvox-emoji--snapshot)) :text)
                   text)))
  (should (equal (plist-get (emacsvox-emoji--prepare
                            "← ↑ ⇒" (emacsvox-emoji-test--policy :approved '("←")))
                           :text)
                 "left arrow ↑ ⇒"))
  (should (equal (plist-get (emacsvox-emoji--prepare
                            "⇒" (emacsvox-emoji-test--policy :names '(("⇒" . "implies"))))
                           :text)
                 "implies")))

(ert-deftest emacsvox-emoji-disabled-and-count-threshold ()
  (let ((original (propertize "Forecast 🔮" 'face 'bold)))
    (should (eq original (plist-get (emacsvox-emoji--prepare original nil) :text)))
    (should (equal (plist-get (emacsvox-emoji--prepare original (emacsvox-emoji-test--policy)) :text)
                   "Forecast crystal ball"))
    (should (equal original "Forecast 🔮")))
  (dolist (entry '(("🔮 🔮" . "crystal ball crystal ball")
                   ("🔮 🔮 🔮" . "🔮 🔮 🔮")
                   ("a🔮✨b" . "a crystal ball sparkles b")))
    (should (equal (plist-get (emacsvox-emoji--prepare (car entry) (emacsvox-emoji-test--policy)) :text)
                   (cdr entry)))))

(ert-deftest emacsvox-emoji-complete-sequences-and-foreign-text ()
  (dolist (text '("🔮‍🚀" "🔮️" "🔮🏽" "🔮́" "é ∑ 日本語"))
    (should (equal text (plist-get (emacsvox-emoji--prepare text (emacsvox-emoji-test--policy)) :text))))
  (let ((policy (emacsvox-emoji-test--policy :approved '("👩‍💻" "👍🏽"))))
    (should (equal (plist-get (emacsvox-emoji--prepare "👩‍💻 👍🏽" policy) :text)
                   "woman technologist thumbs up: medium skin tone")))
  (should (equal (plist-get (emacsvox-emoji--prepare "日本語 🔮 café" (emacsvox-emoji-test--policy)) :text)
                 "日本語 crystal ball café")))

(ert-deftest emacsvox-emoji-full-table-names-without-individual-approval ()
  (let ((policy (emacsvox-emoji-test--policy :approved t)))
    (dolist (entry '(("🌱" . "seedling")
                     ("🇦🇺" . "flag: Australia")
                     ("1️⃣" . "keycap: 1")
                     ("👩‍💻" . "woman technologist")))
      (let ((result (emacsvox-emoji--prepare (car entry) policy)))
        (should (equal (plist-get result :text) (cdr entry)))
        (should-not (plist-get result :diagnostics))))
    (should (equal (plist-get (emacsvox-emoji--prepare "🌱 🌱" policy) :text)
                   "seedling seedling"))
    (should (equal (plist-get (emacsvox-emoji--prepare "🌱 🌱 🌱" policy) :text)
                   "🌱 🌱 🌱"))
    (let ((frozen (emacsvox-emoji--item-policy "🌱 🌱 🌱" policy)))
      (should (equal (plist-get (emacsvox-emoji--prepare "🌱" frozen) :diagnostics)
                     '(count-exceeded))))))

(ert-deftest emacsvox-emoji-explicit-restrictions-still-apply ()
  (dolist (approved '(nil ("🔮")))
    (let ((policy (emacsvox-emoji-test--policy :approved approved)))
      (should (equal (plist-get (emacsvox-emoji--prepare "🌱 🇦🇺 1️⃣" policy) :text)
                     "🌱 🇦🇺 1️⃣"))
      (should-not (plist-get (emacsvox-emoji--item-policy "🌱 🌱 🌱" policy)
                            :count-exceeded)))))

(ert-deftest emacsvox-emoji-full-table-custom-names-survive-missing-data ()
  (cl-letf (((symbol-function 'emacsvox-emoji--lookup)
             (lambda (_) '(:diagnostic unavailable-data))))
    (let ((result (emacsvox-emoji--prepare
                   "🌱 日本語" (emacsvox-emoji-test--policy
                               :approved t :names '(("🌱" . "seedling"))))))
      (should (equal (plist-get result :text) "seedling 日本語"))
      (should (equal (plist-get result :diagnostics) '(unavailable-data))))))

(ert-deftest emacsvox-emoji-custom-names-no-recursion-or-duplicate-preparation ()
  (let* ((policy (emacsvox-emoji-test--policy :names '(("🔮" . "✨ magic"))))
         (result (emacsvox-emoji--prepare "🔮" policy)))
    (should (equal (plist-get result :text) "✨ magic"))
    (should (equal (plist-get (emacsvox-emoji--prepare (plist-get result :text) policy) :text)
                   "✨ magic")))
  (let ((text (propertize "🔮" 'emacsvox-emoji-pronounced t)))
    (should (equal (plist-get (emacsvox-emoji--prepare text (emacsvox-emoji-test--policy)) :text) "🔮"))))

(ert-deftest emacsvox-emoji-invalid-policy-and-missing-data-preserve-input ()
  (dolist (overrides '((:maximum -1) (:maximum 65) (:approved (42))
                       (:names (("🔮" . ""))) (:names (("🔮" . "a\nb")))))
    (let ((result (emacsvox-emoji--prepare "🔮" (apply #'emacsvox-emoji-test--policy overrides))))
      (should (equal (plist-get result :text) "🔮"))
      (should (equal (plist-get result :diagnostics) '(invalid-policy)))))
  (cl-letf (((symbol-function 'emacsvox-emoji--lookup) (lambda (_) '(:diagnostic unavailable-data))))
    (let ((result (emacsvox-emoji--prepare "🔮 🔮" (emacsvox-emoji-test--policy))))
      (should (equal (plist-get result :text) "🔮 🔮"))
      (should (equal (plist-get result :diagnostics) '(unavailable-data))))))

(ert-deftest emacsvox-emoji-preserves-styles-and-maps-positioned-actions ()
  (let* ((text (concat (propertize "a " 'face 'italic)
                       (propertize "⚠️" 'face 'bold) " z"))
         (property 'emacsvox-aural-concrete-positioned-actions)
         (policy (emacsvox-emoji-test--policy)))
    (put-text-property 0 1 property '(before) text)
    (put-text-property 2 3 property '(at-start) text)
    (put-text-property 5 6 property '(after) text)
    (let* ((result (emacsvox-emoji--prepare text policy))
           (output (plist-get result :text))
           (evidence (car (plist-get result :replacements))))
      (should (equal output "a warning z"))
      (should (eq (get-text-property 0 'face output) 'italic))
      (should (eq (get-text-property 7 'face output) 'bold))
      (should (equal (get-text-property 0 property output) '(before)))
      (should (equal (get-text-property 2 property output) '(at-start)))
      (should-not (get-text-property 3 property output))
      (should (equal (get-text-property 10 property output) '(after)))
      (should (= (plist-get evidence :source-start) 2))
      (should (= (plist-get evidence :source-end) 4))
      (should (= (plist-get evidence :output-start) 2))
      (should (= (plist-get evidence :output-end) 9)))
    (put-text-property 3 4 property '(inside) text)
    (should (equal (plist-get (emacsvox-emoji--prepare text policy) :text) text))
    (remove-text-properties 3 4 (list property nil) text)
    (put-text-property 3 4 'face 'italic text)
    (should (equal (plist-get (emacsvox-emoji--prepare text policy) :text) text))))

(ert-deftest emacsvox-emoji-policy-is-source-local-and-frozen ()
  (let ((emacsvox-emoji-naming-enabled nil) policy)
    (with-temp-buffer
      (setq-local emacsvox-emoji-naming-enabled t)
      (setq-local emacsvox-emoji-custom-names (list (cons "🔮" "prediction")))
      (setq policy (emacsvox-emoji--snapshot))
      (aset (cdar emacsvox-emoji-custom-names) 0 ?X))
    (should-not emacsvox-emoji-naming-enabled)
    (should (equal (plist-get (emacsvox-emoji--prepare "🔮" policy) :text) "prediction"))))

(provide 'emacsvox-emoji-tests)
;;; emacsvox-emoji-tests.el ends here
