;;; emacsvox-aural-voice-editor-tests.el --- Spoken voice editor interactions -*- lexical-binding: t; -*-
;;; Commentary:
;; Test visible scope, immutable comparison, save behavior and return navigation.
;;; Code:
(require 'ert)
(require 'emacsvox-aural-voice-drafts-tests)
(require 'emacsvox-aural-voice-editor)
(defmacro emacsvox-test--with-voice-editor (&rest body)
  (declare (indent 0) (debug t))
  `(emacsvox-test--with-voice-save
    (let ((emacsvox-aural-voice-drafts--registry (make-hash-table :test #'equal))
          (emacsvox-aural-voice-editor--contexts (make-hash-table :test #'equal))
          (emacsvox-aural-voice-editor--preview-owner nil)
          (emacsvox-aural-voice-drafts--changed-hook '(emacsvox-aural-voice-editor--draft-changed))
          speech requests callbacks)
      (unwind-protect
          (cl-letf (((symbol-function 'tts-speak) (lambda (text &rest _) (push text speech)))
                    ((symbol-function 'tts-notify) (lambda (text &rest _) (push text speech)))
                    ((symbol-function 'emacsvox-icon) #'ignore)
                    ((symbol-function 'tts-voice-inventory) (lambda () nil))
                    ((symbol-function 'tts-stop) #'ignore)
                    ((symbol-function 'tts-preview-voices)
                     (lambda (entries &optional callback) (push entries requests) (when callback (funcall callback '(:status completed)))))
                    ((symbol-function 'tts-apply-voice-configuration)
                     (lambda (&optional callback) (push callback callbacks))))
            ,@body)
        (maphash (lambda (_ context)
                   (when (buffer-live-p (plist-get context :buffer))
                     (with-current-buffer (plist-get context :buffer)
                       (let ((kill-buffer-query-functions nil)) (kill-buffer)))))
                 emacsvox-aural-voice-editor--contexts)))))

(ert-deftest emacsvox-aural-voice-editor-opening-is-read-only-and-labels-shared-scope ()
  (emacsvox-test--with-voice-editor
   (let ((before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file)))
     (emacsvox-aural-voice-editor-open 'source-child 'voice-bolden)
     (should (derived-mode-p 'emacsvox-aural-voice-editor-mode))
     (should (string-match-p "First save creates an independent copy" (buffer-string)))
     (should (string-match-p "every fallback choice" (buffer-string)))
     (should (eq emacsvox-aural-voice-palette-override 'reading-owned))
     (should-not callbacks)
     (should (equal before (emacsvox-aural-voice-drafts--file-id emacsvox-aural-schemes-file))))))

(ert-deftest emacsvox-aural-voice-editor-comparison-and-save-retain-newer-changes ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'average-pitch 8)
   (emacsvox-aural-voice-editor-compare)
   (let ((entries (car requests)))
     (should (= (length entries) 4))
     (should (= (plist-get (plist-get (nth 1 entries) :acss) :average-pitch) 0))
     (should (= (plist-get (plist-get (nth 3 entries) :acss) :average-pitch) (/ 8.0 9)))
     (should (equal (plist-get (nth 1 entries) :selectors) (plist-get (nth 3 entries) :selectors))))
   (emacsvox-aural-voice-editor-save)
   (should (= (length callbacks) 1))
   (let ((draft (emacsvox-aural-voice-editor--draft)))
     (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
     (emacsvox-aural-voice-editor--set 'average-pitch 9)
     (funcall (car callbacks) '(:status applied))
     (should (emacsvox-aural-voice-drafts--dirty-fields draft))
     (should (string-match-p "Unsaved changes" header-line-format))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-draft-original draft) :definition) :average-pitch) 8)))))

(ert-deftest emacsvox-aural-voice-editor-filter-direction-cancelled-picker-and-return-position ()
  (emacsvox-test--with-voice-editor
   (let ((origin (generate-new-buffer " *voice-editor-origin*")))
     (unwind-protect
         (progn
           (switch-to-buffer origin) (insert "row one\nrow two\n") (goto-char 12)
           (emacsvox-aural-voice-editor-open 'reading-owned 'bolden origin)
           (emacsvox-aural-voice-editor--put :automatic-sample nil)
           (emacsvox-aural-voice-editor--set 'low-pass 3)
           (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :low-pass) 6))
           (let ((before (emacsvox-aural-voice-editor--working)))
             (cl-letf (((symbol-function 'emacsvox-aural-voice-editor--pick) (lambda () (user-error "Cancelled"))))
               (should-error (emacsvox-aural-voice-editor-choose 0)))
             (should (equal before (emacsvox-aural-voice-editor--working))))
           (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Keep draft and return")))
             (emacsvox-aural-voice-editor-leave))
           (should (eq (current-buffer) origin))
           (should (= (point) 12)))
       (kill-buffer origin)))))

(ert-deftest emacsvox-aural-voice-editor-experiment-destination-preserves-fallbacks ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "new") (:voice-id "New voice" :language "en")) (current-buffer) "Sample")
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 8)
   (let ((answers '("reading-owned" "bolden" "Both — shared adjustments for all fallback choices" "Add as fallback")))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (pop answers))))
       (emacsvox-aural-voice-editor-keep-experiment)))
   (let ((working (emacsvox-aural-voice-editor--working)))
     (should (= (length (plist-get working :selectors)) 3))
     (should (equal (plist-get (car (plist-get working :selectors)) :engine-id) "dectalk"))
     (should (= (plist-get (plist-get working :definition) :richness) 8))
     (should-not callbacks)
     (should (equal (emacsvox-aural-voice-editor--get :voice) 'bolden)))))

(ert-deftest emacsvox-aural-voice-editor-both-named-entry-points-resume-the-same-draft ()
  (emacsvox-test--with-voice-editor
   (switch-to-buffer (with-temp-buffer
                       (emacsvox-aural-voice-palette-previews-mode)
                       (setq emacsvox-aural-voice-palette-previews-palette 'reading-owned)
                       (cl-letf (((symbol-function 'emacsvox-aural-voice-palette-previews--current-voice) (lambda () 'bolden)))
                         (emacsvox-aural-voice-palette-previews-tune))))
   (let ((first (emacsvox-aural-voice-editor--draft)))
     (emacsvox-aural-voice-editor--put :automatic-sample nil)
     (emacsvox-aural-voice-editor--set 'richness 7)
     (switch-to-buffer (with-temp-buffer
                         (setq emacsvox-aural-voice-workbench-view 'logical)
                         (insert (propertize "Bolden" 'tabulated-list-id "voice-bolden"))
                         (goto-char (point-min))
                         (cl-letf (((symbol-function 'emacsvox-aural-voice-workbench--active-palette) (lambda () 'reading-owned)))
                           (emacsvox-aural-voice-workbench-tune))))
     (should (eq first (emacsvox-aural-voice-editor--draft)))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :richness) 7))
     (should-not callbacks))))

(ert-deftest emacsvox-aural-voice-editor-killed-draft-remains-discoverable-from-home ()
  (emacsvox-test--with-voice-editor
   (require 'emacsvox-aural-home)
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 7)
   (let ((context emacsvox-aural-voice-editor--context))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Keep draft and return"))) (kill-buffer))
     (should (memq context (emacsvox-aural-home--pending-drafts)))
     (emacsvox-aural-voice-editor--show context (current-buffer))
     (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :richness) 7)))))

(ert-deftest emacsvox-aural-voice-editor-converted-draft-becomes-independent-on-first-save ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'source-child 'voice-bolden)
   (emacsvox-aural-voice-editor--put :automatic-sample nil)
   (emacsvox-aural-voice-editor--set 'richness 7)
   (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new-personal")))
     (emacsvox-aural-voice-editor-save))
   (funcall (car callbacks) '(:status applied))
   (should (eq (emacsvox-aural-voice-editor--get :palette) 'new-personal))
   (let ((source (emacsvox-aural-voice-drafts--palette-data 'source-child)))
     (setq source (plist-put source :summary "Changed source"))
     (puthash 'source-child (emacsvox-aural-compile-voice-palette-data source) emacsvox-aural-voice-palette-registry))
   (emacsvox-aural-voice-editor--set 'richness 8)
   (emacsvox-aural-voice-editor-save)
   (should (= (length callbacks) 2))
   (should (= (plist-get (cdr (assq 'bolden (emacsvox-aural-voice-palette-entries
                                             (gethash 'new-personal emacsvox-aural-voice-palette-registry)))) :richness) 8))))

(ert-deftest emacsvox-aural-voice-editor-picker-auditions-without-editing ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (let ((before (emacsvox-aural-voice-editor--working))
         (answers '("Candidate" "Audition candidate" "Cancel")))
     (cl-letf (((symbol-function 'emacsvox-aural-voice-workbench--physical-candidates)
                (lambda (&rest _) '(("Candidate" (:engine-id "test") (:voice-id "one")))))
               ((symbol-function 'completing-read) (lambda (&rest _) (pop answers))))
       (should-error (emacsvox-aural-voice-editor-choose 0)))
     (should (equal (plist-get (plist-get (caar requests) :selector) :voice-id) "one"))
     (should (equal before (emacsvox-aural-voice-editor--working))))))

(ert-deftest emacsvox-aural-voice-editor-return-after-refresh-and-standard-actions ()
  (emacsvox-test--with-voice-editor
   (let ((origin (generate-new-buffer " *voice-editor-table*")) column)
     (unwind-protect
         (progn
           (switch-to-buffer origin)
           (emacsvox-aural-voice-palette-previews-mode)
           (setq emacsvox-aural-voice-palette-previews-palette 'reading-owned)
           (emacsvox-aural-voice-palette-previews-refresh)
           (emacsvox-aural-ui-goto-row 'bolden)
           (move-to-column 25)
           (setq column (current-column))
           (emacsvox-aural-voice-editor-open 'reading-owned 'bolden origin)
           (should (eq (key-binding (kbd "C-c C-i")) #'emacsvox-aural-ui-open-manual))
           (emacsvox-aural-voice-editor--locate 'more)
           (call-interactively (key-binding (kbd "RET")))
           (should (emacsvox-aural-voice-editor--get :effects))
           (emacsvox-aural-voice-editor--put :automatic-sample nil)
           (emacsvox-aural-voice-editor--set 'richness 8)
           (emacsvox-aural-voice-editor-save)
           (funcall (car callbacks) '(:status applied))
           (should (cl-some (lambda (text) (string-match-p "Saved and applied" text)) speech))
           (emacsvox-aural-voice-editor-leave)
           (should (eq (current-buffer) origin))
           (should (eq (tabulated-list-get-id) 'bolden))
           (should (= (current-column) column)))
       (kill-buffer origin)))))

(ert-deftest emacsvox-aural-voice-editor-adjustment-sample-starts-with-displayed-value ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "test") (:voice-id "one")) (current-buffer) "The quick brown fox.")
   (emacsvox-aural-voice-editor--locate 'average-pitch)
   (setq speech nil)
   (emacsvox-aural-voice-editor-increase)
   (should (equal (plist-get (caar requests) :text) "1. The quick brown fox."))
   (should-not speech)
   (emacsvox-aural-voice-editor-increase)
   (should (equal (plist-get (caar requests) :text) "2. The quick brown fox."))
   (emacsvox-aural-voice-editor--set 'low-pass 3)
   (should (equal (plist-get (caar requests) :text) "3. The quick brown fox."))
   (should (= (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) :low-pass) 6))
   (emacsvox-aural-voice-editor--set 'average-pitch nil)
   (should (equal (plist-get (caar requests) :text) "Adapter default. The quick brown fox."))
   (should (equal (emacsvox-aural-voice-editor--get :text) "The quick brown fox."))
   (emacsvox-aural-voice-editor-play)
   (should (equal (plist-get (caar requests) :text) "The quick brown fox."))))

(ert-deftest emacsvox-aural-voice-editor-adjustment-boundaries-preserve-the-draft ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (dimension '(rate-offset average-pitch pitch-range stress richness
                       gain low-pass high-pass pan reverb echo chorus))
     (emacsvox-aural-voice-editor--locate dimension)
     (dolist (bound (if (eq dimension 'rate-offset) '(-20 20) '(0 9)))
       (emacsvox-aural-voice-editor--set dimension bound)
       (let ((before (emacsvox-aural-voice-editor--working))
             (history (copy-tree (emacsvox-aural-voice-draft-history (emacsvox-aural-voice-editor--draft))))
             (count (length requests)))
         (emacsvox-aural-voice-editor-adjust (if (> bound 0) 1 -1))
         (should (equal before (emacsvox-aural-voice-editor--working)))
         (should (equal history (emacsvox-aural-voice-draft-history (emacsvox-aural-voice-editor--draft))))
         (should (= count (length requests)))
         (should (equal (car speech) (format "%s %s" (if (> bound 0) "Maximum" "Minimum") bound))))))))

(ert-deftest emacsvox-aural-voice-editor-invalid-entry-reports-control-range ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (dolist (entry '((average-pitch "10" "0 to 9") (low-pass "-1" "0 to 9")
                    (rate-offset "21" "-20 to 20")))
     (let ((before (emacsvox-aural-voice-editor--working)))
       (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (nth 1 entry))))
         (let ((error (should-error (emacsvox-aural-voice-editor-edit (car entry)) :type 'user-error)))
           (should (string-match-p (nth 2 entry) (error-message-string error)))))
       (should (equal before (emacsvox-aural-voice-editor--working)))))
   (should-not requests)))

(ert-deftest emacsvox-aural-voice-editor-automatic-sample-toggle-speaks-state ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--locate 'auto-sample)
   (call-interactively (key-binding (kbd "RET")))
   (should (equal (car speech) "Automatic sample after adjustment: off"))
   (emacsvox-aural-voice-editor--locate 'average-pitch)
   (emacsvox-aural-voice-editor-increase)
   (should-not requests)
   (should (string-prefix-p "Average Pitch:" (car speech)))
   (emacsvox-aural-voice-editor--locate 'auto-sample)
   (call-interactively (key-binding (kbd "RET")))
   (should (equal (car speech) "Automatic sample after adjustment: on"))
   (should-not requests)))

(ert-deftest emacsvox-aural-voice-editor-field-navigation-stops-at-both-ends ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--locate 'save)
   (let ((first (point)))
     (call-interactively (key-binding (kbd "<up>")))
     (should (= first (point)))
     (should (string-prefix-p "First field." (car speech)))
     (call-interactively (key-binding (kbd "<down>")))
     (should (> (point) first))
     (call-interactively (key-binding (kbd "<up>")))
     (should (= first (point))))
   (goto-char (button-start (previous-button (point-max))))
   (let ((last (point)))
     (call-interactively (key-binding (kbd "<down>")))
     (should (= last (point)))
     (should (string-prefix-p "Last field." (car speech)))
     (call-interactively (key-binding (kbd "TAB")))
     (should (= last (point)))
     (call-interactively (key-binding (kbd "<up>")))
     (should (< (point) last))
     (call-interactively (key-binding (kbd "<down>")))
     (should (= last (point))))))

(ert-deftest emacsvox-aural-voice-editor-toggle-keys-announce-state-after-distinct-cues ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (let (events)
     (cl-letf (((symbol-function 'emacsvox-icon) (lambda (icon) (push icon events)))
               ((symbol-function 'tts-speak) (lambda (text &rest _) (push text events))))
       (dolist (case '((more "More adjustments and effects" "expanded" "collapsed")
                       (auto-sample "Automatic sample after adjustment" "off" "on")
                       (fallbacks "Fallbacks" "expanded" "collapsed")))
         (emacsvox-aural-voice-editor--locate (car case))
         (should (eq (key-binding (kbd "RET")) #'emacsvox-aural-voice-editor-activate))
         (dolist (state (cddr case))
           (setq events nil)
           (call-interactively (key-binding (kbd "RET")))
           (should (= (length events) 2))
           (should (string-prefix-p (cadr case) (car events)))
           (should (string-suffix-p state (car events)))
           (should (eq (cadr events) (if (member state '("expanded" "on")) 'on 'off)))
           (should (eq (get-text-property (point) 'voice-field) (car case)))
           (let ((label (car events)))
             (call-interactively (key-binding (kbd "<down>")))
             (call-interactively (key-binding (kbd "<up>")))
             (should (equal (car events) label))))))
     (should-not requests))))

(ert-deftest emacsvox-aural-voice-editor-horizontal-arrows-navigate-nonnumeric-fields ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (let ((before (emacsvox-aural-voice-editor--working)))
     (dolist (field '(save primary family more auto-sample))
       (emacsvox-aural-voice-editor--locate field)
       (let ((position (point)))
         (call-interactively (key-binding (kbd "<right>")))
         (should (> (point) position))
         (should (equal (car speech) (button-label (button-at (point)))))))
     (emacsvox-aural-voice-editor--locate 'auto-sample)
     (call-interactively (key-binding (kbd "<left>")))
     (should (eq (get-text-property (point) 'voice-field) 'text))
     (goto-char (point-min))
     (call-interactively (key-binding (kbd "<right>")))
     (should (eq (get-text-property (point) 'voice-field) 'save))
     (should (equal before (emacsvox-aural-voice-editor--working)))
     (should-not requests))))

(ert-deftest emacsvox-aural-voice-editor-default-key-clears-zero-and-can-be-undone ()
  (emacsvox-test--with-voice-editor
   (emacsvox-aural-voice-editor-experiment
    '((:engine-id "test") (:voice-id "one")) (current-buffer) "Sample.")
   (emacsvox-aural-voice-editor--put :effects t)
   (emacsvox-aural-voice-editor-refresh)
   (dolist (dimension '(rate-offset average-pitch low-pass gain pan))
     (emacsvox-aural-voice-editor--locate dimension)
     (emacsvox-aural-voice-editor--set dimension 0)
     (let* ((key (emacsvox-aural--voice-dimension-key dimension))
            (stored (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key)))
       (should (numberp stored))
       (call-interactively (key-binding (kbd "d")))
       (should-not (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key))
       (should (string-match-p "adapter default" (button-label (button-at (point)))))
       (should (equal (plist-get (caar requests) :text) "Adapter default. Sample."))
       (emacsvox-aural-voice-editor-undo)
       (should (equal stored (plist-get (plist-get (emacsvox-aural-voice-editor--working) :definition) key)))))))

(ert-deftest emacsvox-aural-voice-editor-leave-dismisses-window-before-workbench-quit ()
  (emacsvox-test--with-voice-editor
   (save-window-excursion
     (let ((source (generate-new-buffer " *voice-quit-source*"))
           (workbench (generate-new-buffer " *voice-quit-workbench*")))
       (unwind-protect
           (cl-letf (((symbol-function 'emacsvox-speak-mode-line) #'ignore))
             (dolist (same-window '(t nil))
               (delete-other-windows)
               (switch-to-buffer source)
               (let ((display-buffer-overriding-action
                      (if same-window '(display-buffer-same-window)
                        '(display-buffer-pop-up-window))))
                 (pop-to-buffer workbench)
                 (emacsvox-aural-voice-workbench-mode)
                 (setq emacsvox-aural-voice-workbench-view 'engines)
                 (emacsvox-aural-voice-editor-experiment
                  '((:engine-id "test") (:voice-id "one")) workbench "Sample.")
                 (let ((editor (current-buffer))
                       (context emacsvox-aural-voice-editor--context))
                   (call-interactively (key-binding (kbd "q")))
                   (should (eq (current-buffer) workbench))
                   (should (buffer-live-p editor))
                   (should-not (get-buffer-window editor))
                   (call-interactively (key-binding (kbd "q")))
                   (should-not (eq (current-buffer) editor))
                   (should-not (get-buffer-window editor))
                   ;; Leaving retains the experiment, without making it the
                   ;; destination of a later workbench quit.
                   (should (eq (plist-get context :buffer) editor))))))
         (kill-buffer workbench)
         (kill-buffer source))))))

(provide 'emacsvox-aural-voice-editor-tests)
;;; emacsvox-aural-voice-editor-tests.el ends here
