;;; emacsvox-aural-voice-editing-tests.el --- Voice editor proposal contracts -*- lexical-binding: t; -*-
;;; Commentary:
;; Named and physical entry paths must propose the same complete saved voice.
;;; Code:
(require 'ert)
(require 'emacsvox-aural-voice-runtime-tests)
(require 'emacsvox-aural-voice-editing)

(ert-deftest emacsvox-aural-voice-editing-experiment-keeps-are-explicit-and-preserve-chain ()
  (emacsvox-test--with-owned-runtime
   (let* ((snapshot (plist-get (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden) :snapshot))
          (experiment '(:definition (:family nil :average-pitch 8 :pitch-range 2 :stress 4 :richness 5)
                                    :selectors ((:kind exact :scope local :engine-id "new" :voice-id "new"))))
          (physical (emacsvox-aural-voice-editing--keep snapshot experiment 'physical 'replace))
          (adjustments (emacsvox-aural-voice-editing--keep snapshot experiment 'adjustments 'replace))
          (both (emacsvox-aural-voice-editing--keep snapshot experiment 'both 'fallback)))
     (should (equal (plist-get physical :definition) (plist-get snapshot :definition)))
     (should (equal (cdr (plist-get physical :selectors)) (cdr (plist-get snapshot :selectors))))
     (should (equal (plist-get adjustments :selectors) (plist-get snapshot :selectors)))
     (should (equal (plist-get adjustments :definition) (plist-get experiment :definition)))
     (should (equal (butlast (plist-get both :selectors)) (plist-get snapshot :selectors)))
     (should (equal (car (last (plist-get both :selectors))) (car (plist-get experiment :selectors)))))))

(ert-deftest emacsvox-aural-voice-editing-style-only-preserves-local-reference-and-raw-values ()
  (emacsvox-test--with-owned-runtime
   (let* ((snapshot (plist-get (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden) :snapshot))
          (edited (emacsvox-aural-voice-editing--adjust snapshot 'reading-owned 'echo nil))
          (proposal (emacsvox-aural-voice-editing--proposal 'reading-owned 'bolden edited 'reading-owned ""))
          (properties (cdr (assq 'bolden (plist-get (plist-get proposal :palette) :entries)))))
     (should (= (plist-get (plist-get properties :style) :low-pass) 7))
     (should (= (plist-get (plist-get properties :style) :average-pitch) 0))
     (should (plist-member (plist-get properties :style) :echo))
     (should-not (plist-get (plist-get properties :style) :echo))
     (should (equal (plist-get properties :local-choices) "fixture-reading-bolden-1"))
     (should-not (plist-get proposal :choice-sets)))))

(ert-deftest emacsvox-aural-voice-editing-inherited-change-copies-owner-and-automatic-clears-reference ()
  (emacsvox-test--with-owned-runtime
   (puthash 'child-owned
            (emacsvox-aural-compile-voice-palette-data
             '(:schema-version 3 :id child-owned :summary "Child" :parent reading-owned :routing owned :entries nil))
            emacsvox-aural-voice-palette-registry)
   (let* ((snapshot (plist-get (emacsvox-aural-voice-editing--snapshot 'child-owned 'bolden) :snapshot))
          (copy (emacsvox-aural-voice-editing--proposal 'child-owned 'bolden snapshot 'child-owned ""))
          (set (car (plist-get copy :choice-sets))))
     (should (eq (plist-get set :palette) 'child-owned))
     (should (equal (plist-get set :choices) (plist-get snapshot :choices)))
     (setq snapshot (plist-put snapshot :selectors nil))
     (setq snapshot (plist-put snapshot :choices nil))
     (let* ((auto (emacsvox-aural-voice-editing--proposal 'reading-owned 'bolden snapshot 'reading-owned ""))
            (properties (cdr (assq 'bolden (plist-get (plist-get auto :palette) :entries)))))
       (should-not (plist-get properties :local-choices))
       (should-not (plist-get properties :choices))))))

(ert-deftest emacsvox-aural-voice-editing-preview-keeps-chain-and-neutral-effects ()
  (emacsvox-test--with-owned-runtime
   (let* ((snapshot (plist-get (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden) :snapshot))
          (preview (emacsvox-aural-voice-editing--preview snapshot 'reading-owned
                                                          '(:engine-order ("dectalk") :disabled-engines ("disabled") :fallback (:engines ("eloquence"))) "Test")))
     (should (equal (plist-get preview :selectors) (plist-get snapshot :selectors)))
     (should (= (plist-get (plist-get preview :effects) :gain) 0.5))
     (should (= (plist-get (plist-get preview :effects) :pan) 0.5))
     (should (= (plist-get (plist-get preview :effects) :low-pass) (/ 7.0 9)))
     (should (= (plist-get (plist-get preview :acss) :average-pitch) 0))
     (should (= (plist-get preview :rate-offset) -4)))))

(ert-deftest emacsvox-aural-voice-editing-freezes-personality-without-registration ()
  (let ((symbol (make-symbol "test-personality")))
    (set symbol (make-acss :average-pitch 2 :richness 4))
    (cl-letf (((symbol-function 'voice-from-acss) (lambda (&rest _) (ert-fail "Inspection must not register a voice"))))
      (let* ((snapshot (emacsvox-aural-voice-editing--freeze (list :definition symbol :selectors nil) nil))
             (before (emacsvox-aural-voice-editing--style snapshot nil)))
        (set symbol (make-acss :average-pitch 9 :richness 9))
        (should (= (plist-get before :average-pitch) 2))
        (should (equal before (emacsvox-aural-voice-editing--style snapshot nil)))
        (should (eq (plist-get snapshot :definition) symbol))
        (let ((combined (emacsvox-aural-voice-editing--keep snapshot '(:definition nil) 'adjustments 'replace)))
          (should-not (plist-get (emacsvox-aural-voice-editing--style combined nil) :average-pitch)))))))

(defun emacsvox-test--cascade-snapshot ()
  "Return a shared base with two independent occurrences of one physical voice."
  (let* ((selector '(:kind exact :scope local :engine-id "eloquence" :voice-id "Reed"))
         (rows (list (list :id "normal" :selector selector :adjustments '(:richness 0 :echo nil))
                     (list :id "soft" :selector selector :adjustments '(:richness nil :rate-offset 0)))))
    (list :definition '(:family paul :average-pitch 3 :richness 9 :echo 4) :language "en"
          :choices rows :selectors (emacsvox-aural-voice-data--selectors rows))))

(ert-deftest emacsvox-aural-voice-editing-cascade-preserves-rows-and-equal-context ()
  (let* ((snapshot (emacsvox-test--cascade-snapshot))
         (before (copy-tree snapshot))
         (context '(:richness 9 :average-pitch nil :echo nil))
         (entry (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample" context "soft")))
    (should (equal snapshot before))
    (should (equal (plist-get entry :selection) '(:mode choice :choice-id "soft")))
    (should (equal (plist-get (plist-get entry :voice) :choices) (plist-get snapshot :choices)))
    (should (equal (plist-get entry :context) context))
    (should (= (plist-get (plist-get (plist-get entry :voice) :shared) :richness) 9))
    (should-not (plist-member (plist-get (plist-get entry :voice) :shared) :family))
    (should (equal (plist-get entry :placement) '(:pan nil)))
    (let ((composed (emacsvox-aural-voice-editing--compose-preview entry)))
      (should (= (plist-get (plist-get composed :style) :richness) 9))
      (should (= (plist-get (plist-get composed :style) :average-pitch) 3))
      (should (= (plist-get (plist-get composed :style) :rate-offset) 0))
      (should (equal (plist-get composed :defaults) '(:echo))))))

(ert-deftest emacsvox-aural-voice-editing-cascade-refuses-missing-and-inconsistent-rows ()
  (let ((snapshot (emacsvox-test--cascade-snapshot)))
    (should-error (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample" nil "new"))
    (plist-put snapshot :selectors (reverse (append (plist-get snapshot :selectors) '(nil))))
    (should-error (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample"))))

(ert-deftest emacsvox-aural-voice-editing-legacy-gate-retains-default-versus-zero ()
  (let* ((snapshot (emacsvox-test--cascade-snapshot))
         (automatic (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample"))
         (reset (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample" nil "soft"))
         (numeric (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample" '(:richness 0) "soft")))
    (should-error (emacsvox-aural-voice-editing--legacy-preview automatic))
    (should-error (emacsvox-aural-voice-editing--legacy-preview reset))
    (let ((legacy (emacsvox-aural-voice-editing--legacy-preview numeric)))
      (should (equal (plist-get legacy :selector) (car (plist-get snapshot :selectors))))
      (should-not (plist-member legacy :selectors))
      (should (= (plist-get (plist-get legacy :acss) :richness) 0))
      (should (= (plist-get legacy :rate-offset) 0)))
    ;; Contextual ACSS nil is an omission; it cannot undo the row's native reset.
    (plist-put reset :context '(:richness nil))
    (should-error (emacsvox-aural-voice-editing--legacy-preview reset))))

(ert-deftest emacsvox-aural-voice-editing-legacy-shared-context-never-reads-live-policy ()
  (let* ((snapshot (emacsvox-test--cascade-snapshot)))
    (dolist (row (plist-get snapshot :choices)) (plist-put row :adjustments nil))
    (let ((entry (emacsvox-aural-voice-editing--cascade snapshot nil nil "Sample" '(:richness 2 :echo nil))))
      (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () (error "Live inventory read"))))
        (let ((legacy (emacsvox-aural-voice-editing--legacy-preview entry)))
          (should-not (plist-get (plist-get legacy :fallback-policy) :preferred-engines))
          (should (= (plist-get (plist-get legacy :acss) :richness) (/ 2.0 9)))
          (should-not (plist-get (plist-get legacy :effects) :echo)))))))

(ert-deftest emacsvox-aural-voice-editing-shared-edit-preserves-rows-and-tuned-edit-allocates-snapshot ()
  (emacsvox-test--with-owned-runtime
   (let* ((snapshot (emacsvox-aural-voice-editing--freeze
                     (plist-get (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden) :snapshot) 'reading-owned))
          (edited (emacsvox-aural-voice-editing--adjust snapshot 'reading-owned 'echo nil))
          (shared (emacsvox-aural-voice-editing--proposal 'reading-owned 'bolden edited 'reading-owned "")))
     (should-not (plist-get snapshot :transient-choices))
     (should (plist-get snapshot :choices))
     (should (= (plist-get (plist-get shared :palette) :schema-version) 3))
     (should-not (plist-get shared :choice-sets))
     (plist-put (car (plist-get edited :choices)) :adjustments '(:richness 0))
     (let ((tuned (emacsvox-aural-voice-editing--proposal 'reading-owned 'bolden edited 'reading-owned "")))
       (should (= (plist-get (plist-get tuned :palette) :schema-version) 3))
       (should (equal (plist-get (car (plist-get (car (plist-get tuned :choice-sets)) :choices)) :id)
                      (plist-get (car (plist-get edited :choices)) :id)))))))

(ert-deftest emacsvox-aural-voice-editing-field-sources-retain-layer-intent ()
  (let* ((entry '(:voice (:shared (:richness 5 :average-pitch 3 :rate-offset 4 :echo 6)
                         :choices ((:id "first" :selector (:kind exact :scope local :engine-id "test" :voice-id "same")
                                    :adjustments (:richness 7 :average-pitch 8))
                                   (:id "second" :selector (:kind exact :scope local :engine-id "test" :voice-id "same")
                                    :adjustments (:richness nil :average-pitch nil :rate-offset 0 :echo 0))))
                  :context (:richness 5 :average-pitch nil :echo nil)))
         (before (copy-tree entry))
         (fields (emacsvox-aural-voice-editing--field-sources entry "second")))
    (cl-flet ((field (key) (cl-find key fields :key (lambda (item) (plist-get item :dimension)))))
      (should (equal (plist-get (field :richness) :source) 'context))
      (should (= (plist-get (field :richness) :value) 5))
      (should (eq (plist-get (field :richness) :choice-state) 'default))
      (should (eq (plist-get (field :average-pitch) :source) 'choice))
      (should (eq (plist-get (field :average-pitch) :context-state) 'legacy-nil))
      (should-not (plist-get (field :average-pitch) :value))
      (should (= (plist-get (field :rate-offset) :value) 0))
      (should (eq (plist-get (field :echo) :source) 'context))
      (should (eq (plist-get (field :echo) :context-state) 'default)))
    (setq fields (emacsvox-aural-voice-editing--field-sources entry nil))
    (should (eq (plist-get (nth 0 fields) :source) 'shared))
    (should (= (plist-get (nth 0 fields) :value) 3))
    (should (equal entry before))
    (should-error (emacsvox-aural-voice-editing--field-sources entry "absent"))))

(ert-deftest emacsvox-aural-voice-editing-individual-keep-preserves-other-rows-and-shared ()
  (emacsvox-test--with-owned-runtime
   (let* ((snapshot (emacsvox-aural-voice-editing--freeze
                     (plist-get (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden) :snapshot) 'reading-owned))
          (rows (plist-get snapshot :choices))
          (id (plist-get (nth 1 rows) :id))
          (experiment '(:definition (:richness 8 :rate-offset 0 :low-pass 6)
                                    :selectors ((:kind exact :scope local :engine-id "new" :voice-id "new"))))
          (before (copy-tree snapshot)))
     (dolist (placement '(replace preferred fallback))
       (let* ((result (emacsvox-aural-voice-editing--keep-for-choice snapshot experiment 'both placement id))
              (new-rows (plist-get result :choices))
              (target (pcase placement ('replace (nth 1 new-rows)) ('preferred (car new-rows)) (_ (car (last new-rows))))))
         (should (equal (plist-get result :definition) (plist-get snapshot :definition)))
         (should (= (plist-get (plist-get target :adjustments) :richness) 8))
         (should (= (plist-get (plist-get target :adjustments) :rate-offset) 0))
         (should (plist-member (plist-get target :adjustments) :echo))
         (should-not (plist-get (plist-get target :adjustments) :echo))
         (should-not (plist-member (plist-get target :adjustments) :family))
         (should (equal (plist-get result :selectors) (emacsvox-aural-voice-data--selectors new-rows)))
         (if (eq placement 'replace)
             (progn (should (equal (plist-get target :id) id)) (should (equal (car new-rows) (car rows))))
           (should (equal (if (eq placement 'preferred) (cdr new-rows) (butlast new-rows)) rows)))))
     (let ((result (emacsvox-aural-voice-editing--keep-for-choice snapshot experiment 'adjustments 'replace id)))
       (should (equal (plist-get result :selectors) (plist-get snapshot :selectors)))
       (should (equal (car (plist-get result :choices)) (car rows))))
     (should-error (emacsvox-aural-voice-editing--keep-for-choice snapshot experiment 'adjustments 'replace nil))
     (should (equal before snapshot)))))

(provide 'emacsvox-aural-voice-editing-tests)
;;; emacsvox-aural-voice-editing-tests.el ends here
