;;; emacsvox-dired-tests.el --- Dired advice migration tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused coverage for the native advice generated by emacsvox-dired.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'emacsvox-preamble)

(defconst emacsvox-test--dired-advice-targets
  '(dired ido-dired dired-jump dired-other-window dired-other-frame
    dired-next-subdir dired-prev-subdir
    dired-tree-up dired-tree-down dired-up-directory
    dired-next-marked-file dired-prev-marked-file
    dired-next-dirline dired-prev-dirline
    dired-next-line dired-previous-line
    dired-unmark-backward dired-maybe-insert-subdir
    locate locate-with-filter)
  "Dired and Locate commands converted to native advice in this slice.")

(let ((module
       (expand-file-name
        "../lisp/emacsvox-dired.el"
        (file-name-directory (or load-file-name buffer-file-name)))))
  ;; Face-to-voice mapping is startup configuration and irrelevant here.
  (cl-letf (((symbol-function 'voice-setup-add-map) #'ignore))
    (load module nil nil)))

(defun emacsvox-test--dired-advice-function (target)
  "Return the native Emacsvox Dired advice function for TARGET."
  (intern (format "emacsvox--dired-%s-after" target)))

(ert-deftest emacsvox-dired-converted-advice-is-directly-registered ()
  "Every converted Dired advice bypasses the compatibility bridge."
  (dolist (target emacsvox-test--dired-advice-targets)
    (let ((function (emacsvox-test--dired-advice-function target)))
      (should (fboundp function))
      (should (advice-member-p function target))
      (should-not
       (gethash
        (list target :after function) ems--modern-advice-wrappers)))))

(defun emacsvox-test--dired-feedback (target)
  "Call TARGET's migrated advice and return its semantic feedback events."
  (let ((ems--interactive-fn-name target)
        events)
    (cl-letf (((symbol-function 'emacsvox-dired-initialize)
               (lambda () (push 'initialize events)))
              ((symbol-function 'emacsvox-icon)
               (lambda (icon) (push (list 'icon icon) events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'speak-mode-line events)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (push 'speak-dired-line events)))
              ((symbol-function 'emacsvox-speak-line)
               (lambda () (push 'speak-line events))))
      (funcall (emacsvox-test--dired-advice-function target)))
    (nreverse events)))

(ert-deftest emacsvox-dired-converted-advice-preserves-feedback-order ()
  "Representative commands retain their interactive speech and icons."
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired)
    '(initialize (icon open-object) speak-mode-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-prev-subdir)
    '((icon large-movement) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-next-line)
    '((icon select-object) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'locate)
    '(speak-line (icon open-object)))))

(ert-deftest emacsvox-dired-converted-advice-ignores-noninteractive-calls ()
  "Migrated feedback remains restricted to interactive commands."
  (let ((ems--interactive-fn-name nil)
        called)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (&rest _) (setq called t)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (setq called t))))
      (emacsvox--dired-dired-next-line-after))
    (should-not called)))

(provide 'emacsvox-dired-tests)
;;; emacsvox-dired-tests.el ends here
