;;; emacsvox-dired-tests.el --- Dired advice migration tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused coverage for the native advice generated by emacsvox-dired.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'emacsvox-preamble)
(require 'emacsvox-aural-explanation)

(defconst emacsvox-test--dired-advice-targets
  '(dired ido-dired dired-jump dired-other-window dired-other-frame
    dired-next-subdir dired-prev-subdir
    dired-tree-up dired-tree-down dired-up-directory
    dired-goto-file dired-goto-subdir
    dired-next-marked-file dired-prev-marked-file
    dired-next-dirline dired-prev-dirline
    dired-next-line dired-previous-line
    dired-unmark-backward dired-maybe-insert-subdir
    locate locate-with-filter)
  "Dired and Locate commands converted to native advice in this slice.")

(defconst emacsvox-test--dired-handwritten-advice
  '((dired-sort-toggle-or-edit
     :around emacsvox--advice-dired-sort-toggle-or-edit-around)
    (dired-query :before emacsvox--advice-dired-query-before)
    (dired-find-file :around emacsvox--advice-dired-find-file-around)
    (dired-mark :around emacsvox--advice-dired-mark-around)
    (dired-flag-file-deletion
     :around emacsvox--advice-dired-flag-file-deletion-around)
    (dired-unmark :around emacsvox--advice-dired-unmark-around)
    (dired-number-of-marked-files
     :around emacsvox--advice-dired-number-of-marked-files-around)
    (dired-hide-details-mode
     :around emacsvox--advice-dired-hide-details-mode-around)
    (dired-hide-subdir :around emacsvox--advice-dired-hide-subdir-around)
    (dired-hide-all :around emacsvox--advice-dired-hide-all-around)
    (dired-do-async-shell-command
     :around emacsvox--advice-dired-do-async-shell-command-around)
    (revert-buffer :around emacsvox--advice-dired-revert-buffer-around)
    (quit-window :around emacsvox--advice-dired-quit-window-around))
  "Remaining hand-written Dired advice migrated to final native form.")

(defconst emacsvox-test--dired-operation-advice-targets
  '(dired-create-directory dired-create-empty-file
    dired-do-copy dired-do-copy-regexp
    dired-do-rename dired-do-rename-regexp
    dired-do-delete dired-do-flagged-delete
    dired-do-symlink dired-do-symlink-regexp
    dired-do-relsymlink dired-do-relsymlink-regexp
    dired-do-hardlink dired-do-hardlink-regexp
    dired-do-compress dired-do-compress-to
    dired-do-chmod dired-do-chown dired-do-chgrp dired-do-touch
    dired-downcase dired-upcase
    dired-toggle-marks dired-unmark-all-files dired-unmark-all-marks
    dired-change-marks dired-mark-directories dired-mark-executables
    dired-mark-files-containing-regexp dired-mark-files-regexp
    dired-mark-subdir-files dired-mark-symlinks
    dired-flag-auto-save-files dired-flag-backup-files
    dired-flag-files-regexp dired-flag-garbage-files dired-clean-directory
    dired-copy-filename-as-kill dired-do-kill-lines dired-do-redisplay
    dired-undo
    dired-diff dired-do-find-regexp dired-do-find-regexp-and-replace
    dired-do-info dired-do-man dired-do-open dired-do-print
    dired-do-byte-compile dired-do-load dired-do-shell-command
    dired-vc-next-action browse-url-of-dired-file)
  "Dired filesystem operations with semantic result advice.")

(defconst emacsvox-test--dired-open-advice-targets
  '(dired-find-file dired-find-alternate-file
    dired-find-file-other-window dired-display-file dired-view-file)
  "Dired commands whose opened destination is presented.")

(let ((module
       (expand-file-name
        "../lisp/emacsvox-dired.el"
        (file-name-directory (or load-file-name buffer-file-name)))))
  (load module nil nil))

(defun emacsvox-test--dired-advice-function (target)
  "Return the native Emacsvox Dired advice function for TARGET."
  (intern (format "emacsvox--dired-%s-after" target)))

(ert-deftest emacsvox-dired-converted-advice-is-directly-registered ()
  "Every converted Dired advice uses native advice directly."
  (dolist (target emacsvox-test--dired-advice-targets)
    (let ((function (emacsvox-test--dired-advice-function target)))
      (should (fboundp function))
      (should (advice-member-p function target)))))

(defun emacsvox-test--dired-feedback (target)
  "Call TARGET's migrated advice and return its semantic feedback events."
  (let ((ems--interactive-fn-name target)
        events)
    (cl-letf (((symbol-function 'emacsvox-dired-initialize)
               (lambda () (push 'initialize events)))
              ((symbol-function 'emacsvox-icon)
               (lambda (icon) (push (list 'icon icon) events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'speak-mode-line events)))
              ((symbol-function 'emacsvox-dired--current-entry-content)
               (lambda () "entry"))
              ((symbol-function 'emacsvox-dired--line-content)
               (lambda () "results"))
              ((symbol-function 'emacsvox-aural-submit)
               (lambda (_content &rest arguments)
                 (dolist
                     (action
                      (plist-get arguments :compatibility-actions))
                   (push
                    (list
                     'icon
                     (emacsvox-aural-compatibility-action-value action))
                    events))
                 (push 'speak-dired-line events)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (push 'speak-dired-line events)))
              ((symbol-function 'emacsvox-speak-line)
               (lambda () (push 'speak-line events))))
      (funcall (emacsvox-test--dired-advice-function target)))
    (nreverse events)))

(ert-deftest emacsvox-dired-converted-advice-preserves-feedback-order ()
  "Representative commands retain their interactive speech and icons."
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired)
    '(initialize (icon open-object) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-prev-subdir)
    '((icon large-movement) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-next-line)
    '((icon select-object) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'locate)
    '((icon open-object) speak-dired-line))))

(ert-deftest emacsvox-dired-listing-open-is-one-native-submission ()
  "Opening Dired submits its summary, listing facts, and cue together."
  (let ((ems--interactive-fn-name 'dired)
        initialized
        submission)
    (cl-letf
        (((symbol-function 'emacsvox-dired-initialize)
          (lambda () (setq initialized t)))
         ((symbol-function 'emacsvox-dired--buffer-summary)
          (lambda () "tmp, dired by name"))
         ((symbol-function 'emacsvox-dired--submit-text)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (emacsvox--dired-dired-after))
    (should initialized)
    (should
     (equal
      submission
      '("tmp, dired by name"
        (:role filesystem-listing
         :events (filesystem-listing-opened))
        state-change open-object)))))

(ert-deftest emacsvox-dired-listing-visibility-is-semantic ()
  "A listing visibility change carries aspect, state, text, and cue."
  (let (submission)
    (cl-letf
        (((symbol-function 'emacsvox-dired--submit-text)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (emacsvox-dired--present-listing-visibility
       'details 'folded "File details hidden"))
    (should
     (equal
      submission
      '("File details hidden"
        (:role filesystem-listing
         :events (visibility-changed)
         :visibility folded
         :filesystem-listing-aspect details)
        state-change close-object)))))

(ert-deftest emacsvox-dired-hide-details-has-real-feedback ()
  "A real detail toggle changes Dired state and submits one transaction."
  (let* ((directory (make-temp-file "emacsvox-dired-details-" t))
         buffer
         submissions)
    (unwind-protect
        (progn
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf
                (((symbol-function 'emacsvox-aural-submit)
                  (lambda (content &rest arguments)
                    (push (cons content arguments) submissions))))
              (funcall-interactively #'dired-hide-details-mode 1))
            (should dired-hide-details-mode))
          (should (= (length submissions) 1))
          (should
           (equal
            (substring-no-properties (caar submissions))
            "File details hidden"))
          (should
           (equal
            (plist-get (cdar submissions) :facts)
            '(:role filesystem-listing
              :events (visibility-changed)
              :visibility folded
              :filesystem-listing-aspect details))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-revert-is-mode-scoped-and-native ()
  "Only an interactive Dired revert submits a refreshed listing summary."
  (let ((ems--interactive-fn-name 'revert-buffer)
        (calls 0)
        submission)
    (cl-letf
        (((symbol-function 'emacsvox-dired-label-fields) #'ignore)
         ((symbol-function 'emacsvox-dired--buffer-summary)
          (lambda () "tmp, dired by name"))
         ((symbol-function 'emacsvox-dired--submit-text)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (with-temp-buffer
        (setq major-mode 'dired-mode)
        (should
         (eq
          'refreshed
          (emacsvox--advice-dired-revert-buffer-around
           (lambda ()
             (should-not emacsvox-speak-messages)
             (setq calls (1+ calls))
             'refreshed)))))
      (should
       (equal
        submission
        '("tmp, dired by name"
          (:role filesystem-operation
           :filesystem-operation-kind refresh
           :events (operation-completed))
          state-change task-done)))
      (setq submission nil)
      (with-temp-buffer
        (should
         (eq
          'ordinary
          (emacsvox--advice-dired-revert-buffer-around
           (lambda ()
             (setq calls (1+ calls))
             'ordinary))))))
    (should (= calls 2))
    (should-not submission)))

(ert-deftest emacsvox-dired-training-follows-earcon-and-filename ()
  "Training identifies the movement cue after normal Dired feedback."
  (let ((this-command 'dired-next-line)
        (real-this-command 'dired-next-line)
        (post-command-hook nil)
        (tts-speaker-process 'speaker)
        (emacsvox-use-icons t)
        (emacsvox-aural-plan-presented-hook nil)
        (emacsvox-aural-training-mode nil)
        (emacsvox-aural-training-voice 'annotate)
        (emacsvox-aural-explanation--pending-training-explanations nil)
        events)
    (cl-letf
         (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (focus-entered) :states (marked))))
         ((symbol-function 'process-live-p) (lambda (_) t))
         ((symbol-function 'emacsvox-sounds-play-concrete-cue)
          (lambda (&rest _) (push 'earcon events)))
         ((symbol-function 'emacsvox-aural-compile-voice)
          (lambda (voice)
            (should (eq voice 'annotate))
            "TRAINING"))
         ((symbol-function 'tts-voice-reset-code) (lambda () "RESET"))
         ((symbol-function 'tts--protocol-queue-code)
          (lambda (code) (push (list 'code code) events)))
         ((symbol-function 'tts--protocol-queue-text)
          (lambda (text) (push (list 'text text) events)))
         ((symbol-function 'tts--protocol-dispatch)
          (lambda () (push 'dispatch events))))
      (unwind-protect
          (progn
            (emacsvox-aural-training-mode 1)
            (emacsvox-dired-present-current
             'select-object 'navigation 'focus-entered
             (lambda () (push 'filename events)))
            (should
             (equal
              (nreverse (copy-sequence events))
              '(earcon dispatch filename)))
            (run-hooks 'post-command-hook))
        (emacsvox-aural-training-mode -1)))
    (should
     (equal
      (nreverse events)
      '(earcon
        dispatch
        filename
        (code "RESET")
        (code "TRAINING")
        (text
         "filesystem entry, focus entered, marked, entry kind file, earcon mark object, navigation occasion.")
        (code "RESET")
        dispatch)))))

(ert-deftest emacsvox-dired-converted-advice-ignores-noninteractive-calls ()
  "Migrated feedback remains restricted to interactive commands."
  (let ((ems--interactive-fn-name nil)
        called)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (&rest _) (setq called t)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (setq called t))))
      (emacsvox--dired-dired-next-line-after))
    (should-not called)))

(ert-deftest emacsvox-dired-handwritten-advice-is-directly-registered ()
  "Hand-written Dired advice uses native advice directly."
  (dolist (entry emacsvox-test--dired-handwritten-advice)
    (pcase-let ((`(,target ,where ,function) entry))
      (should (fboundp target))
      (should (fboundp function))
      (should (advice-member-p function target))))
  (should-not (fboundp 'dired-quit))
  (should (eq (lookup-key dired-mode-map "q") 'quit-window)))

(ert-deftest emacsvox-dired-operation-advice-is-directly-registered ()
  "Every core filesystem operation has its semantic result advice."
  (dolist (target emacsvox-test--dired-operation-advice-targets)
    (let ((function (intern (format "emacsvox--dired-%s-around" target))))
      (should (fboundp target))
      (should (fboundp function))
      (should (advice-member-p function target)))))

(ert-deftest emacsvox-dired-open-advice-is-directly-registered ()
  "Every core Dired opener has destination-aware advice."
  (dolist (target emacsvox-test--dired-open-advice-targets)
    (let ((function (intern (format "emacsvox--advice-%s-around" target))))
      (should (fboundp target))
      (should (fboundp function))
      (should (advice-member-p function target)))))

(ert-deftest emacsvox-dired-operation-result-runs-once-and-owns-message ()
  "An interactive filesystem operation submits one result without duplication."
  (let ((ems--interactive-fn-name 'dired-do-copy)
        (visible-message "Earlier message")
        (calls 0)
        submission)
    (cl-letf
        (((symbol-function 'current-message)
          (lambda () visible-message))
         ((symbol-function 'emacsvox-dired--submit-message)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (should
       (eq
        'copied
        (emacsvox--dired-dired-do-copy-around
         (lambda (&rest arguments)
           (should-not emacsvox-speak-messages)
           (should (equal arguments '(3)))
           (setq
            calls (1+ calls)
            visible-message "Copy: 2 files done")
           'copied)
         3))))
    (should (= calls 1))
    (should
     (equal
      submission
      '("Copy: 2 files done"
        (:role filesystem-operation
         :filesystem-operation-kind copy
         :events (operation-completed))
        state-change save-object)))))

(ert-deftest emacsvox-dired-operation-cancellation-is-not-success ()
  "A Dired cancellation gets failed facts and a warning cue."
  (let ((ems--interactive-fn-name 'dired-do-delete)
        visible-message
        submission)
    (cl-letf
        (((symbol-function 'current-message)
          (lambda () visible-message))
         ((symbol-function 'emacsvox-dired--submit-message)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (emacsvox--dired-dired-do-delete-around
       (lambda ()
         (setq visible-message "OK, canceled"))))
    (should
     (equal
      submission
      '("OK, canceled"
        (:role filesystem-operation
         :filesystem-operation-kind delete
         :events (operation-failed))
        state-change warn-user)))))

(ert-deftest emacsvox-dired-async-operation-is-started-not-completed ()
  "An asynchronous Dired command reports start without claiming completion."
  (let ((ems--interactive-fn-name 'dired-do-async-shell-command)
        (visible-message "Earlier message")
        (calls 0)
        submission)
    (cl-letf
        (((symbol-function 'current-message)
          (lambda () visible-message))
         ((symbol-function 'emacsvox-dired--submit-message)
          (lambda (&rest arguments)
            (setq submission arguments))))
      (should
       (eq
        'process
        (emacsvox--advice-dired-do-async-shell-command-around
         (lambda (&rest arguments)
           (should-not emacsvox-speak-messages)
           (should (equal arguments '("echo ?" nil ("one"))))
           (setq
            calls (1+ calls)
            visible-message "Started asynchronous command")
           'process)
         "echo ?" nil '("one")))))
    (should (= calls 1))
    (should
     (equal
      submission
      '("Started asynchronous command"
        (:role filesystem-operation
         :filesystem-operation-kind async-shell-command
         :events (operation-started))
        state-change progress)))))

(ert-deftest emacsvox-dired-operation-advice-ignores-programmatic-calls ()
  "Programmatic filesystem operations receive no interactive feedback."
  (let ((calls 0)
        submitted)
    (cl-letf
        (((symbol-function 'emacsvox-dired--submit-message)
          (lambda (&rest _)
            (setq submitted t))))
      (should
       (eq
        'copied
        (emacsvox--dired-dired-do-copy-around
         (lambda ()
           (setq calls (1+ calls))
           'copied)))))
    (should (= calls 1))
    (should-not submitted)))

(ert-deftest emacsvox-dired-create-directory-has-real-operation-feedback ()
  "A real directory creation is performed once and reported semantically."
  (let* ((directory (make-temp-file "emacsvox-dired-create-" t))
         (created (expand-file-name "created" directory))
         buffer
         submission)
    (unwind-protect
        (progn
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf
                (((symbol-function 'emacsvox-dired--submit-message)
                  (lambda (&rest arguments)
                    (setq submission arguments))))
              (funcall-interactively #'dired-create-directory created)))
          (should (file-directory-p created))
          (should
           (equal
            (cadr submission)
            '(:role filesystem-operation
              :filesystem-operation-kind create-directory
              :events (operation-completed)))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-toggle-marks-has-real-operation-feedback ()
  "Bulk mark changes update the listing and submit their semantic result."
  (let* ((directory (make-temp-file "emacsvox-dired-toggle-" t))
         (first (expand-file-name "first.txt" directory))
         (second (expand-file-name "second.txt" directory))
         buffer
         submission)
    (unwind-protect
        (progn
          (write-region "first" nil first nil 'silent)
          (write-region "second" nil second nil 'silent)
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf
                (((symbol-function 'emacsvox-dired--submit-message)
                  (lambda (&rest arguments)
                    (setq submission arguments))))
              (funcall-interactively #'dired-toggle-marks))
            (should
             (= (length (dired-get-marked-files nil nil nil t)) 2)))
          (should
           (equal
            submission
            '("Marks toggled"
              (:role filesystem-operation
               :filesystem-operation-kind toggle-marks
               :events (operation-completed))
              state-change mark-object))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-marked-summary-is-native-inspection ()
  "Marked-file count and size are submitted with listing inspection facts."
  (let* ((directory (make-temp-file "emacsvox-dired-marked-" t))
         (file (expand-file-name "marked.txt" directory))
         buffer
         submission)
    (unwind-protect
        (progn
          (write-region "contents" nil file nil 'silent)
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (dired-goto-file file)
            (dired-mark 1)
            (cl-letf
                (((symbol-function 'emacsvox-dired--submit-message)
                  (lambda (&rest arguments)
                    (setq submission arguments))))
              (funcall-interactively #'dired-number-of-marked-files)))
          (should (string-match-p "\\`1 marked file" (car submission)))
          (should
           (equal
            (cdr submission)
            '((:role filesystem-listing
               :events (entry-inspected)
               :entry-inspection-kind marked-summary)
              inspection select-object))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-operation-semantics-are-registered ()
  "The Dired operation role and discriminator are public semantics."
  (should (emacsvox-aural-semantic 'filesystem-operation))
  (should (emacsvox-aural-semantic 'filesystem-operation-kind))
  (should (emacsvox-aural-semantic 'filesystem-listing-opened))
  (should (emacsvox-aural-semantic 'filesystem-listing-aspect))
  (should (emacsvox-aural-semantic 'operation-started)))

(ert-deftest emacsvox-dired-sort-calls-original-once ()
  "Interactive sorting runs once with messages silenced before feedback."
  (let ((ems--interactive-fn-name 'dired-sort-toggle-or-edit)
        (calls 0)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-dired--buffer-summary)
          (lambda () "tmp, dired by date"))
         ((symbol-function 'emacsvox-dired--submit-text)
          (lambda (&rest arguments)
            (push (cons 'submission arguments) events))))
      (should
       (eq
        'result
        (emacsvox--advice-dired-sort-toggle-or-edit-around
         (lambda (&rest arguments)
           (setq calls (1+ calls))
           (push
            (list 'original arguments
                  emacsvox-speak-messages inhibit-message)
            events)
           'result)
         3))))
    (should (= calls 1))
    (should
     (equal
      (nreverse events)
      '((original (3) nil t)
        (submission
         "tmp, dired by date"
         (:role filesystem-operation
          :filesystem-operation-kind sort
          :events (operation-completed))
         state-change task-done))))))

(ert-deftest emacsvox-dired-programmatic-sort-runs-once-quietly ()
  "Programmatic sorting runs once without Dired-specific feedback."
  (let ((calls 0)
        events)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (&rest arguments) (push arguments events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'mode-line events))))
      (should
       (eq
        'result
        (emacsvox--advice-dired-sort-toggle-or-edit-around
         (lambda (&rest arguments)
           (setq calls (1+ calls))
           (should (equal arguments '(2)))
           'result)
         2))))
    (should (= calls 1))
    (should-not events)))

(ert-deftest emacsvox-dired-find-file-inspects-before-one-call ()
  "File opening detects a directory before calling the original once."
  (let ((ems--interactive-fn-name 'dired-find-file)
        (source (current-buffer))
        (destination (generate-new-buffer " *dired-destination*"))
        (calls 0)
        events)
    (unwind-protect
        (progn
          (cl-letf
              (((symbol-function 'dired-get-file-for-visit)
                (lambda ()
                  (push 'filename events)
                  "/tmp/directory"))
               ((symbol-function 'file-directory-p)
                (lambda (filename)
                  (push (list 'directory filename) events)
                  t))
               ((symbol-function 'emacsvox-dired-entry-facts)
                (lambda (event)
                  (push (list 'facts event) events)
                  '(:role filesystem-entry :entry-kind directory
                    :events (entry-opened))))
               ((symbol-function 'emacsvox-dired--present-opened-destination)
                (lambda (&rest arguments)
                  (push (cons 'present arguments) events))))
            (should
             (eq
              destination
              (emacsvox--advice-dired-find-file-around
               (lambda ()
                 (setq calls (1+ calls))
                 (push 'original events)
                 destination)))))
          (should (= calls 1))
          (should
           (equal
            (nreverse events)
            `(filename
              (directory "/tmp/directory")
              (facts entry-opened)
              original
              (present
               ,destination ,source t
               (:role filesystem-entry :entry-kind directory
                :events (entry-opened)))))))
      (kill-buffer destination))))

(ert-deftest emacsvox-dired-file-open-uses-destination-module-context ()
  "A file opened from Dired is summarized under its destination module."
  (let ((source (generate-new-buffer " *dired-source*"))
        (destination (generate-new-buffer " *dired-file*"))
        submission)
    (unwind-protect
        (progn
          (with-current-buffer destination
            (setq-local emacsvox-aural-module 'org)
            (setq mode-name "Org"))
          (cl-letf
              (((symbol-function 'emacsvox-aural-submit)
                (lambda (content &rest arguments)
                  (setq submission (cons content arguments)))))
            (emacsvox-dired--present-opened-destination
             destination source nil
             '(:role filesystem-entry :entry-kind file
               :events (entry-opened))))
          (should
           (equal
            (substring-no-properties (car submission))
            " *dired-file*, org"))
          (should
           (equal
            (plist-get (cdr submission) :facts)
            '(:role filesystem-entry :entry-kind file
              :events (entry-opened))))
          (should (eq (plist-get (cdr submission) :module) 'org))
          (should
           (eq
            (emacsvox-aural-compatibility-action-value
             (car
              (plist-get
               (cdr submission) :compatibility-actions)))
            'open-object)))
      (kill-buffer source)
      (kill-buffer destination))))

(ert-deftest emacsvox-dired-inserted-directory-remains-navigation ()
  "Opening an inserted subdirectory speaks its row instead of a new buffer."
  (let ((source (generate-new-buffer " *dired-source*"))
        presentation
        submitted)
    (unwind-protect
        (cl-letf
            (((symbol-function 'emacsvox-dired-present-current)
              (lambda (&rest arguments)
                (setq presentation arguments)))
             ((symbol-function 'emacsvox-aural-submit)
              (lambda (&rest _)
                (setq submitted t))))
          (emacsvox-dired--present-opened-destination
           source source t
           '(:role filesystem-entry :entry-kind directory
             :events (entry-opened)))
          (should
           (equal
            presentation
            '(large-movement navigation focus-entered)))
          (should-not submitted))
      (kill-buffer source))))

(ert-deftest emacsvox-dired-real-file-open-submits-one-destination-summary ()
  "A real Dired file visit selects the file and submits one open transaction."
  (let* ((directory (make-temp-file "emacsvox-dired-open-" t))
         (file (expand-file-name "opened.txt" directory))
         dired-buffer
         destination
         submissions)
    (unwind-protect
        (progn
          (write-region "contents" nil file nil 'silent)
          (setq dired-buffer (dired-noselect directory))
          (switch-to-buffer dired-buffer)
          (dired-goto-file file)
          (cl-letf
              (((symbol-function 'emacsvox-aural-submit)
                (lambda (content &rest arguments)
                  (push (cons content arguments) submissions))))
            (funcall-interactively #'dired-find-file))
          (setq destination (current-buffer))
          (should (equal (buffer-file-name destination) file))
          (should (= (length submissions) 1))
          (should
           (equal
            (plist-get (cdar submissions) :facts)
            '(:role filesystem-entry :entry-kind file
              :events (entry-opened))))
          (should (eq (plist-get (cdar submissions) :occasion) 'state-change))
          (should
           (eq
            (emacsvox-aural-compatibility-action-value
             (car
              (plist-get
               (cdar submissions) :compatibility-actions)))
            'open-object)))
      (when (buffer-live-p destination)
        (kill-buffer destination))
      (when (buffer-live-p dired-buffer)
        (kill-buffer dired-buffer))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-entry-facts-describe-kind-and-marker ()
  "Dired exposes filesystem kind, mark state, and operation event."
  (let ((directory (make-temp-file "emacsvox-dired-facts-" t)))
    (unwind-protect
        (with-temp-buffer
          (insert "* entry")
          (goto-char (point-min))
          (cl-letf (((symbol-function 'dired-get-filename)
                     (lambda (&rest _) directory)))
            (should
             (equal
              (emacsvox-dired-entry-facts 'entry-marked)
              '(:role filesystem-entry
                :entry-kind directory
                :events (entry-marked)
                :states (marked))))))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-marked-files-have-distinct-voice ()
  "The whole marked filename, not only its marker, has a distinct voice."
  (should
   (eq
    (voice-setup-get-voice-for-face 'dired-marked)
    'voice-lighten))
  (with-temp-buffer
    (insert (propertize "marked.txt" 'face 'dired-marked))
    (goto-char (point-min))
    (should (eq (tts-get-style) 'voice-lighten))))

(ert-deftest emacsvox-dired-face-presentation-covers-current-dired ()
  "Every face provided by the current Dired interface has one voice mapping."
  (let* ((mapped (mapcar #'car emacsvox-dired--face-voice-map))
         (current
          (seq-filter
           (lambda (face)
             (string-prefix-p "dired-" (symbol-name face)))
           (face-list))))
    (should (= (length mapped) (length (delete-dups (copy-sequence mapped)))))
    (should (= (length current) 12))
    (dolist (face current)
      (should (assq face emacsvox-dired--face-voice-map)))))

(ert-deftest emacsvox-dired-inspection-message-is-one-native-submission ()
  "An inspection result is displayed silently and submitted exactly once."
  (let (messages submissions)
    (cl-letf
        (((symbol-function 'message)
          (lambda (format-string &rest arguments)
            (push
             (list
              emacsvox-speak-messages
              (apply #'format format-string arguments))
             messages)))
         ((symbol-function 'emacsvox-aural-submit)
          (lambda (content &rest arguments)
            (push (cons content arguments) submissions))))
      (emacsvox-dired--present-inspection
       'permissions "Permissions -rw-r--r--"))
    (should (equal messages '((nil "Permissions -rw-r--r--"))))
    (should (= (length submissions) 1))
    (pcase-let ((`(,content . ,arguments) (car submissions)))
      (should (equal content "Permissions -rw-r--r--"))
      (should
       (equal
        (plist-get arguments :facts)
        '(:role filesystem-entry :entry-kind other
          :events (entry-inspected)
          :entry-inspection-kind permissions)))
      (should (eq (plist-get arguments :module) 'dired))
      (should (eq (plist-get arguments :occasion) 'inspection))
      (should
       (eq
        (emacsvox-aural-compatibility-action-value
         (car (plist-get arguments :compatibility-actions)))
        'select-object)))))

(ert-deftest emacsvox-dired-file-type-dereference-uses-file-capital-l ()
  "Prefix inspection asks `file' to dereference rather than list its magic."
  (let ((emacsvox-dired-file-cmd-options "-b --mime-type")
        process-call
        submission)
    (with-temp-buffer
      (let ((source (current-buffer)))
        (cl-letf
            (((symbol-function 'call-process)
              (lambda (program infile destination display &rest arguments)
                (setq
                 process-call
                 (list program infile destination display arguments))
                (insert "text/plain\n")
                0))
             ((symbol-function 'dired-get-filename)
              (lambda (&rest _)
                (and (eq (current-buffer) source) "/tmp/example.txt")))
             ((symbol-function 'file-symlink-p) (lambda (_) nil))
             ((symbol-function 'file-directory-p) (lambda (_) nil))
             ((symbol-function 'file-regular-p) (lambda (_) t))
             ((symbol-function 'emacsvox-dired--submit-message)
              (lambda (&rest arguments)
                (setq submission arguments))))
          (emacsvox-dired-show-file-type "/tmp/example.txt" t))))
    (should
     (equal
      process-call
      '("file" nil t nil
        ("-L" "-b" "--mime-type" "--" "/tmp/example.txt"))))
    (should
     (equal
      submission
      '("text/plain"
        (:role filesystem-entry :entry-kind file
         :events (entry-inspected)
         :entry-inspection-kind file-type)
        inspection select-object)))))

(ert-deftest emacsvox-dired-smart-open-falls-back-for-extensionless-entry ()
  "The smart opener delegates directories and extensionless files to Dired."
  (let (opened)
    (cl-letf
        (((symbol-function 'dired-get-filename)
          (lambda (&rest _) "/tmp/README"))
         ((symbol-function 'call-interactively)
          (lambda (command &rest _)
            (setq opened command))))
      (emacsvox-dired-open-this-file))
    (should (eq opened 'dired-find-file))))

(ert-deftest emacsvox-dired-epub-passes-raw-name-without-second-cue ()
  "The Dired EPUB adapter leaves quoting and feedback to the destination."
  (let (opened icon)
    (cl-letf
        (((symbol-function 'dired-get-filename)
          (lambda (&rest _) "/tmp/A Book.epub"))
         ((symbol-function 'emacsvox-epub-eww)
          (lambda (filename &rest _)
            (setq opened filename)))
         ((symbol-function 'emacsvox-icon)
          (lambda (&rest arguments)
            (setq icon arguments))))
      (emacsvox-dired-epub-eww))
    (should (equal opened "/tmp/A Book.epub"))
    (should-not icon)))

(ert-deftest emacsvox-dired-duration-does-not-shell-parse-file-name ()
  "Media duration passes an apostrophe-containing filename as one process arg."
  (let* ((directory (make-temp-file "emacsvox-dired-duration-" t))
         (file (expand-file-name "Bart's track.mp3" directory))
         (sox-soxi t)
         (emacsvox-media-extensions "\\.mp3\\'")
         (major-mode 'dired-mode)
         process-call
         presentation)
    (unwind-protect
        (progn
          (write-region "audio" nil file nil 'silent)
          (cl-letf
              (((symbol-function 'dired-get-filename)
                (lambda (&rest _) file))
               ((symbol-function 'call-process)
                (lambda (program infile destination display &rest arguments)
                  (setq
                   process-call
                   (list program infile destination display arguments))
                  (insert "00:01:23.45\n")
                  0))
               ((symbol-function 'emacsvox-dired--present-inspection)
                (lambda (&rest arguments)
                  (setq presentation arguments))))
            (emacsvox-dired-play-duration))
          (should
           (equal
            process-call
            `("soxi" nil t nil ("-d" ,file))))
          (should
           (equal
            presentation
            '(duration "00:01:23.45 Bart's track"
              select-object nil))))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-rpm-query-does-not-use-a-shell ()
  "RPM inspection passes the selected filename directly to each process."
  (let (process-calls submission shell-used)
    (unwind-protect
        (with-temp-buffer
          (setq major-mode 'dired-mode)
          (cl-letf
              (((symbol-function 'dired-get-filename)
                (lambda (&rest _) "/tmp/package name's file"))
               ((symbol-function 'emacsvox-dired-entry-facts)
                (lambda (&rest _)
                  '(:role filesystem-entry :entry-kind file
                    :events (entry-inspected))))
               ((symbol-function 'call-process)
                (lambda (program infile destination display &rest arguments)
                  (push
                   (list program infile destination display arguments)
                   process-calls)
                  (insert
                   (if (equal arguments
                              '("-qf" "/tmp/package name's file"))
                       "example-package\n"
                     "Name: example-package\nSummary: Example package\n"))
                  0))
               ((symbol-function 'shell-command)
                (lambda (&rest _)
                  (setq shell-used t)))
               ((symbol-function 'pop-to-buffer)
                (lambda (buffer &rest _)
                  (set-buffer buffer)))
               ((symbol-function 'emacsvox-dired--submit-text)
                (lambda (&rest arguments)
                  (setq submission arguments))))
            (emacsvox-dired-rpm-query-in-dired)))
      (when-let* ((buffer (get-buffer "*RPM Query*")))
        (kill-buffer buffer)))
    (should-not shell-used)
    (should
     (equal
      (nreverse process-calls)
      '(("rpm" nil t nil ("-qf" "/tmp/package name's file"))
        ("rpm" nil t nil ("-qi" "example-package")))))
    (should
     (equal
      submission
      '("Summary: Example package"
        (:role filesystem-entry :entry-kind file
         :events (entry-inspected)
         :entry-inspection-kind package)
        inspection open-object)))))

(ert-deftest emacsvox-dired-missing-inspection-is-semantic-failure ()
  "Inspecting a non-entry row submits the failure and warning cue."
  (let (presentation)
    (cl-letf
        (((symbol-function 'dired-get-filename) (lambda (&rest _) nil))
         ((symbol-function 'emacsvox-dired--submit-message)
          (lambda (&rest arguments)
            (setq presentation arguments))))
      (emacsvox-dired-speak-file-permissions))
    (should
     (equal
      presentation
      '("No file on current line"
        (:role filesystem-entry :entry-kind other
         :events (entry-inspected operation-failed)
         :entry-inspection-kind permissions)
        inspection warn-user)))))

(ert-deftest emacsvox-dired-header-is-submitted-as-listing-content ()
  "The Dired header is submitted natively with listing-level facts."
  (let (submission)
    (with-temp-buffer
      (insert "header one\nheader two\nentry\n")
      (cl-letf
          (((symbol-function 'emacsvox-dired--submit-text)
            (lambda (&rest arguments)
              (setq submission arguments))))
        (emacsvox-dired-speak-header-line)))
    (should
     (equal
      submission
      '("header one\nheader two"
        (:role filesystem-listing
         :events (entry-inspected)
         :entry-inspection-kind header)
        inspection section)))))

(ert-deftest emacsvox-dired-marked-navigation-uses-mark-earcon ()
  "Entering a marked row replaces the generic selection cue."
  (let ((emacsvox-aural-active-scheme 'default)
        (emacsvox-aural-enabled-feature-fragments nil)
        (emacsvox-aural-user-rules nil)
        (emacsvox-aural-session-rules nil)
        (emacsvox-aural-buffer-rules nil)
        (context (emacsvox-aural-capture-context 'dired 'navigation))
        plan)
    (setq
     plan
     (emacsvox-aural-resolve-legacy-icon
      'select-object context
      '(:role filesystem-entry :entry-kind file
        :events (focus-entered) :states (marked))))
    (should
     (equal
      (mapcar
       #'emacsvox-aural-action-cue
       (emacsvox-aural-render-plan-before plan))
      '(mark-object)))))

(ert-deftest emacsvox-dired-navigation-uses-one-native-submission ()
  "Default current-entry feedback submits content and cue together."
  (let ((content (propertize "entry.txt" 'personality 'voice-lighten))
        calls)
    (cl-letf
        (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (focus-entered))))
         ((symbol-function 'emacsvox-dired--current-entry-content)
          (lambda () content))
         ((symbol-function 'emacsvox-aural-submit)
          (lambda (submitted &rest arguments)
            (push (cons submitted arguments) calls)
            'submission)))
      (emacsvox-dired-present-current
       'select-object 'navigation 'focus-entered))
    (should (= (length calls) 1))
    (pcase-let* ((`(,submitted . ,arguments) (car calls))
                 (actions (plist-get arguments :compatibility-actions))
                 (action (car actions)))
      (should (equal submitted "entry.txt"))
      (should (eq (get-text-property 0 'personality submitted) 'voice-lighten))
      (should
       (equal
        (plist-get arguments :facts)
        '(:role filesystem-entry :entry-kind file
          :events (focus-entered))))
      (should (eq (plist-get arguments :module) 'dired))
      (should (eq (plist-get arguments :occasion) 'navigation))
      (should (= (length actions) 1))
      (should (eq (emacsvox-aural-compatibility-action-phase action) 'before))
      (should
       (eq
        (emacsvox-aural-compatibility-action-value action)
        'select-object)))))

(ert-deftest emacsvox-dired-missing-filename-keeps-legacy-fallback ()
  "A non-entry row still cues, speaks the line, and dings."
  (let (events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind other
              :events (focus-entered))))
         ((symbol-function 'emacsvox-dired--current-entry-content)
          (lambda () nil))
         ((symbol-function 'emacsvox-icon)
          (lambda (icon) (push (list 'icon icon) events)))
         ((symbol-function 'emacsvox-speak-line)
          (lambda () (push 'line events)))
         ((symbol-function 'ding)
          (lambda (&rest _) (push 'ding events))))
      (emacsvox-dired-present-current
       'select-object 'navigation 'focus-entered))
    (should
     (equal
      (nreverse events) '((icon select-object) line ding)))))

(ert-deftest emacsvox-dired-native-navigation-resolves-and-presents-once ()
  "Marked-entry navigation preserves voice and one ordered transaction."
  (dolist (icons-enabled '(t nil))
    (let ((emacsvox-aural-active-scheme 'default)
          (emacsvox-aural-enabled-feature-fragments nil)
          (emacsvox-aural-user-rules nil)
          (emacsvox-aural-session-rules nil)
          (emacsvox-aural-buffer-rules nil)
          (emacsvox-aural-presentation-history nil)
          (emacsvox-aural-presentation-history-limit 20)
          (emacsvox-aural--presentation-sequence 0)
          (emacsvox-aural--submission-sequence 0)
          (emacsvox-aural-plan-presented-hook nil)
          (emacsvox-use-icons icons-enabled)
          (emacsvox-aural-face-presentation-enabled t)
          (voice-lock-mode t)
          events
          submission)
      (cl-letf
          (((symbol-function 'emacsvox-dired-entry-facts)
            (lambda (&rest _)
              '(:role filesystem-entry :entry-kind file
                :events (focus-entered) :states (marked))))
           ((symbol-function 'emacsvox-dired--current-entry-content)
            (lambda ()
              (propertize
               "marked.txt" 'personality 'voice-lighten)))
           ((symbol-function 'tts-speak)
            (lambda (prepared)
              (with-temp-buffer
                (insert prepared)
                (tts-audio-format (point-min) (point-max)))))
           ((symbol-function 'emacsvox-queue-resource)
            (lambda (_resource) (push 'cue events)))
           ((symbol-function 'tts-voice-reset-code)
            (lambda () "RESET"))
           ((symbol-function 'tts--protocol-queue-code) #'ignore)
           ((symbol-function 'tts--protocol-queue-text)
            (lambda (text) (push (list 'text text) events)))
           ((symbol-function 'tts--protocol-silence) #'ignore))
        (setq
         submission
         (emacsvox-dired-present-current
          'select-object 'navigation 'focus-entered)))
      (should (emacsvox-aural-submission-p submission))
      (should
       (equal
        (nreverse events)
        (if icons-enabled
            '(cue (text "marked.txt"))
          '((text "marked.txt")))))
      (should (= (length emacsvox-aural-presentation-history) 1))
      (should
       (= (emacsvox-aural-presentation-record-transaction-id
           (emacsvox-aural-last-presentation))
          1))
      (let* ((plans (emacsvox-aural-submission-plans submission))
             (plan (car plans))
             (content (emacsvox-aural-concrete-plan-content plan)))
        (should (= (length plans) 1))
        (should
         (equal
          (mapcar
           #'emacsvox-aural-concrete-action-cue
           (emacsvox-aural-concrete-plan-before plan))
          (and icons-enabled '(mark-object))))
        (should
         (eq
          (emacsvox-aural-concrete-content-voice-request content)
          'voice-lighten))
        (should
         (eq
          (plist-get
           (emacsvox-aural-concrete-plan-context plan)
           :icons-enabled)
          icons-enabled))))))

(ert-deftest emacsvox-dired-marking-submits-two-semantic-objects ()
  "A marking cue and destination retain distinct facts in one submission."
  (let* ((action-facts
          '(:role filesystem-entry :entry-kind file
            :events (entry-marked) :states (marked)))
         (destination-facts
          '(:role filesystem-entry :entry-kind directory
            :events (focus-entered)))
         (context
          '(:module dired :mode dired-mode :occasion state-change
            :icons-enabled t))
         submission)
    (cl-letf
        (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _) destination-facts))
         ((symbol-function 'emacsvox-dired--current-entry-content)
          (lambda () (propertize "next" 'personality 'voice-bolden)))
         ((symbol-function 'emacsvox-aural-submit)
          (lambda (content &rest arguments)
            (setq submission (cons content arguments)))))
      (emacsvox-dired--present-marking-result
       action-facts context 'mark-object))
    (pcase-let* ((`(,content . ,arguments) submission)
                 (actions (plist-get arguments :compatibility-actions)))
      (should (equal (substring-no-properties content) "xnext"))
      (should
       (eq
        (get-text-property 0 emacsvox-aural-object-property content)
        'dired-marking-action))
      (should
       (eq
        (get-text-property 1 emacsvox-aural-object-property content)
        'dired-marking-destination))
      (should
       (equal
        (get-text-property 0 emacsvox-aural-facts-property content)
        action-facts))
      (should
       (equal
        (get-text-property 1 emacsvox-aural-facts-property content)
        destination-facts))
      (should (eq (get-text-property 0 'personality content) 'inaudible))
      (should (eq (get-text-property 1 'personality content) 'voice-bolden))
      (should
       (eq
        (get-text-property 0 emacsvox-aural-occasion-property content)
        'state-change))
      (should
       (eq
        (get-text-property 1 emacsvox-aural-occasion-property content)
        'navigation))
      (should (equal (plist-get arguments :context) context))
      (should (eq (plist-get arguments :occasion) 'navigation))
      (should (eq (plist-get arguments :delivery-policy) 'replaceable))
      (should (eq (plist-get arguments :replacement-key) 'dired-marking))
      (should (= (length actions) 1))
      (should
       (eq
        (emacsvox-aural-compatibility-action-value (car actions))
        'mark-object)))))

(ert-deftest emacsvox-dired-marking-replaces-one-complete-packet ()
  "Rapid marking retains only the latest cue-then-destination transaction."
  (let ((emacsvox-aural-active-scheme 'default)
        (emacsvox-aural-enabled-feature-fragments nil)
        (emacsvox-aural-user-rules nil)
        (emacsvox-aural-session-rules nil)
        (emacsvox-aural-buffer-rules nil)
        (emacsvox-aural--pending-deliveries
         (make-hash-table :test #'equal))
        (emacsvox-aural--delivery-sequence 0)
        (emacsvox-aural--submission-sequence 0)
        (emacsvox-aural-presentation-history nil)
        (emacsvox-aural-plan-presented-hook nil)
        (emacsvox-play-program nil)
        (emacsvox-use-icons t)
        (emacsvox-pronounce-table nil)
        (emacsvox-pronounce-personality nil)
        (tts-speaker-process 'speech)
        (tts-notify-process nil)
        (tts-stop-immediately t)
        (tts-stopped-hook nil)
        (tts-punctuation-mode 'all)
        (tts-quiet nil)
        (voice-lock-mode nil)
        (context
         '(:module dired
           :mode dired-mode
           :mode-lineage (dired-mode special-mode)
           :occasion state-change
           :face-presentation-enabled t
           :voice-lock-enabled nil
           :icons-enabled t))
        (contents '("obsolete destination" "latest destination"))
        writes)
    (cl-letf
        (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (focus-entered))))
         ((symbol-function 'emacsvox-dired--current-entry-content)
          (lambda () (pop contents)))
         ((symbol-function 'process-live-p)
          (lambda (process) (eq process 'speech)))
         ((symbol-function 'process-send-string)
          (lambda (process command)
            (push (list process command) writes)))
         ((symbol-function 'run-with-idle-timer)
          (lambda (&rest _arguments) 'timer))
         ((symbol-function 'cancel-timer) #'ignore)
         ((symbol-function 'tts-voice-reset-code)
          (lambda () "RESET")))
      (emacsvox-dired--present-marking-result
       '(:role filesystem-entry :entry-kind file
         :events (entry-marked) :states (marked))
       context 'mark-object)
      (emacsvox-dired--present-marking-result
       '(:role filesystem-entry :entry-kind file
         :events (entry-unmarked))
       context 'deselect-object)
      (should
       (equal
        (nreverse (copy-sequence writes))
        '((speech "s\n") (speech "s\n"))))
      (emacsvox-aural-flush-pending-deliveries 'speech))
    (let* ((writes (nreverse writes))
           (wire (mapconcat #'cadr writes ""))
           (cue-position (string-match "deselect-object\\.ogg" wire))
           (speech-position (string-match "latest destination" wire)))
      (should (= (length writes) 3))
      (should-not (string-match-p "obsolete destination" wire))
      (should-not (string-match-p "mark-object\\.ogg" wire))
      (should cue-position)
      (should speech-position)
      (should (< cue-position speech-position))
      (should (string-match-p "\nd\n\\'" wire)))))

(ert-deftest emacsvox-dired-marking-feedback-is-target-aware ()
  "Only the matching command emits action cue then next-row speech."
  (let ((ems--interactive-fn-name 'dired-flag-file-deletion)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-action-facts)
          (lambda (&rest _) '(:role filesystem-entry)))
         ((symbol-function 'emacsvox-dired--present-marking-result)
          (lambda (facts _context icon)
            (push (list 'presentation facts icon) events))))
      (emacsvox--advice-dired-mark-around
       (lambda () (push 'mark events)))
      (emacsvox--advice-dired-flag-file-deletion-around
       (lambda () (push 'original events)))
      (emacsvox--advice-dired-unmark-around
       (lambda () (push 'unmark events))))
    (should
     (equal
      (nreverse events)
      '(mark
        original
        (presentation (:role filesystem-entry) delete-object)
        unmark)))))

(ert-deftest emacsvox-dired-marking-freezes-the-action-target ()
  "The action cue keeps pre-command facts while next-row speech is navigation."
  (let ((ems--interactive-fn-name 'dired-mark)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-action-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (entry-marked) :states (marked))))
         ((symbol-function 'emacsvox-dired--present-marking-result)
          (lambda (facts _context icon)
            (push (list 'presentation facts icon) events))))
      (emacsvox--advice-dired-mark-around
       (lambda () (push 'original events) 'result)))
    (should
     (equal
      (nreverse events)
      '(original
        (presentation
         (:role filesystem-entry :entry-kind file
          :events (entry-marked) :states (marked))
         mark-object))))))

(ert-deftest emacsvox-dired-interactive-mark-actions-preserve-destination ()
  "Real mark and unmark commands capture their destination row."
  (let* ((directory (make-temp-file "emacsvox-dired-actions-" t))
         (first (expand-file-name "first.txt" directory))
         (second (expand-file-name "second.txt" directory))
         buffer
         events)
    (unwind-protect
        (progn
          (write-region "first" nil first nil 'silent)
          (write-region "second" nil second nil 'silent)
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf
                (((symbol-function 'emacsvox-dired--present-marking-result)
                  (lambda (facts _context icon)
                    (push
                     (list
                      icon
                      (plist-get facts :events)
                      (file-name-nondirectory
                       (dired-get-filename nil t)))
                     events))))
              (dired-goto-file first)
              (funcall-interactively #'dired-mark nil t)
              (dired-goto-file first)
              (funcall-interactively #'dired-unmark nil t))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))
    (should
     (equal
      (nreverse events)
      '((mark-object (entry-marked) "second.txt")
        (deselect-object (entry-unmarked) "second.txt"))))))

(ert-deftest emacsvox-dired-quit-feedback-is-mode-scoped ()
  "Only an interactive quit originating in Dired gets Dired feedback."
  (let ((ems--interactive-fn-name 'quit-window)
        (calls 0)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-icon)
          (lambda (icon)
            (push
             (list
              'icon icon emacsvox-aural-submission-facts
              (plist-get emacsvox-aural-submission-context :module))
             events)))
         ((symbol-function 'emacsvox-speak-mode-line)
          (lambda () (push 'mode-line events))))
      (with-temp-buffer
        (setq major-mode 'dired-mode)
        (should
         (eq
          'dismissed
          (emacsvox--advice-dired-quit-window-around
           (lambda ()
             (setq calls (1+ calls))
             (setq major-mode 'fundamental-mode)
             'dismissed)))))
      (setq ems--interactive-fn-name 'quit-window)
      (with-temp-buffer
        (should
         (eq
          'ordinary
          (emacsvox--advice-dired-quit-window-around
           (lambda ()
             (setq calls (1+ calls))
             'ordinary))))))
    (should (eq ems--interactive-fn-name 'quit-window))
    (should (= calls 2))
    (should
     (equal
      (nreverse events)
      '((icon close-object
         (:role filesystem-listing
          :events (filesystem-listing-closed))
         dired)
        mode-line)))))

(ert-deftest emacsvox-dired-query-cue-remains-unconditional ()
  "Dired queries always cue before deciding whether prompting is needed."
  (let (events)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (icon) (push icon events))))
      (emacsvox--advice-dired-query-before))
    (should (equal events '(ask-short-question)))))

(provide 'emacsvox-dired-tests)
;;; emacsvox-dired-tests.el ends here
