;;; emacsvox-aural-voice-bulk-tests.el --- Complete palette voice workflow -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
;;; Commentary:
;; Cover complete saved palettes, private comparisons and interrupted bulk saves.
;;; Code:

(require 'emacsvox-aural-voice-editor-tests)
(require 'emacsvox-aural-voice-choice-tests)
(require 'omnivox-espeak-variants-tests)
(require 'emacsvox-aural-voice-bulk)

(defconst emacsvox-test--bulk-selector
  '(:kind exact :scope local :engine-id "espeak" :voice-id "espeak:gmw/en-US+max"))

(defmacro emacsvox-test--with-bulk (&rest body)
  "Run BODY with real isolated stores, private reviews and stubbed audio."
  (declare (indent 0) (debug t))
  `(emacsvox-test--with-voice-editor
     (let ((emacsvox-aural-voice-bulk--contexts (make-hash-table :test #'equal))
           (emacsvox-aural-voice-drafts--changed-hook
            (cons #'emacsvox-aural-voice-bulk--changed emacsvox-aural-voice-drafts--changed-hook)))
       (unwind-protect (progn ,@body)
         (maphash (lambda (_ context)
                    (when (buffer-live-p (plist-get context :buffer))
                      (kill-buffer (plist-get context :buffer))))
                  emacsvox-aural-voice-bulk--contexts)))))

(defun emacsvox-test--bulk-open (&optional copy)
  "Open the fixture's palette review, optionally as a COPY."
  (emacsvox-aural-voice-bulk--open 'reading-owned (if copy 'bulk-copy 'reading-owned)
                                 emacsvox-test--bulk-selector "English US plus Max" (current-buffer)))

(ert-deftest emacsvox-aural-voice-bulk-promotes-first-match-with-complete-tuning ()
  (let* ((native (emacsvox-test--native-choices))
         (before (append (list (car (last native))) (butlast native)))
         (saved (copy-tree before))
         (selector (plist-get (cadr before) :selector))
         (after (emacsvox-aural-voice-editing--prefer-physical before selector)))
    (should (equal (mapcar (lambda (row) (plist-get row :id)) after)
                   '("paul-main" "eci-default" "paul-soft")))
    (should (equal (car after) (cadr before)))
    (should (equal (caddr after) (caddr before)))
    (should (equal before saved))
    (should (equal after (emacsvox-aural-voice-editing--prefer-physical after selector)))))

(ert-deftest emacsvox-aural-voice-bulk-new-choice-inherits-without-transferring-native-settings ()
  (let* ((before (emacsvox-test--native-choices))
         (after (emacsvox-aural-voice-editing--prefer-physical before emacsvox-test--bulk-selector)))
    (should (equal (cdr after) before))
    (should-not (plist-get (car after) :adjustments))
    (should-not (plist-member (car after) :native))
    (should (equal (plist-get (car after) :selector) emacsvox-test--bulk-selector))
    (should-not (member (plist-get (car after) :id) (mapcar (lambda (row) (plist-get row :id)) before)))
    (let* ((dynamic (list (list :id "engine" :selector '(:kind engine-default :scope portable :engine-id "espeak")
                                :adjustments '(:average-pitch 0))))
           (result (emacsvox-aural-voice-editing--prefer-physical dynamic emacsvox-test--bulk-selector)))
      (should (= 2 (length result)))
      (should (equal (cdr result) dynamic)))))

(ert-deftest emacsvox-aural-voice-bulk-materializes-all-names-with-raw-definitions-and-owned-choices ()
  (emacsvox-test--with-bulk
    (let ((files (emacsvox-aural-voice-bulk--files))
          (source (emacsvox-aural-voice-drafts--palette-data 'reading-owned)))
      (emacsvox-test--bulk-open)
      (let* ((data (emacsvox-aural-voice-bulk--get :data))
             (palette (plist-get data :palette))
             (rows (plist-get data :rows)))
        (should (eq (plist-get (car rows) :name) 'default))
        (should (= (length rows) (length (emacsvox-aural-effective-voice-entries 'reading-owned))))
        (should (= (length rows) (length (plist-get palette :entries))))
        (should (eq (plist-get palette :parent) (plist-get source :parent)))
        (let ((style (plist-get (cdr (assq 'bolden (plist-get palette :entries))) :style)))
          (should (= (plist-get style :average-pitch) 0))
          (should (= (plist-get style :rate-offset) -4))
          (should (plist-member style :high-pass))
          (should-not (plist-get style :high-pass)))
        (dolist (row rows)
          (should (equal (plist-get (plist-get row :original) :definition)
                         (plist-get (plist-get row :proposed) :definition)))
          (should (equal (plist-get (car (plist-get (plist-get row :proposed) :choices)) :selector)
                         emacsvox-test--bulk-selector)))
        (dolist (set (plist-get data :choice-sets))
          (should (eq (plist-get set :palette) 'reading-owned)))
        (should (equal source (emacsvox-aural-voice-drafts--palette-data 'reading-owned)))
        (should (equal files (emacsvox-aural-voice-bulk--files)))))))

(ert-deftest emacsvox-aural-voice-bulk-native-copy-roundtrip-retains-per-choice-ownership ()
  (emacsvox-test--with-bulk
    (let* ((fixture emacsvox-test--native-choice-fixture)
           (palette (copy-tree (plist-get fixture :expected-palette)))
           (sets (copy-tree (plist-get (plist-get fixture :expected-routing) :choice-sets)))
           (rows (emacsvox-test--native-choices)))
      (emacsvox-aural-register-voice-palette-data palette)
      (setq emacsvox-aural-routing--choice-sets
            (emacsvox-aural-routing--merge-choice-sets emacsvox-aural-routing--choice-sets sets))
      (emacsvox-aural-voice-bulk--open 'reading 'native-copy (plist-get (car rows) :selector)
                                     "DECtalk Paul" (current-buffer))
      (emacsvox-aural-voice-bulk-collect)
      (let* ((saved (cl-find 'native-copy (plist-get (emacsvox-aural-read-user-data) :voice-palettes)
                             :key (lambda (data) (plist-get data :id))))
             (properties (cdr (assq 'bolden (plist-get saved :entries))))
             (reference (plist-get properties :local-choices))
             (snapshot (cl-find reference (plist-get (emacsvox-aural-read-routing-profiles) :choice-sets)
                                :test #'equal :key (lambda (set) (plist-get set :id)))))
        (should (= (plist-get saved :schema-version) 4))
        (should (eq (plist-get snapshot :palette) 'native-copy))
        (should (eq (plist-get snapshot :voice) 'bolden))
        (should (equal (plist-get snapshot :choices) rows))
        (should-not (equal reference "reading-bolden-after"))
        (should (eq (plist-get properties :personality) 'voice-bolden))))))

(ert-deftest emacsvox-aural-voice-bulk-copy-save-is-independent-and-repeat-is-unchanged ()
  (emacsvox-test--with-bulk
    (let ((original (emacsvox-aural-voice-drafts--palette-data 'reading-owned))
          (old-sets (copy-tree emacsvox-aural-routing--choice-sets)))
      (emacsvox-test--bulk-open t)
      (emacsvox-aural-voice-bulk-collect)
      (should-not callbacks)
      (should (eq (emacsvox-aural-effective-voice-palette) 'reading-owned))
      (let* ((copy (emacsvox-aural-voice-drafts--palette-data 'bulk-copy))
             (repeat (emacsvox-aural-voice-editing--bulk-physical
                      'bulk-copy 'bulk-copy emacsvox-test--bulk-selector "Ignored for an update")))
        (should (eq (plist-get copy :parent) 'acss-default))
        (should (equal copy (plist-get repeat :palette)))
        (should-not (plist-get repeat :choice-sets))
        (should (equal original (emacsvox-aural-voice-drafts--palette-data 'reading-owned)))
        (dolist (set old-sets) (should (member set emacsvox-aural-routing--choice-sets)))
        (emacsvox-test--set-palette-default 'reading-owned "different" 8)
        (should (equal (plist-get (car (plist-get (emacsvox-aural-voice-runtime--resolve 'default 'bulk-copy) :choices)) :selector)
                       emacsvox-test--bulk-selector))))))

(ert-deftest emacsvox-aural-voice-bulk-missing-local-reference-rejects-whole-operation ()
  (emacsvox-test--with-bulk
    (let ((emacsvox-aural-routing--choice-sets nil)
          (files (emacsvox-aural-voice-bulk--files)))
      (should-error (emacsvox-test--bulk-open) :type 'user-error)
      (should (= 0 (hash-table-count emacsvox-aural-voice-bulk--contexts)))
      (should (equal files (emacsvox-aural-voice-bulk--files))))))

(ert-deftest emacsvox-aural-voice-bulk-preview-and-cancel-write-nothing ()
  (emacsvox-test--with-bulk
    (let ((files (emacsvox-aural-voice-bulk--files)) entries)
      (emacsvox-test--bulk-open t)
      (should (eq (tabulated-list-get-id) 'default))
      (cl-letf (((symbol-function 'emacsvox-aural-voice-editor--submit-preview)
                 (lambda (requests callback current)
                   (should (funcall current))
                   (setq entries requests)
                   (funcall callback '(:status completed)) nil)))
        (call-interactively (key-binding (kbd "B"))))
      (let ((samples (cl-remove-if-not (lambda (entry) (eq (plist-get entry :role) 'sample)) entries)))
        (should (= (length samples) 2))
        (should (equal (plist-get (car samples) :text) (plist-get (cadr samples) :text)))
        (should (equal (plist-get (plist-get (car samples) :voice) :shared)
                       (plist-get (plist-get (cadr samples) :voice) :shared)))
        (should (equal (plist-get (car (plist-get (plist-get (cadr samples) :voice) :choices)) :selector)
                       emacsvox-test--bulk-selector)))
      (should-not (gethash 'bulk-copy emacsvox-aural-voice-palette-registry))
      (emacsvox-aural-voice-bulk-cancel)
      (should (= 0 (hash-table-count emacsvox-aural-voice-bulk--contexts)))
      (should (equal files (emacsvox-aural-voice-bulk--files))))))

(ert-deftest emacsvox-aural-voice-bulk-late-preview-cannot-replace-new-view-state ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let ((context emacsvox-aural-voice-editor--context) callback valid)
      (cl-letf (((symbol-function 'emacsvox-aural-voice-editor--submit-preview)
                 (lambda (_ receive current) (setq callback receive valid current) nil)))
        (emacsvox-aural-voice-bulk-play))
      (should (funcall valid))
      (emacsvox-aural-voice-bulk-stop)
      (should-not (funcall valid))
      (funcall callback '(:status completed))
      (should-not (plist-get context :preview-result))
      (cl-letf (((symbol-function 'emacsvox-aural-voice-editor--submit-preview)
                 (lambda (_ receive current) (setq callback receive valid current) nil)))
        (emacsvox-aural-voice-bulk-play))
      (kill-buffer (current-buffer))
      (should-not (funcall valid))
      (funcall callback '(:status completed))
      (should-not (plist-get context :preview-result)))))

(ert-deftest emacsvox-aural-voice-bulk-partial-write-retry-reuses-all-snapshot-identities ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let ((before (emacsvox-aural-read-user-data))
          (writer (symbol-function 'emacsvox-aural-routing--write-user-data))
          (draft (emacsvox-aural-voice-bulk--get :draft))
          (writes 0))
      (cl-letf (((symbol-function 'emacsvox-aural-routing--write-user-data)
                 (lambda (&rest args) (cl-incf writes) (apply writer args))))
        (cl-letf (((symbol-function 'emacsvox-aural--write-user-data)
                   (lambda (&rest _) (error "Injected second-store failure"))))
          (emacsvox-aural-voice-bulk-collect))
        (let ((proposal (emacsvox-aural-voice-draft-proposal draft)))
          (should (eq (emacsvox-aural-voice-save-state proposal) 'partial))
          (should (equal before (emacsvox-aural-read-user-data)))
          (should-error (emacsvox-aural-voice-bulk-cancel) :type 'user-error)
          (emacsvox-aural-voice-bulk-collect)
          (should (= writes 1))
          (should (eq (emacsvox-aural-voice-save-state proposal) 'saved))
          (should (eq proposal (emacsvox-aural-voice-draft-proposal draft)))
          (should (= (length (plist-get (emacsvox-aural-voice-drafts--palette-data 'reading-owned) :entries))
                     (length (emacsvox-aural-voice-bulk--get :rows)))))))))

(ert-deftest emacsvox-aural-voice-bulk-apply-failure-retry-and-new-selection-preserve-saved-data ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open t)
    (emacsvox-aural-voice-bulk-save)
    (let* ((draft (emacsvox-aural-voice-bulk--get :draft))
           (proposal (emacsvox-aural-voice-draft-proposal draft))
           (files (emacsvox-aural-voice-bulk--files))
           (old-callback (car callbacks)))
      (should (eq (emacsvox-aural-effective-voice-palette) 'bulk-copy))
      (funcall old-callback '(:status failed :processes ((:role speaker :status applied)
                                                       (:role notification :phase timeout))))
      (should (eq (emacsvox-aural-voice-save-state proposal) 'apply-failed))
      (emacsvox-aural-voice-bulk-save)
      (should (= (length callbacks) 2))
      (funcall old-callback '(:status applied))
      (should (eq (emacsvox-aural-voice-save-state proposal) 'applying))
      (funcall (car callbacks) '(:status failed))
      (emacsvox-aural-select-voice-palette 'alternative-owned)
      (let ((count (length callbacks)))
        (emacsvox-aural-voice-bulk-save)
        (should (= (length callbacks) count)))
      (should (eq (emacsvox-aural-effective-voice-palette) 'alternative-owned))
      (should (equal files (emacsvox-aural-voice-bulk--files))))))

(ert-deftest emacsvox-aural-voice-bulk-initial-conflict-has-a-resolvable-review ()
  (emacsvox-test--with-bulk
    (let* ((editor (emacsvox-aural-voice-editor--context-for 'reading-owned 'default))
           (draft (plist-get editor :draft)))
      (emacsvox-aural-voice-drafts--edit draft '(:pending t))
      (emacsvox-test--bulk-open)
      (should (emacsvox-aural-voice-bulk--get :blocked))
      (should-not (emacsvox-aural-voice-bulk--get :data))
      (should-error (emacsvox-aural-voice-bulk-collect) :type 'user-error)
      (should (eq (key-binding (kbd "r")) 'emacsvox-aural-voice-bulk-resolve))
      (emacsvox-aural-voice-drafts--discard draft)
      (emacsvox-aural-voice-bulk-refresh)
      (should-not (emacsvox-aural-voice-bulk--get :blocked))
      (should (eq (tabulated-list-get-id) 'default)))))

(ert-deftest emacsvox-aural-voice-bulk-saved-review-can-close-or-start-a-new-edit ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let ((old emacsvox-aural-voice-editor--context))
      (emacsvox-aural-voice-bulk-collect)
      (emacsvox-test--bulk-open)
      (should-not (eq old emacsvox-aural-voice-editor--context))
      (let* ((new emacsvox-aural-voice-editor--context)
             (draft (plist-get new :draft))
             (key (emacsvox-aural-voice-draft-key draft)))
        (with-current-buffer (plist-get old :buffer)
          (emacsvox-aural-voice-bulk-close-result))
        (should (eq new (gethash key emacsvox-aural-voice-bulk--contexts)))
        (should (eq draft (gethash key emacsvox-aural-voice-drafts--registry)))
        (set-buffer (plist-get new :buffer))))
    (emacsvox-aural-voice-bulk-collect)
    (let ((files (emacsvox-aural-voice-bulk--files)))
      (emacsvox-aural-voice-bulk-close-result)
      (should (= 0 (hash-table-count emacsvox-aural-voice-bulk--contexts)))
      (should (equal files (emacsvox-aural-voice-bulk--files))))))

(ert-deftest emacsvox-aural-voice-bulk-dirty-editor-during-review-is-preserved ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let* ((review (current-buffer))
           (files (emacsvox-aural-voice-bulk--files))
           (editor (emacsvox-aural-voice-editor--context-for 'reading-owned 'default))
           (draft (plist-get editor :draft)))
      (emacsvox-aural-voice-drafts--edit draft '(:unsaved "keep me"))
      (should-error (emacsvox-aural-voice-bulk-save) :type 'user-error)
      (should (equal '(:unsaved "keep me") (emacsvox-aural-voice-draft-working draft)))
      (should (equal files (emacsvox-aural-voice-bulk--files)))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_ choices &rest _) (caar choices))))
        (emacsvox-aural-voice-bulk-resolve))
      (should (derived-mode-p 'emacsvox-aural-voice-editor-mode))
      (emacsvox-aural-voice-drafts--discard draft)
      (set-buffer review)
      (emacsvox-aural-voice-bulk-collect)
      (should (equal (plist-get (car (plist-get (emacsvox-aural-voice-draft-working draft) :choices)) :selector)
                     emacsvox-test--bulk-selector)))))

(ert-deftest emacsvox-aural-voice-bulk-checks-complete-local-inputs-and-file-drift ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let ((sets (copy-tree emacsvox-aural-routing--choice-sets))
          (files (emacsvox-aural-voice-bulk--files)))
      (setf (plist-get (car (plist-get (car emacsvox-aural-routing--choice-sets) :choices)) :adjustments)
            '(:average-pitch 1))
      (should-error (emacsvox-aural-voice-bulk-collect) :type 'emacsvox-aural-voice-draft-conflict)
      (should (equal files (emacsvox-aural-voice-bulk--files)))
      (setq emacsvox-aural-routing--choice-sets sets)
      (with-temp-buffer (insert "; changed outside the editor\n")
                        (write-region (point-min) (point-max) emacsvox-aural-schemes-file t 'silent))
      (should-error (emacsvox-aural-voice-bulk-collect) :type 'user-error)
      (emacsvox-aural-voice-bulk-refresh)
      (emacsvox-aural-voice-bulk-collect)
      (should-not callbacks))))

(ert-deftest emacsvox-aural-voice-bulk-checks-conflicts-between-store-writes ()
  (emacsvox-test--with-bulk
    (emacsvox-test--bulk-open)
    (let* ((writer (symbol-function 'emacsvox-aural-routing--write-user-data))
           (before (emacsvox-aural-read-user-data))
           (draft (emacsvox-aural-voice-bulk--get :draft)))
      (cl-letf (((symbol-function 'emacsvox-aural-routing--write-user-data)
                 (lambda (&rest args)
                   (apply writer args)
                   (let ((other (emacsvox-aural-voice-drafts--open '(base reading-owned indent) '(:pitch 0))))
                     (emacsvox-aural-voice-drafts--edit other '(:pitch 8))))))
        (emacsvox-aural-voice-bulk-collect))
      (should (eq (emacsvox-aural-voice-save-state (emacsvox-aural-voice-draft-proposal draft)) 'partial))
      (should (equal before (emacsvox-aural-read-user-data))))))

(ert-deftest emacsvox-aural-voice-bulk-graphical-browser-review-cancel-and-save ()
  (skip-unless (display-graphic-p))
  (emacsvox-test--with-bulk
    (let* ((inventory (omnivox-espeak-variants-tests--inventory))
           (origin (generate-new-buffer " *Bulk browser test*"))
           (files (emacsvox-aural-voice-bulk--files))
           (answers '("Create a new personal palette" "reading-owned")))
      (unwind-protect
          (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory))
                    ((symbol-function 'completing-read) (lambda (&rest _) (pop answers)))
                    ((symbol-function 'emacsvox-aural-voice-palettes--read-new-id) (lambda (&rest _) 'bulk-copy)))
            (switch-to-buffer origin)
            (omnivox-espeak-variants-mode)
            (omnivox-espeak-variants--render)
            (goto-char (point-min))
            (let ((variant (tabulated-list-get-id)))
              (call-interactively (key-binding (kbd "V")))
              (should (eq (window-buffer (selected-window)) (current-buffer)))
              (should (eq (tabulated-list-get-id) 'default))
              (redisplay t)
              (should (pos-visible-in-window-p (point)))
              (let ((rows (emacsvox-aural-voice-bulk--get :rows)))
                (should (eq (key-binding (kbd "<down>")) 'emacsvox-aural-ui-next-row))
                (call-interactively (key-binding (kbd "<down>")))
                (should (eq (tabulated-list-get-id) (plist-get (cadr rows) :name))))
              (call-interactively (key-binding (kbd "B")))
              (should requests)
              (call-interactively (key-binding (kbd "C-c C-k")))
              (should (eq (current-buffer) origin))
              (should (equal (tabulated-list-get-id) variant)))
            (should (equal files (emacsvox-aural-voice-bulk--files)))
            ;; Exercise the physical browser's actual key and personal-update path.
            (emacsvox-aural-voice-workbench-mode)
            (setq emacsvox-aural-voice-workbench-view 'physical
                  emacsvox-aural-voice-workbench-inventory inventory)
            (emacsvox-aural-voice-workbench-refresh)
            (emacsvox-aural-ui-goto-row '("espeak" "espeak:gmw/en-US"))
            (setq answers '("Update an existing personal palette" "reading-owned"))
            (call-interactively (key-binding (kbd "V")))
            (should (derived-mode-p 'emacsvox-aural-voice-bulk-mode))
            (should (eq (window-buffer (selected-window)) (current-buffer)))
            (call-interactively (key-binding (kbd "c")))
            (should (equal (plist-get (car (plist-get (emacsvox-aural-voice-runtime--resolve 'default 'reading-owned) :choices)) :selector)
                           '(:kind exact :scope local :engine-id "espeak" :voice-id "espeak:gmw/en-US"))))
        (when (buffer-live-p origin) (kill-buffer origin))))))

(provide 'emacsvox-aural-voice-bulk-tests)
;;; emacsvox-aural-voice-bulk-tests.el ends here
