;;; emacsvox-welcome-tests.el --- Welcome behavior -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
(require 'ert)
(require 'cl-lib)
(require 'emacsvox-welcome)

(ert-deftest emacsvox-welcome-preference-is-profile-local ()
  (let* ((user-emacs-directory (make-temp-file "welcome-profile-" t))
         (emacsvox-welcome-show-at-startup t))
    (unwind-protect
        (cl-letf (((symbol-function 'tts-speak) #'ignore))
          (with-temp-buffer
            (emacsvox-welcome-mode)
            (should (emacsvox-welcome--enabled-p))
            (emacsvox-welcome-toggle-startup)
            (should-not (emacsvox-welcome--enabled-p))
            (let ((user-emacs-directory (expand-file-name "other/" user-emacs-directory)))
              (should (emacsvox-welcome--enabled-p)))
            (emacsvox-welcome-toggle-startup)
            (should (emacsvox-welcome--enabled-p))))
      (delete-directory user-emacs-directory t))))

(ert-deftest emacsvox-welcome-does-not-evaluate-preference ()
  (let* ((user-emacs-directory (make-temp-file "welcome-profile-" t))
         (emacsvox-welcome-show-at-startup nil))
    (unwind-protect
        (progn
          (with-temp-file (emacsvox-welcome--preference-file)
            (insert "(error \"Do not evaluate me\")"))
          (should-not (emacsvox-welcome--enabled-p)))
      (delete-directory user-emacs-directory t))))

(ert-deftest emacsvox-welcome-waits-for-readiness-and-startup ()
  (let ((emacsvox-welcome--offered nil)
        (emacsvox-welcome--startup-finished nil)
        (emacsvox-welcome--ready nil))
    (emacsvox-welcome--maybe-show)
    (should-not emacsvox-welcome--offered)
    (setq emacsvox-welcome--ready t)
    (emacsvox-welcome--maybe-show)
    (should-not emacsvox-welcome--offered)))

(ert-deftest emacsvox-welcome-preserves-files-and-user-activity ()
  (dolist (reason '(file input minibuffer none))
    (let ((emacsvox-welcome--offered nil)
          (emacsvox-welcome--startup-finished t)
          (emacsvox-welcome--ready t)
          (emacsvox-welcome--initial-input num-input-keys)
          (noninteractive nil) shown
          (process-environment (copy-sequence process-environment)))
      (setenv "EMACSVOX_NATIVE_RESULT" nil)
      (cl-letf (((symbol-function 'emacsvox-welcome--enabled-p) (lambda () t))
                ((symbol-function 'buffer-name) (lambda (&rest _) "*scratch*"))
                ((symbol-function 'buffer-modified-p) (lambda (&rest _) nil))
                ((symbol-function 'buffer-file-name) (lambda (&rest _) (eq reason 'file)))
                ((symbol-function 'active-minibuffer-window) (lambda () (eq reason 'minibuffer)))
                ((symbol-function 'emacsvox-welcome) (lambda () (setq shown t))))
        (when (eq reason 'input) (setq emacsvox-welcome--initial-input -1))
        (emacsvox-welcome--maybe-show)
        (should (eq (not (null shown)) (eq reason 'none)))
        (setq shown nil)
        (emacsvox-welcome--maybe-show)
        (should-not shown)))))

(ert-deftest emacsvox-welcome-keyboard-actions-are-distinct ()
  (let (calls spoken)
    (cl-letf (((symbol-function 'tts-speak) (lambda (text) (push text spoken)))
              ((symbol-function 'tts-set-rate) (lambda () (interactive) (push 'rate calls)))
              ((symbol-function 'emacsvox-welcome-output) (lambda () (interactive) (push 'output calls))))
      (with-temp-buffer
        (emacsvox-welcome-mode)
        (emacsvox-welcome--render)
        (emacsvox-welcome-next)
        (should (equal (car spoken) "Test speech"))
        (emacsvox-welcome-next)
        (push-button)
        (emacsvox-welcome-next)
        (push-button)
        (should (equal calls '(output rate)))
        (emacsvox-welcome-previous)
        (should (equal (car spoken) "Adjust speech rate"))))))

(provide 'emacsvox-welcome-tests)
