;;; emacsvox-dired-tests.el --- Dired advice migration tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused coverage for the native advice generated by emacsvox-dired.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'emacsvox-preamble)
(require 'emacsvox-aural-tools)

(defconst emacsvox-test--dired-advice-targets
  '(dired ido-dired dired-jump dired-other-window dired-other-frame
    dired-next-subdir dired-prev-subdir
    dired-tree-up dired-tree-down dired-up-directory
    dired-next-marked-file dired-prev-marked-file
    dired-next-dirline dired-prev-dirline
    dired-next-line dired-previous-line
    dired-unmark-backward dired-maybe-insert-subdir
    locate locate-with-filter)
  "Dired and Locate commands converted to native advice in this slice.")

(defconst emacsvox-test--dired-handwritten-advice
  '((dired-sort-toggle-or-edit
     :around emacsvox--advice-dired-sort-toggle-or-edit-around)
    (dired-query :before emacsvox--advice-dired-query-before)
    (dired-find-file :around emacsvox--advice-dired-find-file-around)
    (dired-mark :around emacsvox--advice-dired-mark-around)
    (dired-flag-file-deletion
     :around emacsvox--advice-dired-flag-file-deletion-around)
    (dired-unmark :around emacsvox--advice-dired-unmark-around)
    (quit-window :around emacsvox--advice-dired-quit-window-around))
  "Remaining hand-written Dired advice migrated to final native form.")

(let ((module
       (expand-file-name
        "../lisp/emacsvox-dired.el"
        (file-name-directory (or load-file-name buffer-file-name)))))
  (load module nil nil))

(defun emacsvox-test--dired-advice-function (target)
  "Return the native Emacsvox Dired advice function for TARGET."
  (intern (format "emacsvox--dired-%s-after" target)))

(ert-deftest emacsvox-dired-converted-advice-is-directly-registered ()
  "Every converted Dired advice uses native advice directly."
  (dolist (target emacsvox-test--dired-advice-targets)
    (let ((function (emacsvox-test--dired-advice-function target)))
      (should (fboundp function))
      (should (advice-member-p function target)))))

(defun emacsvox-test--dired-feedback (target)
  "Call TARGET's migrated advice and return its semantic feedback events."
  (let ((ems--interactive-fn-name target)
        events)
    (cl-letf (((symbol-function 'emacsvox-dired-initialize)
               (lambda () (push 'initialize events)))
              ((symbol-function 'emacsvox-icon)
               (lambda (icon) (push (list 'icon icon) events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'speak-mode-line events)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (push 'speak-dired-line events)))
              ((symbol-function 'emacsvox-speak-line)
               (lambda () (push 'speak-line events))))
      (funcall (emacsvox-test--dired-advice-function target)))
    (nreverse events)))

(ert-deftest emacsvox-dired-converted-advice-preserves-feedback-order ()
  "Representative commands retain their interactive speech and icons."
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired)
    '(initialize (icon open-object) speak-mode-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-prev-subdir)
    '((icon large-movement) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'dired-next-line)
    '((icon select-object) speak-dired-line)))
  (should
   (equal
    (emacsvox-test--dired-feedback 'locate)
    '(speak-line (icon open-object)))))

(ert-deftest emacsvox-dired-training-follows-earcon-and-filename ()
  "Training identifies the movement cue after normal Dired feedback."
  (let ((this-command 'dired-next-line)
        (real-this-command 'dired-next-line)
        (post-command-hook nil)
        (tts-speaker-process 'speaker)
        (emacsvox-use-icons t)
        (emacsvox-aural-plan-presented-hook nil)
        (emacsvox-aural-training-mode nil)
        (emacsvox-aural-training-voice 'annotate)
        (emacsvox-aural-tools--pending-training-explanations nil)
        events)
    (cl-letf
         (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (focus-entered) :states (marked))))
         ((symbol-function 'process-live-p) (lambda (_) t))
         ((symbol-function 'emacsvox-sounds-play-concrete-cue)
          (lambda (&rest _) (push 'earcon events)))
         ((symbol-function 'emacsvox-aural-compile-voice)
          (lambda (voice)
            (should (eq voice 'annotate))
            "TRAINING"))
         ((symbol-function 'tts-voice-reset-code) (lambda () "RESET"))
         ((symbol-function 'tts--protocol-queue-code)
          (lambda (code) (push (list 'code code) events)))
         ((symbol-function 'tts--protocol-queue-text)
          (lambda (text) (push (list 'text text) events)))
         ((symbol-function 'tts--protocol-dispatch)
          (lambda () (push 'dispatch events))))
      (unwind-protect
          (progn
            (emacsvox-aural-training-mode 1)
            (emacsvox-dired-present-current
             'select-object 'navigation 'focus-entered
             (lambda () (push 'filename events)))
            (should
             (equal
              (nreverse (copy-sequence events))
              '(earcon dispatch filename)))
            (run-hooks 'post-command-hook))
        (emacsvox-aural-training-mode -1)))
    (should
     (equal
      (nreverse events)
      '(earcon
        dispatch
        filename
        (code "RESET")
        (code "TRAINING")
        (text
         "filesystem entry, focus entered, marked, entry kind file, earcon mark object, navigation occasion.")
        (code "RESET")
        dispatch)))))

(ert-deftest emacsvox-dired-converted-advice-ignores-noninteractive-calls ()
  "Migrated feedback remains restricted to interactive commands."
  (let ((ems--interactive-fn-name nil)
        called)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (&rest _) (setq called t)))
              ((symbol-function 'emacsvox-dired-speak-line)
               (lambda () (setq called t))))
      (emacsvox--dired-dired-next-line-after))
    (should-not called)))

(ert-deftest emacsvox-dired-handwritten-advice-is-directly-registered ()
  "Hand-written Dired advice uses native advice directly."
  (dolist (entry emacsvox-test--dired-handwritten-advice)
    (pcase-let ((`(,target ,where ,function) entry))
      (should (fboundp target))
      (should (fboundp function))
      (should (advice-member-p function target))))
  (should-not (fboundp 'dired-quit))
  (should (eq (lookup-key dired-mode-map "q") 'quit-window)))

(ert-deftest emacsvox-dired-sort-calls-original-once ()
  "Interactive sorting runs once with messages silenced before feedback."
  (let ((ems--interactive-fn-name 'dired-sort-toggle-or-edit)
        (calls 0)
        events)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (icon) (push (list 'icon icon) events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'mode-line events))))
      (should
       (eq
        'result
        (emacsvox--advice-dired-sort-toggle-or-edit-around
         (lambda (&rest arguments)
           (setq calls (1+ calls))
           (push
            (list 'original arguments
                  emacsvox-speak-messages inhibit-message)
            events)
           'result)
         3))))
    (should (= calls 1))
    (should
     (equal
      (nreverse events)
      '((original (3) nil t) (icon task-done) mode-line)))))

(ert-deftest emacsvox-dired-programmatic-sort-runs-once-quietly ()
  "Programmatic sorting runs once without Dired-specific feedback."
  (let ((calls 0)
        events)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (&rest arguments) (push arguments events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'mode-line events))))
      (should
       (eq
        'result
        (emacsvox--advice-dired-sort-toggle-or-edit-around
         (lambda (&rest arguments)
           (setq calls (1+ calls))
           (should (equal arguments '(2)))
           'result)
         2))))
    (should (= calls 1))
    (should-not events)))

(ert-deftest emacsvox-dired-find-file-inspects-before-one-call ()
  "File opening detects a directory before calling the original once."
  (let ((ems--interactive-fn-name 'dired-find-file)
        (calls 0)
        events)
    (cl-letf (((symbol-function 'dired-get-filename)
               (lambda (&rest arguments)
                 (push (list 'filename arguments) events)
                 "/tmp/directory"))
              ((symbol-function 'file-directory-p)
               (lambda (filename)
                 (push (list 'directory filename) events)
                 t))
              ((symbol-function 'emacsvox-dired-label-fields)
               (lambda () (push 'label events)))
              ((symbol-function 'emacsvox-speak-mode-line)
               (lambda () (push 'mode-line events)))
              ((symbol-function 'emacsvox-icon)
               (lambda (icon) (push (list 'icon icon) events))))
      (should
       (eq
        'result
        (emacsvox--advice-dired-find-file-around
         (lambda ()
           (setq calls (1+ calls))
           (push 'original events)
           'result)))))
    (should (= calls 1))
    (should
     (equal
      (nreverse events)
      '((filename (t t))
        (directory "/tmp/directory")
        (filename (nil t))
        (directory "/tmp/directory")
        original label mode-line (icon open-object))))))

(ert-deftest emacsvox-dired-entry-facts-describe-kind-and-marker ()
  "Dired exposes filesystem kind, mark state, and operation event."
  (let ((directory (make-temp-file "emacsvox-dired-facts-" t)))
    (unwind-protect
        (with-temp-buffer
          (insert "* entry")
          (goto-char (point-min))
          (cl-letf (((symbol-function 'dired-get-filename)
                     (lambda (&rest _) directory)))
            (should
             (equal
              (emacsvox-dired-entry-facts 'entry-marked)
              '(:role filesystem-entry
                :entry-kind directory
                :events (entry-marked)
                :states (marked))))))
      (delete-directory directory t))))

(ert-deftest emacsvox-dired-marked-files-have-distinct-voice ()
  "The whole marked filename, not only its marker, has a distinct voice."
  (should
   (eq
    (voice-setup-get-voice-for-face 'dired-marked)
    'voice-lighten))
  (with-temp-buffer
    (insert (propertize "marked.txt" 'face 'dired-marked))
    (goto-char (point-min))
    (should (eq (tts-get-style) 'voice-lighten))))

(ert-deftest emacsvox-dired-marked-navigation-uses-mark-earcon ()
  "Entering a marked row replaces the generic selection cue."
  (let ((emacsvox-aural-active-scheme 'default)
        (emacsvox-aural-enabled-feature-fragments nil)
        (emacsvox-aural-user-rules nil)
        (emacsvox-aural-session-rules nil)
        (emacsvox-aural-buffer-rules nil)
        (context (emacsvox-aural-capture-context 'dired 'navigation))
        plan)
    (setq
     plan
     (emacsvox-aural-resolve-legacy-icon
      'select-object context
      '(:role filesystem-entry :entry-kind file
        :events (focus-entered) :states (marked))))
    (should
     (equal
      (mapcar
       #'emacsvox-aural-action-cue
       (emacsvox-aural-render-plan-before plan))
      '(mark-object)))))

(ert-deftest emacsvox-dired-feedback-shares-semantic-context ()
  "The legacy cue and filename speech see one frozen Dired submission."
  (let (events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-entry-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (focus-entered))))
         ((symbol-function 'emacsvox-icon)
          (lambda (icon)
            (push
             (list icon emacsvox-aural-submission-facts
                   (plist-get emacsvox-aural-submission-context :module)
                   emacsvox-aural-submission-occasion)
             events)))
         ((symbol-function 'emacsvox-dired-speak-line)
          (lambda ()
            (push
             (list 'line emacsvox-aural-submission-facts)
             events))))
      (emacsvox-dired-present-current
       'select-object 'navigation 'focus-entered))
    (should
     (equal
      (nreverse events)
      '((select-object
         (:role filesystem-entry :entry-kind file
          :events (focus-entered))
         dired navigation)
        (line
         (:role filesystem-entry :entry-kind file
          :events (focus-entered))))))))

(ert-deftest emacsvox-dired-marking-feedback-is-target-aware ()
  "Only the matching command emits action cue then next-row speech."
  (let ((ems--interactive-fn-name 'dired-flag-file-deletion)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-action-facts)
          (lambda (&rest _) '(:role filesystem-entry)))
         ((symbol-function 'emacsvox-icon)
          (lambda (icon) (push (list 'icon icon) events)))
         ((symbol-function 'emacsvox-dired-present-current)
          (lambda (&rest _) (push 'line events))))
      (emacsvox--advice-dired-mark-around
       (lambda () (push 'mark events)))
      (emacsvox--advice-dired-flag-file-deletion-around
       (lambda () (push 'original events)))
      (emacsvox--advice-dired-unmark-around
       (lambda () (push 'unmark events))))
    (should
     (equal
      (nreverse events)
      '(mark original line (icon delete-object) unmark)))))

(ert-deftest emacsvox-dired-marking-freezes-the-action-target ()
  "The action cue keeps pre-command facts while next-row speech is navigation."
  (let ((ems--interactive-fn-name 'dired-mark)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-dired-action-facts)
          (lambda (&rest _)
            '(:role filesystem-entry :entry-kind file
              :events (entry-marked) :states (marked))))
         ((symbol-function 'emacsvox-icon)
          (lambda (_)
            (push
             (list 'action emacsvox-aural-submission-facts)
             events)))
         ((symbol-function 'emacsvox-dired-present-current)
          (lambda (&rest _)
            (push 'next-row events))))
      (emacsvox--advice-dired-mark-around
       (lambda () (push 'original events) 'result)))
    (should
     (equal
      (nreverse events)
      '(original
        next-row
        (action
         (:role filesystem-entry :entry-kind file
          :events (entry-marked) :states (marked))))))))

(ert-deftest emacsvox-dired-interactive-mark-actions-confirm-after-navigation ()
  "Real interactive mark and unmark commands leave their cues audible."
  (let* ((directory (make-temp-file "emacsvox-dired-actions-" t))
         (first (expand-file-name "first.txt" directory))
         (second (expand-file-name "second.txt" directory))
         buffer
         events)
    (unwind-protect
        (progn
          (write-region "first" nil first nil 'silent)
          (write-region "second" nil second nil 'silent)
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf
                (((symbol-function 'emacsvox-dired-present-current)
                  (lambda (&rest _) (push 'next-row events)))
                 ((symbol-function 'emacsvox-icon)
                  (lambda (icon) (push (list 'icon icon) events))))
              (dired-goto-file first)
              (funcall-interactively #'dired-mark nil t)
              (dired-goto-file first)
              (funcall-interactively #'dired-unmark nil t))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))
    (should
     (equal
      (nreverse events)
      '(next-row
        (icon mark-object)
        next-row
        (icon deselect-object))))))

(ert-deftest emacsvox-dired-quit-feedback-is-mode-scoped ()
  "Only an interactive quit originating in Dired gets Dired feedback."
  (let ((ems--interactive-fn-name 'quit-window)
        (calls 0)
        events)
    (cl-letf
        (((symbol-function 'emacsvox-icon)
          (lambda (icon)
            (push
             (list
              'icon icon emacsvox-aural-submission-facts
              (plist-get emacsvox-aural-submission-context :module))
             events)))
         ((symbol-function 'emacsvox-speak-mode-line)
          (lambda () (push 'mode-line events))))
      (with-temp-buffer
        (setq major-mode 'dired-mode)
        (should
         (eq
          'dismissed
          (emacsvox--advice-dired-quit-window-around
           (lambda ()
             (setq calls (1+ calls))
             (setq major-mode 'fundamental-mode)
             'dismissed)))))
      (setq ems--interactive-fn-name 'quit-window)
      (with-temp-buffer
        (should
         (eq
          'ordinary
          (emacsvox--advice-dired-quit-window-around
           (lambda ()
             (setq calls (1+ calls))
             'ordinary))))))
    (should (eq ems--interactive-fn-name 'quit-window))
    (should (= calls 2))
    (should
     (equal
      (nreverse events)
      '((icon close-object
         (:role filesystem-listing
          :events (filesystem-listing-closed))
         dired)
        mode-line)))))

(ert-deftest emacsvox-dired-query-cue-remains-unconditional ()
  "Dired queries always cue before deciding whether prompting is needed."
  (let (events)
    (cl-letf (((symbol-function 'emacsvox-icon)
               (lambda (icon) (push icon events))))
      (emacsvox--advice-dired-query-before))
    (should (equal events '(ask-short-question)))))

(provide 'emacsvox-dired-tests)
;;; emacsvox-dired-tests.el ends here
