;;; emacsvox-table-reader-tests.el --- Logical table reading tests -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later

;;; Code:
(require 'ert)
(require 'cl-lib)
(require 'package)
(package-initialize)
(require 'markdown-mode)
(let* ((kind (or (getenv "EMACSVOX_TABLE_READER_TEST_LOAD") "source"))
       (suffix (pcase kind ("source" ".el") ("compiled" ".elc")
                       (_ (error "Unknown table reader test load kind: %s" kind))))
       (directory (expand-file-name "../lisp/"
                                    (file-name-directory
                                     (or load-file-name buffer-file-name)))))
  (dolist (entry '(("emacsvox-table-reader" . emacsvox-table-reader-mode)
                   ("emacsvox-markdown" . emacsvox-markdown--table-snapshot)
                   ("emacsvox-org" . emacsvox-org--table-snapshot)))
    (let ((file (expand-file-name (concat (car entry) suffix) directory)))
      (load file nil nil t)
      (unless (equal (file-truename file)
                     (file-truename (symbol-file (cdr entry) 'defun)))
        (error "Table tests loaded the wrong implementation: %s" file)))))

(defmacro emacsvox-table-reader-test--with-table (mode text &rest body)
  "Run BODY in MODE with TEXT, capturing native submissions in `spoken'."
  (declare (indent 2) (debug t))
  `(with-temp-buffer
     (delay-mode-hooks (funcall ,mode))
     (insert ,text)
     (goto-char (point-min))
     (search-forward "Name")
     (set-buffer-modified-p nil)
     (let ((emacsvox-table-reader-titles '(column))
           (emacsvox-table-reader-data-position 'first)
           (kill-ring nil) (kill-ring-yank-pointer nil) spoken)
       (cl-letf (((symbol-function 'emacsvox-aural-submit)
                  (lambda (text &rest args) (push (cons text args) spoken))))
         ,@body))))

(defconst emacsvox-table-reader-test--markdown
  "Before\n\n| Name | Role |\n|---|---|\n| Alice | Engineer |\n| Bob | |\n\nAfter\n")
(defconst emacsvox-table-reader-test--org
  "Before\n\n| Name | Role |\n|------+------|\n| Alice | Engineer |\n| Bob | |\n\nAfter\n")

(ert-deftest emacsvox-table-reader-equivalent-source-navigation ()
  "Both adapters preserve text, columns, complete rows and native Aural roles."
  (dolist (case `((markdown-mode ,emacsvox-table-reader-test--markdown markdown markdown-table-row)
                  (org-mode ,emacsvox-table-reader-test--org org org-table)))
    (emacsvox-table-reader-test--with-table (car case) (cadr case)
      (let ((source (buffer-string)))
        (emacsvox-table-reader-mode 1)
        (should emacsvox-table-reader-mode)
        (should (equal (caar spoken) "Table reading. Table, 2 data rows, 2 columns. Name."))
        (emacsvox-table-reader-next-column)
        (should (looking-at "Role"))
        (emacsvox-table-reader-next-row)
        (should (looking-at "Engineer"))
        (should (equal (caar spoken) "Alice, Name. Engineer, Role."))
        (should (eq (plist-get (cdar spoken) :occasion) 'navigation))
        (should (eq (plist-get (cdar spoken) :module) (nth 2 case)))
        (should (eq (plist-get (plist-get (cdar spoken) :facts) :role) (nth 3 case)))
        (emacsvox-table-reader-speak-context)
        (should (equal (caar spoken) "Data row 1 of 2, column 2 of 2."))
        (emacsvox-table-reader-next-row)
        (should (equal (caar spoken) "Bob, Name. blank, Role."))
        (should (= (plist-get (emacsvox-table-reader--cell) :column-index) 1))
        (emacsvox-table-reader-previous-row 2)
        (should (looking-at "Role"))
        (emacsvox-table-reader-next-row -1)
        (should (looking-at "Before"))
        (should-not emacsvox-table-reader-mode)
        (should (equal (caar spoken) "Before table. Before"))
        (should (= (length spoken) 7))
        (should (equal (buffer-string) source))
        (should-not (buffer-modified-p))))))

(ert-deftest emacsvox-table-reader-keys-are-explicit-and-editing-restores ()
  "Letters, Org row edits and native TAB/RET are restored when reading ends."
  (dolist (case `((markdown-mode ,emacsvox-table-reader-test--markdown)
                  (org-mode ,emacsvox-table-reader-test--org)))
    (emacsvox-table-reader-test--with-table (car case) (cadr case)
      (let* ((keys '("r" "c" "t" "k" "SPC" "TAB" "RET" "M-<up>"))
             (bindings (mapcar (lambda (key) (key-binding (kbd key))) keys)))
        (should (memq (key-binding "r") '(self-insert-command org-self-insert-command)))
        (emacsvox-table-reader-mode 1)
        (should (eq (key-binding "r") 'emacsvox-table-reader-speak-row))
        (should (eq (key-binding (kbd "TAB")) 'emacsvox-table-reader-next-column))
        (should (eq (key-binding (kbd "RET")) 'emacsvox-table-reader-speak-cell))
        (should (eq (key-binding (kbd "M-<up>")) 'emacsvox-table-reader-exit-backward))
        (should (eq (key-binding (kbd "k r")) 'emacsvox-table-reader-copy-row))
        (call-interactively (key-binding (kbd "TAB")))
        (call-interactively (key-binding (kbd "RET")))
        (should-not (buffer-modified-p))
        (emacsvox-table-reader-mode -1)
        (should (equal bindings (mapcar (lambda (key) (key-binding (kbd key))) keys))))
      (emacsvox-table-reader-mode 1)
      (insert "Edited ")
      (should-not emacsvox-table-reader-mode)
      (should (memq (key-binding "r") '(self-insert-command org-self-insert-command)))
      (emacsvox-table-reader-mode 1)
      (should (string-match-p "Edited" (caar spoken)))
      (goto-char (point-max))
      (emacsvox-table-reader--post-command)
      (should-not emacsvox-table-reader-mode)
      (should (equal (caar spoken) "Table reading off.")))))

(ert-deftest emacsvox-table-reader-rejects-prose-and-code ()
  "Explicit entry fails without activating keys in prose or code examples."
  (dolist (case '((markdown-mode "Name prose | still prose\n" "Name")
                  (markdown-mode "```text\n| Name | Role |\n|---|---|\n```\n" "Name")
                  (markdown-mode "    | Name | Role |\n    |---|---|\n" "Name")
                  (org-mode "#+begin_src text\n| Name | Role |\n|---+---|\n#+end_src\n" "Name")
                  (org-mode "#+begin_example\n| Name | Role |\n#+end_example\n" "Name")))
    (emacsvox-table-reader-test--with-table (car case) (cadr case)
      (should-error (emacsvox-table-reader-mode 1) :type 'user-error)
      (should-not emacsvox-table-reader-mode)
      (should (memq (key-binding "r") '(self-insert-command org-self-insert-command)))
      (should-not spoken))))

(ert-deftest emacsvox-table-reader-blank-ragged-headerless-and-boundaries ()
  "Ragged rows keep the column and separators never become data."
  (dolist (mode '(markdown-mode org-mode))
    (emacsvox-table-reader-test--with-table mode
        "| Name | Role | Notes |\n| Alice | Engineer | Long |\n| Bob | Short |\n"
      (emacsvox-table-reader-mode 1)
      (emacsvox-table-reader-next-row)
      (emacsvox-table-reader-next-column 2)
      (let ((origin (point)))
        (emacsvox-table-reader-next-row)
        (should (= origin (point)))
        (should (equal (caar spoken) "No cell in that row."))
        (emacsvox-table-reader-next-column)
        (should (= origin (point)))
        (should (equal (caar spoken) "Right edge of table."))
        (emacsvox-table-reader-next-column 0)
        (should (= origin (point)))
        (should (equal (caar spoken) "Long.")))
      (emacsvox-table-reader-speak-context)
      (should (equal (caar spoken) "Row 2 of 3, column 3 of 3."))
      (emacsvox-table-reader-previous-row)
      (emacsvox-table-reader-previous-row)
      (should (equal (caar spoken) "No content before table."))
      (should emacsvox-table-reader-mode)
      (emacsvox-table-reader-next-row 3)
      (should (equal (caar spoken) "No content after table."))
      (should emacsvox-table-reader-mode))))

(ert-deftest emacsvox-table-reader-logical-copy-and-formatting ()
  "Copies use logical text while headers and blanks have consistent speech."
  (dolist (case `((markdown-mode ,emacsvox-table-reader-test--markdown)
                  (org-mode ,emacsvox-table-reader-test--org)))
    (emacsvox-table-reader-test--with-table (car case) (cadr case)
      (emacsvox-table-reader-mode 1)
      (emacsvox-table-reader-next-row)
      (emacsvox-table-reader-next-column)
      (emacsvox-table-reader-copy-cell)
      (should (equal (car kill-ring) "Engineer"))
      (emacsvox-table-reader-copy-row)
      (should (equal (car kill-ring) "Alice\tEngineer"))
      (emacsvox-table-reader-copy-column)
      (should (equal (car kill-ring) "Role\nEngineer\n"))
      (emacsvox-table-reader-speak-column)
      (should (equal (caar spoken) "Role. Engineer. blank."))
      (let ((emacsvox-table-reader-titles '(column row))
            (emacsvox-table-reader-data-position 'last))
        (emacsvox-table-reader-speak-cell)
        (should (equal (caar spoken) "Alice, Role, Engineer.")))
      (should-not (buffer-modified-p)))))

(ert-deftest emacsvox-table-reader-markdown-quoting-and-optional-pipes ()
  "Cell boundaries survive escapes, inline code and optional outer pipes."
  (emacsvox-table-reader-test--with-table 'markdown-mode
      "Name | Value\n--- | ---\n[Link](https://example.test) | `a|b` and x\\|y\n**Bold** | ``x`y|z``\n"
    (emacsvox-table-reader-mode 1)
    (emacsvox-table-reader-next-row)
    (emacsvox-table-reader-copy-row)
    (should (equal (car kill-ring) "Link\ta|b and x|y"))
    (emacsvox-table-reader-next-row)
    (emacsvox-table-reader-copy-row)
    (should (equal (car kill-ring) "Bold\tx`y|z"))
    (emacsvox-table-reader-next-column)
    (should (looking-at "``x`y|z``"))
    (should-not (buffer-modified-p))))

(ert-deftest emacsvox-table-reader-org-links-and-separators ()
  "Org links use labels, mid-table rules are skipped, and formulas stay intact."
  (emacsvox-table-reader-test--with-table 'org-mode
      "| Name | Value |\n|------+-------|\n| [[https://example.test][Link]] | =a*b= |\n|------+-------|\n| Other | 3 |\n#+TBLFM: $2=$1+1\n"
    (let ((source (buffer-string)))
      (emacsvox-table-reader-mode 1)
      (emacsvox-table-reader-next-row)
      (emacsvox-table-reader-copy-row)
      (should (equal (car kill-ring) "Link\ta*b"))
      (emacsvox-table-reader-next-row)
      (should (looking-at "Other"))
      (emacsvox-table-reader-speak-dimensions)
      (should (equal (caar spoken) "Table, 2 data rows, 2 columns."))
      (should (equal source (buffer-string)))
      (should-not (buffer-modified-p)))))

(ert-deftest emacsvox-table-reader-discovery-skips-code-and-restores-prose ()
  "Discovery reaches separate tables, skips examples, and never inserts letters."
  (dolist (case `((markdown-mode ,emacsvox-table-reader-test--markdown "```text\n| Fake |\n```\n")
                  (org-mode ,emacsvox-table-reader-test--org "#+begin_example\n| Fake |\n#+end_example\n")))
    (emacsvox-table-reader-test--with-table (car case)
        (concat (cadr case) (nth 2 case) "\n| Second |\n\nEnd\n")
      (goto-char (point-min))
      (emacsvox-table-reader-next-table)
      (should (looking-at "Name"))
      (emacsvox-table-reader-next-table)
      (should (looking-at "Second"))
      (emacsvox-table-reader-next-table)
      (should (equal (caar spoken) "No next table."))
      (emacsvox-table-reader-previous-table)
      (should (looking-at "Name"))
      (emacsvox-table-reader-exit-forward)
      (should (looking-at "After"))
      (should-not emacsvox-table-reader-mode)
      (should-not (buffer-modified-p)))))


(ert-deftest emacsvox-table-reader-settings-are-local ()
  "Reading choices leave native Org editing feedback and other buffers alone."
  (let ((titles (default-value 'emacsvox-table-reader-titles))
        (org-feedback emacsvox-org-table-after-movement-function))
    (emacsvox-table-reader-test--with-table 'org-mode emacsvox-table-reader-test--org
      (emacsvox-table-reader-mode 1)
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?r)))
        (emacsvox-table-reader-select-speaking-method))
      (should (local-variable-p 'emacsvox-table-reader-titles))
      (should (equal emacsvox-table-reader-titles '(column row)))
      (should (eq org-feedback emacsvox-org-table-after-movement-function)))
    (should (equal titles (default-value 'emacsvox-table-reader-titles)))))

(ert-deftest emacsvox-table-reader-existing-table-prefix-survives ()
  "The browser's table prefix retains its established commands after loading."
  (require 'emacsvox-keymap)
  (let ((legacy (lookup-key emacsvox-table-submap "r")))
    (require 'emacsvox-table-ui)
    (when legacy (should (eq legacy (lookup-key emacsvox-table-submap "r"))))
    (should (eq (lookup-key emacsvox-table-submap (kbd "C-r"))
                'emacsvox-table-reader-mode))
    (should (eq (lookup-key emacsvox-table-submap "]")
                'emacsvox-table-reader-next-table))
    (should (eq (lookup-key emacsvox-table-submap "[")
                'emacsvox-table-reader-previous-table))))

(ert-deftest emacsvox-table-reader-graphical-wrapped-source ()
  "Actual graphical wrapping does not shorten cells or alter logical movement."
  (skip-unless (display-graphic-p))
  (let ((long (concat (apply #'concat (make-list 80 "long content ")) "FINAL")))
    (dolist (mode '(markdown-mode org-mode))
      (save-window-excursion
        (emacsvox-table-reader-test--with-table mode
            (concat "Before\n| Name | Notes |\n"
                    (if (eq mode 'org-mode) "|------+-------|\n" "|---|---|\n")
                    "| Alice | " long " |\n| Bob | End |\nAfter\n")
          (set-window-buffer (selected-window) (current-buffer))
          (setq-local truncate-lines nil)
          (visual-line-mode 1)
          (emacsvox-table-reader-mode 1)
          (call-interactively (key-binding (kbd "C-M-<right>")))
          (call-interactively (key-binding (kbd "<down>")))
          (redisplay t)
          (should (> (count-screen-lines (line-beginning-position)
                                         (line-end-position)) 1))
          (should (looking-at "long content"))
          (should (string-match-p "FINAL, Notes\\." (caar spoken)))
          (call-interactively (key-binding (kbd "w")))
          (should (equal (car kill-ring) long))
          (call-interactively (key-binding (kbd "<down>")))
          (should (looking-at "End"))
          (call-interactively (key-binding (kbd "<up>")))
          (should (looking-at "long content"))
          (should (string-match-p "FINAL, Notes\\." (caar spoken)))
          (call-interactively (key-binding (kbd "M-<down>")))
          (should (looking-at "After"))
          (should-not emacsvox-table-reader-mode)
          (should-not (buffer-modified-p)))))))

(ert-deftest emacsvox-table-reader-rich-content-preserves-literal-code ()
  "Plain copies resolve nested links without interpreting literal code markup."
  (should (equal (emacsvox-markdown--table-plain-text
                  "[Open [source]](https://example.test/a(b)) and `a*b`")
                 "Open [source] and a*b"))
  (should (equal (emacsvox-markdown--table-plain-text
                  "![**Description**](image.png) [Label][reference]")
                 "Description Label"))
  (should (equal (emacsvox-org--table-plain-text
                  "Text *bold* [[https://example.test][Label]] =[[literal]]= and ~a*b~")
                 "Text bold Label [[literal]] and a*b")))

(ert-deftest emacsvox-table-reader-submissions-resolve-native-semantic-plans ()
  "Every reader action uses facts accepted by its integration's Aural planner."
  (dolist (case `((markdown-mode ,emacsvox-table-reader-test--markdown)
                  (org-mode ,emacsvox-table-reader-test--org)))
    (emacsvox-table-reader-test--with-table (car case) (cadr case)
      (emacsvox-table-reader-mode 1)
      (emacsvox-table-reader-next-row)
      (emacsvox-table-reader-speak-cell)
      (emacsvox-table-reader-speak-row)
      (emacsvox-table-reader-speak-column)
      (emacsvox-table-reader-speak-context)
      (emacsvox-table-reader-speak-dimensions)
      (emacsvox-table-reader-copy-row)
      (emacsvox-table-reader-exit-forward)
      (should (= (length spoken) 9))
      (dolist (submission spoken)
        (let* ((facts (plist-get (cdr submission) :facts))
               (context (list :module (plist-get (cdr submission) :module)
                              :occasion (plist-get (cdr submission) :occasion)
                              :mode major-mode :mode-lineage (list major-mode)))
               (plan (emacsvox-aural-resolve-active facts context)))
          (should (emacsvox-aural-content-style-speak
                   (emacsvox-aural-render-plan-content plan)))
          (should (emacsvox-aural-compile-plan plan facts context)))))))

(ert-deftest emacsvox-table-reader-markdown-pipe-prose-before-table ()
  "A pipe in adjacent prose neither absorbs nor hides the following table."
  (emacsvox-table-reader-test--with-table 'markdown-mode
      "Literal pipe A | B\nName | Value\n--- | ---\nAlice | Engineer\n"
    (emacsvox-table-reader-mode 1)
    (should (equal (caar spoken)
                   "Table reading. Table, 1 data row, 2 columns. Name."))
    (emacsvox-table-reader-exit-backward)
    (should (looking-at "Literal pipe"))
    (should-error (emacsvox-table-reader-mode 1) :type 'user-error)))

(provide 'emacsvox-table-reader-tests)
;;; emacsvox-table-reader-tests.el ends here
