;;; emacsvox-aural-voice-engine-controls-tests.el --- Engine control interactions -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
;;; Commentary:
;; Qualified catalogue replies, shared draft ownership and real editor actions.
;;; Code:
(require 'emacsvox-aural-voice-editor-tests)
(require 'omnivox-explanation-tests)
(require 'emacsvox-aural-voice-engine-controls)

(defmacro emacsvox-test--with-engine-controls (&rest body)
  (declare (indent 0) (debug t))
  `(omnivox-parameters-test--with-lanes
    (emacsvox-test--with-voice-editor
     (let ((after-change-major-mode-hook (remove #'tts-apply-punctuation-mode-policy after-change-major-mode-hook)))
       (emacsvox-aural-voice-editor-open 'reading-owned 'bolden))
     (omnivox-native-test--bundle speaker)
     (let* ((tts-speaker-process speaker)
            (after-change-major-mode-hook (remove #'tts-apply-punctuation-mode-policy after-change-major-mode-hook))
            (voice (plist-get (omnivox-native-test--entry "paul-main") :voice))
            (snapshot (list :definition (append '(:family nil :average-pitch nil :pitch-range nil :stress nil)
                                                (plist-get voice :shared)) :language (plist-get voice :language)
                            :choices (plist-get voice :choices)
                            :selectors (emacsvox-aural-voice-data--selectors (plist-get voice :choices))))
            (draft (emacsvox-aural-voice-editor--draft)))
       (setf (emacsvox-aural-voice-draft-working draft) (copy-tree snapshot)
             (emacsvox-aural-voice-draft-baseline draft) (copy-tree snapshot)
             (emacsvox-aural-voice-draft-original draft) (copy-tree snapshot))
       (emacsvox-aural-voice-editor--put :tuning-choice "paul-main")
       (emacsvox-aural-voice-engine-controls-open)
       ,@body))))

(defun emacsvox-engine-controls-test--ready ()
  (omnivox-parameters-test--answer tts-speaker-process)
  (omnivox-parameters-test--drain))

(defun emacsvox-engine-controls-test--descriptor (id)
  (cl-find id (plist-get (plist-get (emacsvox-aural-voice-engine-controls--state) :catalogue) :parameters)
           :test #'equal :key (lambda (d) (plist-get d :id))))

(ert-deftest emacsvox-engine-controls-open-is-async-and-does-not-sample ()
  (emacsvox-test--with-engine-controls
   (should (string-match-p "Checking engine controls" (buffer-string)))
   (emacsvox-aural-voice-editor--locate 'status)
   (should (eq (get-text-property (point) 'voice-field) 'status))
   (should (= 1 (length omnivox-parameters-test--writes)))
   (should-not requests)
   (let ((before speech))
     (emacsvox-engine-controls-test--ready)
     (should (equal before speech)))
   (should (string-match-p "Smoothness: 55 percent; adjusted here" (buffer-string)))
   (should (string-match-p "Richness: follows common settings" (buffer-string)))
   (should-not requests)
   (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))))

(ert-deftest emacsvox-engine-controls-sparse-edit-default-inherit-and-undo ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((before (emacsvox-aural-voice-editor--working)))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'set 0)
     (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value 0)))
     (should (equal (cdr (plist-get before :choices)) (cdr (plist-get (emacsvox-aural-voice-editor--working) :choices))))
     (should (equal (plist-get before :definition) (plist-get (emacsvox-aural-voice-editor--working) :definition)))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'default)
     (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op default)))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'inherit)
     (should-not (emacsvox-aural-voice-engine-controls--operation "ri"))
     (emacsvox-aural-voice-editor-undo)
     (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op default)))
     (emacsvox-aural-voice-engine-controls-reset-all)
     (should-not (plist-get (emacsvox-aural-voice-engine-controls--row) :native))
     (should (equal (cdr (plist-get before :choices)) (cdr (plist-get (emacsvox-aural-voice-editor--working) :choices))))
     (emacsvox-aural-voice-editor-undo)
     (should (emacsvox-aural-voice-engine-controls--operation "sm")))
   (should-not requests)))

(ert-deftest emacsvox-engine-controls-validates-types-and-qualified-scope ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((descriptor (emacsvox-engine-controls-test--descriptor "ri")))
     (dolist (bad '(101 -1 2.5 nil "2"))
       (should-error (emacsvox-aural-voice-engine-controls--apply "ri" 'set bad) :type 'user-error))
     (setf (plist-get descriptor :value_type) '(:kind "boolean"))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'set nil)
     (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value nil)))
     (should (string-match-p "false" (emacsvox-aural-voice-engine-controls--summary descriptor)))
     (setf (plist-get descriptor :value_type) '(:kind "enum" :choices [(:label "Soft" :value "soft") (:label "Clear" :value "clear")]))
     (should-error (emacsvox-aural-voice-engine-controls--apply "ri" 'set "unknown") :type 'user-error)
     (emacsvox-aural-voice-engine-controls--apply "ri" 'set "soft")
     (setf (plist-get descriptor :scope) "startup")
     (should-error (emacsvox-aural-voice-engine-controls--apply "ri" 'set "clear") :type 'user-error)
     (emacsvox-aural-voice-engine-controls--apply "ri" 'inherit)
     (should-not (emacsvox-aural-voice-engine-controls--operation "ri")))))

(ert-deftest emacsvox-engine-controls-refresh-never-overwrites-input-or-uses-stale-metadata ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((descriptor (emacsvox-engine-controls-test--descriptor "ri"))
         (before (emacsvox-aural-voice-editor--working)))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Set value"))
               ((symbol-function 'read-number)
                (lambda (&rest _) (emacsvox-aural-voice-engine-controls-refresh)
                  (emacsvox-engine-controls-test--ready) 90)))
       (should-error (emacsvox-aural-voice-engine-controls--edit descriptor) :type 'user-error))
     (should (equal before (emacsvox-aural-voice-editor--working)))
     (process-put speaker 'tts--speech-process-generation 900)
     (should-error (emacsvox-aural-voice-engine-controls--apply "ri" 'set 90) :type 'user-error)
     (should (equal before (emacsvox-aural-voice-editor--working))))))

(ert-deftest emacsvox-engine-controls-schema-mismatch-preserves-settings-and-allows-reset ()
  (emacsvox-test--with-engine-controls
   (let ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes))))
     (setf (plist-get (plist-get (plist-get response :result) :identity) :schema_id) "dectalk.future.v2")
     (omnivox-parameters-test--reply speaker response))
   (omnivox-parameters-test--drain)
   (should (string-match-p "different schema" (buffer-string)))
   (should-error (emacsvox-aural-voice-engine-controls--apply "ri" 'set 3) :type 'user-error)
   (should (emacsvox-aural-voice-engine-controls--operation "sm"))
   (emacsvox-aural-voice-engine-controls-reset-all)
   (emacsvox-aural-voice-engine-controls--apply "ri" 'set 3)
   (should (equal (plist-get (plist-get (emacsvox-aural-voice-engine-controls--row) :native) :schema-id) "dectalk.future.v2"))))

(ert-deftest emacsvox-engine-controls-graphical-groups-search-and-focus ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (emacsvox-aural-voice-editor--locate '(parameter "sm"))
   (emacsvox-aural-voice-engine-controls--render)
   (should (equal (get-text-property (point) 'voice-field) '(parameter "sm")))
   (emacsvox-aural-voice-engine-controls--toggle :expanded "voice_character")
   (should-not (string-match-p "Smoothness:" (buffer-string)))
   (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "smoothness")))
     (emacsvox-aural-voice-engine-controls-search))
   (should (string-match-p "Smoothness:" (buffer-string)))
   (should-not (string-match-p "Richness:" (buffer-string)))
   (emacsvox-aural-voice-engine-controls--put :filter "")
   (emacsvox-aural-voice-engine-controls--toggle :changed)
   (should (string-match-p "Smoothness:" (buffer-string)))
   (should-not (string-match-p "Richness:" (buffer-string)))
   (when (display-graphic-p)
     (emacsvox-aural-voice-editor--locate '(parameter "sm"))
     (redisplay t)
     (should (pos-visible-in-window-p (point))))))

(ert-deftest emacsvox-engine-controls-back-detaches-query-and-restores-common-navigation ()
  (emacsvox-test--with-engine-controls
   (let ((waiter (plist-get (emacsvox-aural-voice-engine-controls--state) :waiter)))
     (call-interactively (key-binding (kbd "q")))
     (should-not emacsvox-aural-voice-engine-controls-mode)
     (should (omnivox-parameters--waiter-cancelled waiter))
     (should (eq (get-text-property (point) 'voice-field) 'engine-controls))
     (emacsvox-engine-controls-test--ready)
     (should-not (emacsvox-aural-voice-editor--get :engine-controls))
     (should-not (string-match-p "Smoothness:" (buffer-string))))))

(ert-deftest emacsvox-engine-controls-completion-edits-without-automatic-sample ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((descriptor (emacsvox-engine-controls-test--descriptor "ri")))
     (cl-letf (((symbol-function 'completing-read) (lambda (_ choices &rest _) (should (member "Set value" choices)) "Set value"))
               ((symbol-function 'read-number) (lambda (&rest _) 83)))
       (emacsvox-aural-voice-engine-controls--edit descriptor)))
   (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value 83)))
   (should-not requests)))

(ert-deftest emacsvox-engine-controls-saves-through-existing-palette-stores ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((old-aural (emacsvox-aural-read-user-data))
         (old-routing (emacsvox-aural-read-routing-profiles)))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'set 82)
     (should (equal old-aural (emacsvox-aural-read-user-data)))
     (should (equal old-routing (emacsvox-aural-read-routing-profiles)))
     (emacsvox-aural-voice-editor-save-to-collection)
     (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))
     (should (= 10 (plist-get (emacsvox-aural-read-user-data) :schema-version)))
     (let* ((saved (emacsvox-aural-voice-editing--snapshot 'reading-owned 'bolden))
            (choices (plist-get (plist-get saved :snapshot) :choices)))
       (should (equal choices (plist-get (emacsvox-aural-voice-editor--working) :choices)))
       (should (equal (cdr (assoc "ri" (plist-get (plist-get (car choices) :native) :parameters))) '(:op set :value 82)))))))

(ert-deftest emacsvox-engine-controls-preview-key-submits-native-draft-and-retains-evidence ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (emacsvox-aural-voice-engine-controls--apply "sm" 'set 61)
   (let ((tts-voice-preview-function #'omnivox-preview-voice-sequence)
         (tts-notify-process notification) wire)
     (set-process-coding-system speaker 'utf-8-unix 'utf-8-unix)
     (omnivox--install-control-filter speaker)
     (emacsvox-aural-voice-editor--put :policy '(:engine-order ("dectalk") :fallback (:engines ("espeak"))))
     (cl-letf (((symbol-function 'process-send-string)
                (lambda (process text)
                  (should (eq process speaker))
                  (when (string-prefix-p "omnivox_control {" text)
                    (setq wire (omnivox--decode-control-response (substring text (length "omnivox_control {") -2) t))))))
       (tts-queue--install)
       (process-put speaker 'tts-queue--state (tts-queue--make-state :queue 0 :framing 0))
       (call-interactively (key-binding (kbd "P")))
       (should (equal (plist-get wire :type) "preview_voice_v3"))
       (should (equal (plist-get (plist-get wire :selection) :choice_id) "paul-main"))
       (let ((native (plist-get (aref (plist-get (plist-get wire :voice) :choices) 0) :native)))
         (should (equal (plist-get (plist-get native :parameters) :sm) '(:op "set" :value 61))))
       (omnivox-preview-test--control-line speaker (omnivox-native-test--terminal (plist-get wire :request_id)))
       (should (string-match-p "last sample playback started on dectalk/paul" (buffer-string)))
       (should-not (emacsvox-aural-voice-editor--get :preview-operation))
       (should (emacsvox-aural-voice-drafts--dirty-fields draft))))))

(ert-deftest emacsvox-engine-controls-close-retains-draft-without-stale-view-state ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (emacsvox-aural-voice-engine-controls--apply "ri" 'set 51)
   (let ((context emacsvox-aural-voice-editor--context)
         (kill-buffer-query-functions nil))
     (kill-buffer (current-buffer))
     (should-not (plist-get context :engine-controls))
     (emacsvox-aural-voice-editor-open 'reading-owned 'bolden)
     (should-not emacsvox-aural-voice-engine-controls-mode)
     (should (eq draft (emacsvox-aural-voice-editor--draft)))
     (should (equal (cdr (assoc "ri" (plist-get (plist-get (car (plist-get (emacsvox-aural-voice-editor--working) :choices)) :native) :parameters)))
                    '(:op set :value 51))))))

(ert-deftest emacsvox-engine-controls-value-prompts-retain-explicit-current-values ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let ((descriptor (emacsvox-engine-controls-test--descriptor "ri")))
     (emacsvox-aural-voice-engine-controls--apply "ri" 'set 24)
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest args) (nth 6 args)))
               ((symbol-function 'read-number) (lambda (_prompt &optional default) default)))
       (emacsvox-aural-voice-engine-controls--edit descriptor)
       (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value 24)))
       (setf (plist-get descriptor :value_type) '(:kind "boolean"))
       (emacsvox-aural-voice-engine-controls--apply "ri" 'set nil)
       (emacsvox-aural-voice-engine-controls--edit descriptor)
       (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value nil)))
       (setf (plist-get descriptor :value_type) '(:kind "enum" :choices [(:label "Soft" :value "soft") (:label "Clear" :value "clear")]))
       (emacsvox-aural-voice-engine-controls--apply "ri" 'set "clear")
       (emacsvox-aural-voice-engine-controls--edit descriptor)
       (should (equal (emacsvox-aural-voice-engine-controls--operation "ri") '(:op set :value "clear")))))))

(ert-deftest emacsvox-engine-controls-explanations-use-only-matching-catalogue-labels ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (let* ((catalogue (copy-tree (plist-get (emacsvox-aural-voice-engine-controls--state) :catalogue)))
          (response (list :status 'ready :catalogue catalogue
                          :explanation (plist-get (omnivox-native-test--message :explain_response) :result))))
     (should (string-match-p "Richness: 63 percent" (emacsvox-aural-voice-editor--explanation-text response)))
     (setf (plist-get (plist-get catalogue :identity) :runtime_generation) 999)
     (should (string-match-p "ri: 63;" (emacsvox-aural-voice-editor--explanation-text response)))
     (should-not (string-match-p "Richness:" (emacsvox-aural-voice-editor--explanation-text response))))))

(ert-deftest emacsvox-engine-controls-old-worker-is-readonly-without-losing-overrides ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (process-put speaker omnivox--control-capabilities-property '(:features ("engine_parameter_catalogue_v1")))
   (emacsvox-aural-voice-engine-controls--render)
   (emacsvox-aural-voice-editor--locate 'status)
   (should (string-match-p "cannot apply native" (button-label (button-at (point)))))
   (should-error (emacsvox-aural-voice-engine-controls--apply "sm" 'set 50) :type 'user-error)
   (should (equal (emacsvox-aural-voice-engine-controls--operation "sm") '(:op set :value 55)))
   (should-not (emacsvox-aural-voice-drafts--dirty-fields draft))))

(ert-deftest emacsvox-engine-controls-eloquence-edits-its-own-choice-and-schema ()
  (emacsvox-test--with-engine-controls
   (emacsvox-engine-controls-test--ready)
   (emacsvox-aural-voice-engine-controls-back)
   (emacsvox-aural-voice-editor--put :tuning-choice "eci-default")
   (emacsvox-aural-voice-engine-controls-open)
   (let* ((request (cdar omnivox-parameters-test--writes))
          (response (omnivox-parameters-test--response request))
          (result (plist-get response :result)) (descriptor (aref (plist-get result :parameters) 0)))
     (should (equal (plist-get request :engine_id) "eloquence"))
     (should (eq (plist-get request :voice_id) :null))
     (setf (plist-get response :engine_id) "eloquence"
           (plist-get result :voice_id) :null
           (plist-get (plist-get result :identity) :schema_id) "eloquence.eci-units.v1"
           (plist-get (plist-get result :identity) :profile_id) "eloquence.windows.v1"
           (plist-get result :parameters) (vector descriptor)
           (plist-get result :mappings) []
           (plist-get descriptor :id) "breathiness"
           (plist-get descriptor :label) "Breathiness"
           (plist-get (plist-get descriptor :default) :source) "qualified_profile")
     (omnivox-parameters-test--reply speaker response))
   (omnivox-parameters-test--drain)
   (let ((before (emacsvox-aural-voice-editor--working)))
     (emacsvox-aural-voice-engine-controls--apply "breathiness" 'set 25)
     (should (equal (car (plist-get before :choices)) (car (plist-get (emacsvox-aural-voice-editor--working) :choices))))
     (should (equal (plist-get (plist-get (emacsvox-aural-voice-engine-controls--row) :native) :schema-id) "eloquence.eci-units.v1"))
     (should (equal (emacsvox-aural-voice-engine-controls--operation "breathiness") '(:op set :value 25))))))

(provide 'emacsvox-aural-voice-engine-controls-tests)
;;; emacsvox-aural-voice-engine-controls-tests.el ends here
