;;; omnivox-catalogue-tests.el --- Available voice regressions -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
(require 'ert)
(require 'omnivox-catalogue)

(defun omnivox-catalogue-tests--entries ()
  (plist-get (json-parse-string
              (with-temp-buffer
                (insert-file-contents (expand-file-name "omnivox-voice-catalogue.json" emacsvox-etc-directory))
                (buffer-string)) :object-type 'plist :array-type 'array :null-object :null :false-object :false)
             :entries))

(ert-deftest omnivox-catalogue-filters-available-voices-and-explains-no-matches ()
  (with-temp-buffer
    (omnivox-catalogue-mode)
    (setq omnivox-catalogue--entries (omnivox-catalogue-tests--entries)
          omnivox-catalogue--engine "flite")
    (omnivox-catalogue--render)
    (should (= 2 (length tabulated-list-entries)))
    (omnivox-catalogue-search "RMS")
    (should (= 1 (length tabulated-list-entries)))
    (should (equal (caar tabulated-list-entries) "flite-cmu-us-rms"))
    (omnivox-catalogue-search "nonexistent")
    (should-not (tabulated-list-get-id))
    (should (string-search "No reviewed voices match" (buffer-string)))
    (let (spoken)
      (cl-letf (((symbol-function 'emacsvox-aural-ui-speak) (lambda (text) (setq spoken text))))
        (omnivox-catalogue--speak-row)
        (should (string-search "No reviewed voices match" spoken))))
    (should-error (omnivox-catalogue--selected) :type 'user-error)))

(ert-deftest omnivox-catalogue-refreshed-installation-supersedes-old-operation-status ()
  (let ((omnivox-catalogue--operations (make-hash-table :test #'equal)))
    (with-temp-buffer
      (omnivox-catalogue-mode)
      (let* ((entry (aref (omnivox-catalogue-tests--entries) 0))
             (key (omnivox-catalogue--key nil entry)))
        (puthash key '(:progress (:state "installed-disabled")) omnivox-catalogue--operations)
        (setq omnivox-catalogue--installed
              (vector (list :catalogue (list :entry_id (plist-get entry :id)))))
        (should (equal "Installed" (omnivox-catalogue--status entry)))))))

(ert-deftest omnivox-catalogue-progress-is-quiet-correlated-and-retained ()
  (let* ((omnivox-catalogue--operations (make-hash-table :test #'equal))
         (process (make-pipe-process :name "catalogue progress fixture" :noquery t))
         (stale (make-pipe-process :name "catalogue stale fixture" :noquery t))
         (key '("root" "target" "profile" "voice")) notices)
    (unwind-protect
        (cl-letf (((symbol-function 'message) (lambda (&rest args) (push args notices)))
                  ((symbol-function 'omnivox-catalogue--redraw) #'ignore))
          (process-put process 'omnivox-catalogue-key key)
          (process-put stale 'omnivox-catalogue-key key)
          (puthash key (list :process process) omnivox-catalogue--operations)
          (let ((line "OMNIVOX-LOCAL {\"request_id\":1,\"type\":\"acquisition\",\"progress\":{\"operation_id\":\"test\",\"state\":\"downloading\",\"downloaded_bytes\":1,\"total_bytes\":2,\"terminal\":false,\"detail\":\"Downloading\"}}\n"))
            (omnivox-catalogue--filter process (substring line 0 25))
            (should-not (plist-get (gethash key omnivox-catalogue--operations) :progress))
            (omnivox-catalogue--filter process (substring line 25))
            (should-not notices)
            (omnivox-catalogue--filter stale (replace-regexp-in-string "downloading" "stale" line))
            (should (equal "downloading" (plist-get (plist-get (gethash key omnivox-catalogue--operations) :progress) :state)))
            (let ((terminal (replace-regexp-in-string "false" "true" (replace-regexp-in-string "downloading" "installed-disabled" line))))
              (omnivox-catalogue--filter process terminal)
              (omnivox-catalogue--filter process terminal)
              (should (= 1 (length notices)))
              (should (string-search "Press l to browse voices, plus to enable, then a to Apply"
                                     (apply #'format (car notices))))))
          (delete-process process)
          (omnivox-catalogue--sentinel process "finished")
          (should-not (plist-get (gethash key omnivox-catalogue--operations) :error)))
      (when (process-live-p process) (delete-process process))
      (delete-process stale))))

(ert-deftest omnivox-catalogue-cancel-keeps-cleanup-owner-alive ()
  (let* ((omnivox-catalogue--operations (make-hash-table :test #'equal))
         (process (make-pipe-process :name "catalogue cancellation fixture" :noquery t)) eof)
    (unwind-protect
        (with-temp-buffer
          (omnivox-catalogue-mode)
          (setq omnivox-catalogue--entry (aref (omnivox-catalogue-tests--entries) 0))
          (puthash (omnivox-catalogue--key nil omnivox-catalogue--entry) (list :process process)
                   omnivox-catalogue--operations)
          (cl-letf (((symbol-function 'process-send-eof) (lambda (p) (setq eof p))))
            (omnivox-catalogue-cancel)
            (should (eq eof process))
            (should (process-live-p process))))
      (delete-process process))))

(ert-deftest omnivox-catalogue-graphical-navigation-and-background-refresh ()
  (skip-unless (display-graphic-p))
  (let ((catalogue (generate-new-buffer " *catalogue graphical fixture*")) details spoken)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer catalogue)
          (omnivox-catalogue-mode)
          (setq omnivox-catalogue--entries (omnivox-catalogue-tests--entries)
                omnivox-catalogue--engine "flite")
          (omnivox-catalogue--render)
          (goto-char (point-min))
          (cl-letf (((symbol-function 'emacsvox-aural-ui-speak) (lambda (text) (setq spoken text))))
            (emacsvox-aural-ui-next-row)
            (should (string-prefix-p "RMS" spoken))
            (emacsvox-aural-ui-previous-row)
            (should (string-prefix-p "AWB" spoken))
            (omnivox-catalogue-details)
            (setq details (current-buffer))
            (should (equal spoken "Voice. AWB"))
            (emacsvox-aural-ui-next-row)
            (let ((selected (tabulated-list-get-id)) (window (selected-window)))
              (omnivox-catalogue--redraw '(nil nil nil "flite-cmu-us-awb"))
              (redisplay t)
              (should (eq window (selected-window)))
              (should (eq selected (tabulated-list-get-id)))
              (should (pos-visible-in-window-p (point))))
            (emacsvox-aural-quit)
            (redisplay t)
            (should (eq catalogue (current-buffer)))
            (should (equal "flite-cmu-us-awb" (tabulated-list-get-id)))))
      (dolist (buffer (list catalogue details)) (when (buffer-live-p buffer) (kill-buffer buffer))))))

(defun omnivox-catalogue-tests--grouped-fixture ()
  (let* ((entry (copy-tree (aref (omnivox-catalogue-tests--entries) 2)))
         (other (copy-tree entry)))
    (setq other (plist-put other :id "piper-de-de-fixture-medium")
          other (plist-put other :language "de-DE")
          other (plist-put other :name "Fixture medium")
          omnivox-catalogue--entries (vector entry other)
          omnivox-catalogue--engine "piper"
          omnivox-catalogue--metadata
          '(:piper-en-us-kristin-medium (:voice_name "kristin" :quality "medium" :language_name "English")
            :piper-de-de-fixture-medium (:voice_name "fixture" :quality "medium" :language_name "German")))
    (omnivox-catalogue--render)
    (goto-char (point-min))))

(ert-deftest omnivox-catalogue-groups-search-and-back-preserve-selection ()
  (with-temp-buffer
    (omnivox-catalogue-mode)
    (omnivox-catalogue-tests--grouped-fixture)
    (cl-letf (((symbol-function 'emacsvox-aural-ui-speak) #'ignore))
      (let ((language (tabulated-list-get-id)))
        (should (eq 'group (car language)))
        (should-error (omnivox-catalogue--selected) :type 'user-error)
        (omnivox-catalogue-details)
        (should (= 1 (length omnivox-catalogue--scope)))
        (omnivox-catalogue-details)
        (should (= 2 (length omnivox-catalogue--scope)))
        (should (equal "piper-en-us-kristin-medium" (plist-get (omnivox-catalogue--selected) :id)))
        (omnivox-catalogue-search "German")
        (goto-char (point-min))
        (should (equal "piper-de-de-fixture-medium" (tabulated-list-get-id)))
        (omnivox-catalogue-back)
        (omnivox-catalogue-back)
        (omnivox-catalogue-back)
        (should (equal language (tabulated-list-get-id)))))))

(ert-deftest omnivox-catalogue-details-retain-selected-document-and-speakers ()
  (let ((parent (generate-new-buffer " *catalogue source fixture*")) detail)
    (unwind-protect
        (with-current-buffer parent
          (omnivox-catalogue-mode)
          (setq omnivox-catalogue--entries (omnivox-catalogue-tests--entries)
                omnivox-catalogue--documents '(("flite-cmu-us-awb" . "correct document"))
                omnivox-catalogue--json "wrong document")
          (omnivox-catalogue--render)
          (goto-char (point-min))
          (cl-letf (((symbol-function 'emacsvox-aural-ui--pop-to-buffer)
                     (lambda (buffer _) (setq detail buffer))))
            (omnivox-catalogue-details))
          (with-current-buffer detail
            (should (equal "correct document" omnivox-catalogue--json))
            (omnivox-catalogue-speakers)
            (should (seq-find (lambda (row) (eq 'speaker (car-safe (car row)))) tabulated-list-entries))))
      (dolist (buffer (list parent detail)) (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest omnivox-catalogue-graphical-group-navigation ()
  (skip-unless (display-graphic-p))
  (let ((buffer (generate-new-buffer " *catalogue grouped graphical fixture*")) spoken)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (omnivox-catalogue-mode)
          (omnivox-catalogue-tests--grouped-fixture)
          (cl-letf (((symbol-function 'emacsvox-aural-ui-speak) (lambda (text) (setq spoken text))))
            (emacsvox-aural-ui-next-row)
            (should (string-prefix-p "German" spoken))
            (emacsvox-aural-ui-previous-row)
            (should (string-prefix-p "English" spoken))
            (let ((id (tabulated-list-get-id)))
              (omnivox-catalogue-details)
              (should (string-prefix-p "kristin" spoken))
              (omnivox-catalogue-details)
              (let ((model (tabulated-list-get-id)) (window (selected-window)))
                (omnivox-catalogue--render)
                (redisplay t)
                (should (equal model (tabulated-list-get-id)))
                (should (eq window (selected-window)))
                (should (pos-visible-in-window-p (point))))
              (omnivox-catalogue-back)
              (omnivox-catalogue-back)
              (redisplay t)
              (should (equal id (tabulated-list-get-id)))
              (should (pos-visible-in-window-p (point))))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(provide 'omnivox-catalogue-tests)
;;; omnivox-catalogue-tests.el ends here
