;;; omnivox-parameters-tests.el --- Live parameter discovery -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
;;; Commentary:
;; Independent wire examples, real request ownership, deterministic timers.
;;; Code:
(require 'ert)
(require 'tts-speak)
(require 'omnivox-voices)

(defconst omnivox-parameters-test--fixture
  (expand-file-name "fixtures/voice-editor/engine-parameters-wire.json"
                    (file-name-directory (or load-file-name buffer-file-name))))
(defvar omnivox-parameters-test--timers nil)
(defvar omnivox-parameters-test--writes nil)

(defun omnivox-parameters-test--response (&optional request)
  (let ((response
         (with-temp-buffer
           (insert-file-contents omnivox-parameters-test--fixture)
           (plist-get (plist-get (json-parse-buffer :object-type 'plist
                                                  :null-object :null :false-object :false)
                                :messages) :catalogue_response))))
    (when request (setf (plist-get response :request_id) (plist-get request :request_id)))
    response))

(defun omnivox-parameters-test--tick (timer)
  (when (aref timer 4)
    (aset timer 4 nil)
    (apply (aref timer 2) (aref timer 3))))

(defun omnivox-parameters-test--drain ()
  (let ((limit 100) timer)
    (while (setq timer (cl-find-if (lambda (item) (and (aref item 4) (= 0 (aref item 1))))
                                 (reverse omnivox-parameters-test--timers)))
      (should (> (cl-decf limit) 0))
      (omnivox-parameters-test--tick timer))))

(defun omnivox-parameters-test--reply (process response)
  (omnivox--handle-control-line
   process (concat omnivox-control-event-prefix
                   (base64-encode-string (encode-coding-string (json-serialize response) 'utf-8 t) t))))

(defmacro omnivox-parameters-test--with-lanes (&rest body)
  (declare (indent 0) (debug t))
  `(let ((speaker (make-pipe-process :name "parameters-main" :noquery t))
         (notification (make-pipe-process :name "parameters-notify" :noquery t))
         (omnivox-parameters-test--timers nil) (omnivox-parameters-test--writes nil)
         (omnivox-parameters--last-error nil) (omnivox--control-request-sequence 0)
         (omnivox-voice-configuration-timeout 30) results)
     (unwind-protect
         (cl-letf (((symbol-function 'run-at-time)
                    (lambda (delay _repeat function &rest args)
                      (let ((timer (vector 'parameter-test-timer delay function args t)))
                        (push timer omnivox-parameters-test--timers) timer)))
                   ((symbol-function 'timerp)
                    (lambda (value) (and (vectorp value) (= (length value) 5)
                                         (eq (aref value 0) 'parameter-test-timer))))
                   ((symbol-function 'cancel-timer) (lambda (timer) (aset timer 4 nil)))
                   ((symbol-function 'process-send-string)
                    (lambda (process text)
                      (should (string-prefix-p "omnivox_control {" text))
                      (push (cons process (omnivox--decode-control-response
                                           (substring text (length "omnivox_control {") -2) t))
                            omnivox-parameters-test--writes)))
                   ((symbol-function 'tts-stop) (lambda (&rest _) (ert-fail "Discovery stopped speech")))
                   ((symbol-function 'accept-process-output) (lambda (&rest _) (ert-fail "Discovery waited"))))
           (dolist (process (list speaker notification))
             (process-put process omnivox--control-capabilities-property
                          '(:features ("engine_parameter_catalogue_v1")))
             (process-put process omnivox--control-inventory-property '(:inventory_generation 1)))
           ,@body)
       (delete-process speaker) (delete-process notification))))

(defun omnivox-parameters-test--request (process callback &optional current)
  (omnivox-parameters--request process "dectalk" "paul" callback current))

(defun omnivox-parameters-test--answer (process)
  (omnivox-parameters-test--reply
   process (omnivox-parameters-test--response (cdr (assq process omnivox-parameters-test--writes)))))

(ert-deftest omnivox-parameters-independent-wire-and-strict-scalars ()
  (let* ((response (omnivox-parameters-test--response))
         (result (omnivox-parameters--page response "dectalk" "paul"))
         (descriptor (aref (plist-get result :parameters) 0)))
    (should (omnivox-parameters--editable-p descriptor))
    (setf (plist-get descriptor :value_type) '(:kind "boolean")
          (plist-get (plist-get descriptor :default) :value) :false)
    (should (omnivox-parameters--page response "dectalk" "paul"))
    (setf (plist-get (plist-get descriptor :default) :value) :null)
    (should-error (omnivox-parameters--page response "dectalk" "paul"))
    (setf (plist-get (plist-get descriptor :default) :value) nil)
    (should-error (omnivox-parameters--descriptor descriptor "paul"))))

(ert-deftest omnivox-parameters-numeric-and-enum-contracts ()
  (dolist (type '((:kind "integer" :minimum 0 :maximum 100 :step 3)
                  (:kind "number" :minimum 0.0 :maximum 100.0 :step 3.0)))
    (should (omnivox-parameters--type type))
    (should (omnivox-parameters--accepts-p type 0))
    (should (omnivox-parameters--accepts-p type 1))
    (should-not (omnivox-parameters--accepts-p type 101))
    (should-not (omnivox-parameters--accepts-p type 1.0e+INF))
    (setf (plist-get type :step) 0)
    (should-error (omnivox-parameters--type type)))
  (let ((type '(:kind "enum" :choices [(:value "soft" :label "Soft") (:value "clear" :label "Clear")])))
    (should (omnivox-parameters--type type))
    (should (omnivox-parameters--accepts-p type "soft"))
    (should-not (omnivox-parameters--accepts-p type "other"))
    (should-not (omnivox-parameters--accepts-p type 'soft))))

(ert-deftest omnivox-parameters-future-types-and-other-scopes-are-readonly ()
  (let* ((response (omnivox-parameters-test--response))
         (descriptor (aref (plist-get (plist-get response :result) :parameters) 0)))
    (dolist (scope '("engine" "startup"))
      (setf (plist-get descriptor :scope) scope)
      (omnivox-parameters--descriptor descriptor "paul")
      (should-not (omnivox-parameters--editable-p descriptor)))
    (setf (plist-get descriptor :scope) "voice"
          (plist-get descriptor :value_type) '(:kind "future-scalar" :precision 2))
    (omnivox-parameters--descriptor descriptor "paul")
    (should-not (omnivox-parameters--editable-p descriptor))
    (setf (plist-get (plist-get descriptor :default) :value) [1 2])
    (should-error (omnivox-parameters--descriptor descriptor "paul"))))

(ert-deftest omnivox-parameters-rejects-malformed-metadata ()
  (dolist (mutation
           (list (lambda (r) (setf (plist-get r :engine_id) "piper"))
                 (lambda (r) (setf (plist-get (plist-get r :result) :voice_id) "betty"))
                 (lambda (r) (setf (plist-get (plist-get (plist-get r :result) :identity) :runtime_generation) 0))
                 (lambda (r) (setf (plist-get (plist-get r :result) :next_cursor) "bad cursor"))
                 (lambda (r) (setf (plist-get (plist-get r :result) :parameters) (make-vector 65 nil)))
                 (lambda (r) (let ((d (aref (plist-get (plist-get r :result) :parameters) 0)))
                               (setf (plist-get d :label) (make-string 129 ?x))))
                 (lambda (r) (let ((d (aref (plist-get (plist-get r :result) :parameters) 0)))
                               (setf (plist-get d :adjustable) :null)))
                 (lambda (r) (setf (plist-get r :result) (append (plist-get r :result) '(:status "ready"))))))
    (let ((response (omnivox-parameters-test--response)))
      (funcall mutation response)
      (should-error (omnivox-parameters--page response "dectalk" "paul")))))

(ert-deftest omnivox-parameters-real-filter-preserves-false-without-interning-ids ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (let* ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes)))
          (descriptor (aref (plist-get (plist-get response :result) :parameters) 0))
          (id "unique-parameter-id-not-an-emacs-symbol-71228"))
     (should-not (intern-soft id))
     (setf (plist-get descriptor :id) id
           (plist-get descriptor :value_type) '(:kind "boolean")
           (plist-get (plist-get descriptor :default) :value) :false
           (plist-get (plist-get response :result) :mappings) [])
     (omnivox-parameters-test--reply speaker response)
     (should-not results)
     (omnivox-parameters-test--drain)
     (should (eq (plist-get (car results) :status) 'ready))
     (should (eq :false (plist-get (plist-get (aref (plist-get (plist-get (car results) :catalogue) :parameters) 0) :default) :value)))
     (should-not (intern-soft id))
     (should (zerop (hash-table-count (omnivox--pending-requests speaker)))))))

(ert-deftest omnivox-parameters-coalesces-with-independent-observers-and-cache ()
  (omnivox-parameters-test--with-lanes
   (let ((one (omnivox-parameters-test--request speaker (lambda (_) (ert-fail "Detached observer")))))
     (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
     (omnivox-parameters-test--request speaker (lambda (r)
                                               (setf (plist-get (plist-get r :catalogue) :voice-id) "changed")
                                               (error "Observer failure")))
     (omnivox-parameters--cancel one))
   (should (= 1 (length omnivox-parameters-test--writes)))
   (omnivox-parameters-test--answer speaker)
   (omnivox-parameters-test--drain)
   (should (equal (plist-get (plist-get (car results) :catalogue) :voice-id) "paul"))
   (should omnivox-parameters--last-error)
   (should (equal (plist-get (plist-get (omnivox-parameters--cached speaker "dectalk" "paul") :catalogue) :voice-id) "paul"))
   (omnivox-parameters-test--request speaker #'ignore)
   (should (= 2 (length omnivox-parameters-test--writes)))))

(ert-deftest omnivox-parameters-lanes-and-busy-voices-do-not-overlap ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (omnivox-parameters-test--request notification (lambda (r) (push r results)))
   (omnivox-parameters--request speaker "dectalk" "betty" (lambda (r) (push r results)))
   (should (= 2 (length omnivox-parameters-test--writes)))
   (should-not results)
   (omnivox-parameters-test--drain)
   (should (eq (plist-get (car results) :status) 'busy))
   (omnivox-parameters-test--answer speaker)
   (omnivox-parameters-test--drain)
   (should (omnivox-parameters--cached speaker "dectalk" "paul"))
   (should-not (omnivox-parameters--cached notification "dectalk" "paul"))
   (omnivox-parameters-test--answer notification)
   (omnivox-parameters-test--drain)
   (should (= 3 (length results)))))

(ert-deftest omnivox-parameters-paging-pins-identity-and-allows-forward-references ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (let* ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes)))
          (result (plist-get response :result)) (descriptors (plist-get result :parameters)))
     (setf (plist-get (aref descriptors 0) :side_effects) ["sm"]
           (plist-get result :parameters) (vector (aref descriptors 0))
           (plist-get result :next_cursor) "next")
     (omnivox-parameters-test--reply speaker response)
     (omnivox-parameters-test--drain)
     (should-not results)
     (should-not (omnivox-parameters--cached speaker "dectalk" "paul"))
     (let ((request (cdar omnivox-parameters-test--writes)))
       (should (equal (plist-get request :cursor) "next"))
       (should (equal (plist-get request :expected_catalogue_revision) (make-string 64 ?1)))
       (setf (plist-get response :request_id) (plist-get request :request_id)
             (plist-get result :parameters) (vector (aref descriptors 1))
             (plist-get result :next_cursor) :null))
     (omnivox-parameters-test--reply speaker response)
     (omnivox-parameters-test--drain)
     (should (= 2 (length (plist-get (plist-get (car results) :catalogue) :parameters)))))))

(ert-deftest omnivox-parameters-invalid-continuations-never-publish ()
  (dolist (fault '(runtime revision mappings duplicate cursor reference))
    (omnivox-parameters-test--with-lanes
     (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
     (let* ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes)))
            (result (plist-get response :result)) (descriptors (plist-get result :parameters)))
       (setf (plist-get result :parameters) (vector (aref descriptors 0))
             (plist-get result :next_cursor) "next")
       (omnivox-parameters-test--reply speaker response)
       (omnivox-parameters-test--drain)
       (setf (plist-get response :request_id) (plist-get (cdar omnivox-parameters-test--writes) :request_id)
             (plist-get result :parameters) (vector (aref descriptors 1))
             (plist-get result :next_cursor) :null)
       (pcase fault
         ('runtime (setf (plist-get (plist-get result :identity) :runtime_generation) 8))
         ('revision (setf (plist-get (plist-get result :identity) :catalogue_revision) (make-string 64 ?2)))
         ('mappings (setf (plist-get result :mappings) []))
         ('duplicate (setf (plist-get result :parameters) (vector (aref descriptors 0))))
         ('cursor (setf (plist-get result :next_cursor) "next"))
         ('reference (setf (plist-get (aref descriptors 1) :side_effects) ["missing"])))
       (omnivox-parameters-test--reply speaker response)
       (omnivox-parameters-test--drain)
       (should (eq (plist-get (car results) :status) 'failed))
       (should-not (omnivox-parameters--cached speaker "dectalk" "paul"))
       (should (= 2 (length omnivox-parameters-test--writes)))))))

(ert-deftest omnivox-parameters-busy-and-unavailable-are-terminal-without-retry ()
  (dolist (outcome '((:status "busy" :retry_after_ms 250)
                     (:status "unavailable" :reason "not_described" :message "No controls")))
    (omnivox-parameters-test--with-lanes
     (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
     (let ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes))))
       (setf (plist-get response :result) outcome)
       (omnivox-parameters-test--reply speaker response))
     (omnivox-parameters-test--drain)
     (should (member (plist-get (car results) :status) '(busy unavailable)))
     (should (= 1 (length omnivox-parameters-test--writes)))
     (should-not (process-get speaker 'omnivox-parameters--queries))
     (should-not (cl-some (lambda (timer) (aref timer 4)) omnivox-parameters-test--timers)))))

(ert-deftest omnivox-parameters-deadline-late-reply-and-speech-stop ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (omnivox-parameters--stopped speaker)
   (should (process-get speaker 'omnivox-parameters--queries))
   (let ((deadline (car omnivox-parameters-test--timers)))
     (should (= 5 (aref deadline 1)))
     (omnivox-parameters-test--tick deadline))
   (omnivox-parameters-test--drain)
   (should (eq (plist-get (car results) :status) 'timeout))
   (should (zerop (hash-table-count (omnivox--pending-requests speaker))))
   (omnivox-parameters-test--answer speaker)
   (omnivox-parameters-test--drain)
   (should (= 1 (length results)))
   (should-not (omnivox-parameters--cached speaker "dectalk" "paul"))))

(ert-deftest omnivox-parameters-stale-at-receive-or-delivery ()
  (dolist (stage '(receive delivery))
    (omnivox-parameters-test--with-lanes
     (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
     (omnivox-parameters-test--answer speaker)
     (when (eq stage 'delivery) (omnivox-parameters-test--tick (car omnivox-parameters-test--timers)))
     (process-put speaker omnivox--control-inventory-property '(:inventory_generation 2))
     (omnivox-parameters-test--drain)
     (should (eq (plist-get (car results) :status) 'stale))
     (should-not (omnivox-parameters--cached speaker "dectalk" "paul")))))

(ert-deftest omnivox-parameters-late-error-after-timeout-is-silent ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (omnivox-parameters-test--tick (car omnivox-parameters-test--timers))
   (omnivox-parameters-test--drain)
   (cl-letf (((symbol-function 'omnivox--record-control-error)
              (lambda (&rest _) (ert-fail "Late metadata error reached notifications"))))
     (omnivox-parameters-test--reply
      speaker (list :protocol_version 1 :request_id (plist-get (cdar omnivox-parameters-test--writes) :request_id)
                    :type "error" :message "Old query failed")))
   (should (= 1 (length results)))
   (should-not (process-get speaker 'omnivox-parameters--retired))
   (process-put speaker 'omnivox-parameters--retired (list (+ (expt 2 63) 9)))
   (should (omnivox-parameters--discard-retired-reply-p speaker (+ (expt 2 63) 9)))
   (should-not (process-get speaker 'omnivox-parameters--retired))))

(ert-deftest omnivox-parameters-retirement-cleans-and-view-guard-suppresses ()
  (omnivox-parameters-test--with-lanes
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (omnivox-parameters-test--request speaker (lambda (_) (ert-fail "Obsolete view")) (lambda () nil))
   (process-put speaker 'tts--speech-process-retiring t)
   (omnivox-parameters--stopped speaker)
   (omnivox-parameters-test--drain)
   (should (= 1 (length results)))
   (should (eq (plist-get (car results) :status) 'stale))
   (should (zerop (hash-table-count (omnivox--pending-requests speaker))))))

(ert-deftest omnivox-parameters-unsupported-and-send-failures-are-deferred ()
  (omnivox-parameters-test--with-lanes
   (process-put speaker omnivox--control-capabilities-property '(:features nil))
   (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
   (should-not results)
   (omnivox-parameters-test--drain)
   (should (eq (plist-get (car results) :status) 'unsupported))
   (should-not omnivox-parameters-test--writes)
   (cl-letf (((symbol-function 'process-send-string) (lambda (&rest _) (error "Closed pipe"))))
     (omnivox-parameters-test--request notification (lambda (r) (push r results))))
   (omnivox-parameters-test--drain)
   (should (eq (plist-get (car results) :status) 'failed))
   (should (zerop (hash-table-count (omnivox--pending-requests notification))))))

(ert-deftest omnivox-parameters-reentrant-response-before-send-returns ()
  (omnivox-parameters-test--with-lanes
   (let ((write (symbol-function 'process-send-string)))
     (cl-letf (((symbol-function 'process-send-string)
                (lambda (process text) (funcall write process text)
                  (omnivox-parameters-test--answer process))))
       (omnivox-parameters-test--request speaker (lambda (r) (push r results)))))
   (should-not results)
   (omnivox-parameters-test--drain)
   (should (eq (plist-get (car results) :status) 'ready))))

(ert-deftest omnivox-parameters-assembly-limit-is-enforced-across-pages ()
  (dolist (count '(512 513))
    (omnivox-parameters-test--with-lanes
     (omnivox-parameters-test--request speaker (lambda (r) (push r results)))
     (let ((offset 0))
       (while (< offset count)
         (let* ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes)))
                (result (plist-get response :result))
                (template (aref (plist-get result :parameters) 0))
                (size (min 64 (- count offset))) (parameters []))
           (dotimes (index size)
             (let ((descriptor (tts--dispatch-copy-data template)))
               (setf (plist-get descriptor :id) (format "parameter_%d" (+ offset index)))
               (setq parameters (vconcat parameters (vector descriptor)))))
           (cl-incf offset size)
           (setf (plist-get result :parameters) parameters
                 (plist-get result :mappings) []
                 (plist-get result :next_cursor) (if (< offset count) (format "page-%d" offset) :null))
           (omnivox-parameters-test--reply speaker response)
           (omnivox-parameters-test--drain))))
     (should (eq (plist-get (car results) :status) (if (= count 512) 'ready 'failed)))
     (should (= 1 (length results))))))

(ert-deftest omnivox-parameters-cache-is-bounded-and-retains-qualified-evidence ()
  (omnivox-parameters-test--with-lanes
   (dotimes (index 9)
     (let ((voice (format "path/voice+%d" index)))
       (omnivox-parameters--request speaker "dectalk" voice #'ignore)
       (let ((response (omnivox-parameters-test--response (cdar omnivox-parameters-test--writes))))
         (setf (plist-get (plist-get response :result) :voice_id) voice)
         (omnivox-parameters-test--reply speaker response))
       (omnivox-parameters-test--drain)))
   (should (= 8 (length (process-get speaker 'omnivox-parameters--cache))))
   (should-not (omnivox-parameters--cached speaker "dectalk" "path/voice+0"))
   (let ((entry (omnivox-parameters--cached speaker "dectalk" "path/voice+8")))
     (should (numberp (plist-get entry :checked-at)))
     (should (= 7 (plist-get (plist-get (plist-get entry :catalogue) :identity) :runtime_generation))))))

(ert-deftest omnivox-parameters-cancel-last-observer-does-not-deliver-or-leak ()
  (omnivox-parameters-test--with-lanes
   (let ((waiter (omnivox-parameters-test--request speaker (lambda (_) (ert-fail "Cancelled view")))))
     (omnivox-parameters-test--answer speaker)
     (omnivox-parameters-test--tick (car omnivox-parameters-test--timers))
     (omnivox-parameters--cancel waiter)
     (omnivox-parameters-test--drain)
     (should-not (process-get speaker 'omnivox-parameters--queries))
     (should (zerop (hash-table-count (omnivox--pending-requests speaker))))
     (should-not (cl-some (lambda (timer) (aref timer 4)) omnivox-parameters-test--timers)))))

(provide 'omnivox-parameters-tests)
;;; omnivox-parameters-tests.el ends here
