;;; omnivox-punctuation-tests.el --- Host punctuation editor checks -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
;;; Commentary:
;; Exercise draft isolation, conflict handling, local service and spoken rows.
;;; Code:
(require 'ert)
(require 'cl-lib)
(require 'omnivox-punctuation)

(defun omnivox-punctuation-tests--review ()
  (list :path "/speech/config.json" :sha256 (make-string 64 ?a)
        :defaults (list :none (list :’ :null :$ "dollar")
                        :some (list :’ :null :$ "dollar")
                        :all (list :’ "apostrophe" :$ "dollar"))
        :overrides nil))

(defmacro omnivox-punctuation-tests--buffer (&rest body)
  (declare (indent 0))
  `(cl-letf (((symbol-function 'emacsvox-aural-ui-speak) #'ignore))
     (with-temp-buffer
       (omnivox-punctuation-mode)
       (omnivox-punctuation--accept (omnivox-punctuation-tests--review))
       (omnivox-punctuation--render "’")
       (unwind-protect (progn ,@body)
         (setq kill-buffer-query-functions nil)))))

(ert-deftest omnivox-punctuation-drafts-keep-levels-independent-and-restore-defaults ()
  (omnivox-punctuation-tests--buffer
    (should-not (omnivox-punctuation--dirty-p))
    (omnivox-punctuation--change "’" "Speak a name" "curly quote")
    (should (omnivox-punctuation--dirty-p))
    (should (equal (omnivox-punctuation--value "’") "curly quote"))
    (omnivox-punctuation-level "all")
    (should (equal (omnivox-punctuation--value "’") "apostrophe"))
    (omnivox-punctuation-level "some")
    (should (equal (omnivox-punctuation--value "’") "curly quote"))
    (omnivox-punctuation--change "’" "Restore default")
    (should-not (omnivox-punctuation--dirty-p))
    (omnivox-punctuation--change "$" "Preserve character")
    (should (eq (omnivox-punctuation--value "$") :null))
    (should (equal (gethash "$" (cdr (assoc "some" omnivox-punctuation--defaults))) "dollar"))))

(ert-deftest omnivox-punctuation-save-retains-failed-draft-and-never-restarts ()
  (omnivox-punctuation-tests--buffer
    (omnivox-punctuation--change "’" "Speak a name" "curly quote")
    (cl-letf (((symbol-function 'tts-restart) (lambda () (ert-fail "Unexpected restart")))
              ((symbol-function 'omnivox-punctuation--request) (lambda (_) (error "File changed"))))
      (should-error (omnivox-punctuation-save))
      (should (omnivox-punctuation--dirty-p))
      (should (equal (omnivox-punctuation--value "’") "curly quote")))
    (cl-letf (((symbol-function 'tts-restart) (lambda () (ert-fail "Unexpected restart")))
              ((symbol-function 'omnivox-punctuation--request)
               (lambda (request)
                 (should (equal (plist-get request :command) "punctuation-save"))
                 (should (equal (plist-get request :expected_sha256) (make-string 64 ?a)))
                 (let ((review (omnivox-punctuation-tests--review)))
                   (plist-put review :sha256 (make-string 64 ?b))
                   (plist-put review :overrides
                              (json-parse-string (plist-get request :punctuation_json)
                                                 :object-type 'plist :null-object :null))))))
      (omnivox-punctuation-save)
      (should-not (omnivox-punctuation--dirty-p))
      (should (equal (omnivox-punctuation--value "’") "curly quote"))
      (should (string-match-p "restart" omnivox-punctuation--status)))))

(ert-deftest omnivox-punctuation-refresh-and-restart-respect-drafts-and-targets ()
  (omnivox-punctuation-tests--buffer
    (omnivox-punctuation--change "’" "Speak a name" "quote")
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'omnivox-punctuation--request)
               (lambda (_) (ert-fail "Discarded draft or queried restart"))))
      (omnivox-punctuation-refresh)
      (should (omnivox-punctuation--dirty-p))
      (should-error (omnivox-punctuation-restart) :type 'user-error))
    (omnivox-punctuation--change "’" "Restore default")
    (cl-letf (((symbol-function 'tts-restart) (lambda () (ert-fail "Restarted changed target")))
              ((symbol-function 'omnivox-punctuation--request)
               (lambda (_) (list :sha256 (make-string 64 ?b)))))
      (should-error (omnivox-punctuation-restart) :type 'user-error))))

(ert-deftest omnivox-punctuation-validates-names-and-keeps-explicit-preservation ()
  (omnivox-punctuation-tests--buffer
    (dolist (name '("" " " " edge" "edge " "bad\nname"))
      (should-error (omnivox-punctuation--change "’" "Speak a name" name) :type 'user-error))
    (should-error (omnivox-punctuation--change "’" "Speak a name" (make-string 33 ?é)) :type 'user-error)
    (dolist (character '("" "xx" " " "\n"))
      (should-error (omnivox-punctuation--change character "Preserve character") :type 'user-error))
    (omnivox-punctuation--change "※" "Speak a name" "reference mark")
    (should (equal (tabulated-list-get-id) "※"))
    (omnivox-punctuation--change "※" "Preserve character")
    (should (string-match-p "Preserve character" (aref (tabulated-list-get-entry) 1)))))

(ert-deftest omnivox-punctuation-old-host-fails-without-reading-or-saving ()
  (let ((process (make-pipe-process :name "punctuation old host" :noquery t)) calls)
    (cl-letf (((symbol-function 'omnivox-library--service) (lambda () process))
              ((symbol-function 'omnivox-library--request)
               (lambda (_ command) (push command calls) '(:type "host"))))
      (should-error (omnivox-punctuation--request '(:command "punctuation-review")) :type 'user-error)
      (should (equal calls '((:command "host"))))
      (should-not (process-live-p process)))))

(ert-deftest omnivox-punctuation-native-service-round-trip ()
  (skip-unless (getenv "OMNIVOX_PUNCTUATION_TEST_PROGRAM"))
  (let ((root (make-temp-file "punctuation-ui-" t))
        (process-environment (copy-sequence process-environment)))
    (unwind-protect
        (progn
          (setenv "OMNIVOX_CONFIG_DIR" root)
          (setenv "OMNIVOX_VOICE_ROOT" (expand-file-name "voices" root))
          (with-temp-file (expand-file-name "config.json" root)
            (insert "{\"schema\":2,\"speech\":{\"defaults\":{\"rate\":0.7}}}"))
          (cl-letf (((symbol-function 'omnivox-library--service)
                     (lambda (&optional _role)
                       (make-process :name "punctuation native test"
                                     :command (list (getenv "OMNIVOX_PUNCTUATION_TEST_PROGRAM") "--voice-library-service")
                                     :connection-type 'pipe :coding 'utf-8-unix :noquery t
                                     :filter #'omnivox-library--service-filter)))
                    ((symbol-function 'tts-restart) (lambda () (ert-fail "Unexpected restart"))))
            (omnivox-punctuation-tests--buffer
              (omnivox-punctuation--accept (omnivox-punctuation--request '(:command "punctuation-review")))
              (omnivox-punctuation--change "’" "Speak a name" "single quote")
              (omnivox-punctuation--change "$" "Preserve character")
              (omnivox-punctuation-save)
              (should-not (omnivox-punctuation--dirty-p))
              (let* ((review (omnivox-punctuation--request '(:command "punctuation-review")))
                     (saved (omnivox-punctuation--tables (plist-get review :overrides))))
                (should (equal (gethash "’" (cdr (assoc "some" saved))) "single quote"))
                (should (eq (gethash "$" (cdr (assoc "some" saved))) :null))))
            (with-temp-buffer
              (insert-file-contents (expand-file-name "config.json" root))
              (let ((data (json-parse-buffer :object-type 'plist)))
                (should (= (plist-get data :schema) 3))
                (should (= (plist-get (plist-get (plist-get data :speech) :defaults) :rate) 0.7))))))
      (delete-directory root t))))

(ert-deftest omnivox-punctuation-graphical-navigation-edit-and-return ()
  (skip-unless (display-graphic-p))
  (let ((parent (generate-new-buffer " *punctuation parent*"))
        (editor (generate-new-buffer " *punctuation editor*")) spoken help-spoken)
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'emacsvox-aural-ui-speak) (lambda (text) (push text spoken)))
                    ((symbol-function 'emacsvox-speak-help) (lambda () (setq help-spoken t))))
            (switch-to-buffer parent)
            (switch-to-buffer editor)
            (omnivox-punctuation-mode)
            (setq omnivox-punctuation--parent parent)
            (omnivox-punctuation--accept (omnivox-punctuation-tests--review))
            (omnivox-punctuation--render "’")
            (emacsvox-aural-ui-goto-tabulated-column 1)
            (omnivox-punctuation--change "’" "Speak a name" "single quote")
            (redisplay t)
            (should (eq (window-buffer) editor))
            (should (pos-visible-in-window-p (point) (selected-window)))
            (should (equal (tabulated-list-get-id) "’"))
            (should (= (emacsvox-aural-ui-tabulated-column-index) 1))
            (should (string-match-p "RIGHT SINGLE QUOTATION MARK" (car spoken)))
            (let ((origin (point)))
              (omnivox-punctuation-help)
              (should help-spoken)
              (pop-to-buffer (help-buffer))
              (should (string-match-p "/speech/config.json" (buffer-string)))
              (emacsvox-aural-ui-help-quit)
              (should (eq (current-buffer) editor))
              (should (= (point) origin)))
            (omnivox-punctuation-level "all")
            (should (string-match-p "apostrophe" (aref (tabulated-list-get-entry) 1)))
            (call-interactively (key-binding (kbd "q")))
            (should (eq (current-buffer) parent))
            (with-current-buffer editor (should (omnivox-punctuation--dirty-p)))))
      (with-current-buffer editor (setq kill-buffer-query-functions nil))
      (kill-buffer editor) (kill-buffer parent))))

(provide 'omnivox-punctuation-tests)
;;; omnivox-punctuation-tests.el ends here
