;;; omnivox-espeak-variants-tests.el --- Bundled variant checks -*- lexical-binding: t; -*-
;; Copyright (C) 2026 Emacsvox contributors
;; SPDX-License-Identifier: GPL-2.0-or-later
;;; Commentary:
;; Native catalogue boundaries and non-destructive desired selection.
;;; Code:
(require 'ert)
(require 'cl-lib)
(require 'omnivox-espeak-variants)

(require 'omnivox-engine-settings)
(require 'emacsvox-aural-voice-editor-tests)

(defun omnivox-espeak-variants-tests--inventory ()
  (copy-tree
   '(:status "available" :engines
     ((:engine-id "espeak" :availability "available" :health "healthy"
       :espeak-variants ((:id "m1" :display-name "Male one")
                         (:id "f1" :display-name "Female one"))
       :voices ((:engine-id "espeak" :voice-id "espeak:gmw/en-US"
                 :display-name "English US" :language "en-us" :availability "available")))))))

(ert-deftest omnivox-espeak-variants-old-settings-do-not-gate-startup ()
  (let ((process-environment (copy-sequence process-environment))
        (omnivox-espeak-variants '((nil "espeak:gmw/en-US" "m1"))))
    (setenv "OMNIVOX_ESPEAK_VARIANTS" nil)
    (setenv "EMACSVOX_LOCAL_ESPEAK_VARIANTS" "stale")
    (let ((process-environment (omnivox-engine-settings--environment
                                (expand-file-name "omnivox" emacsvox-servers-directory))))
      (should-not (getenv "EMACSVOX_LOCAL_ESPEAK_VARIANTS")))
    (should (equal omnivox-espeak-variants '((nil "espeak:gmw/en-US" "m1"))))))

(ert-deftest omnivox-espeak-variants-preview-without-enable-save-or-restart ()
  (let ((inventory (omnivox-espeak-variants-tests--inventory)) previews)
    (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory))
              ((symbol-function 'tts-preview-voices)
               (lambda (entries callback) (push entries previews) (funcall callback '(:status completed))))
              ((symbol-function 'tts-restart) (lambda () (ert-fail "Restarted speech")))
              ((symbol-function 'customize-save-variable) (lambda (&rest _) (ert-fail "Saved configuration"))))
      (with-temp-buffer
        (omnivox-espeak-variants-mode)
        (omnivox-espeak-variants--render)
        (goto-char (point-min))
        (should (equal (aref (tabulated-list-get-entry) 1) "Ready"))
        (call-interactively (key-binding (kbd "p")))
        (should (equal (plist-get (plist-get (caar previews) :selector) :voice-id)
                       "espeak:gmw/en-US+f1"))
        (should (equal (tabulated-list-get-id) "f1"))
        (forward-line)
        (call-interactively (key-binding (kbd "RET")))
        (should (equal (plist-get (plist-get (caar previews) :selector) :voice-id)
                       "espeak:gmw/en-US+m1"))
        (should (= (length (plist-get (car (plist-get inventory :engines)) :voices)) 1))
        (should-not (where-is-internal 'omnivox-espeak-variants-apply (current-local-map)))
        (should-not (where-is-internal 'omnivox-espeak-variants-toggle (current-local-map)))))))

(ert-deftest omnivox-espeak-variants-rejects-stale-missing-and-disabled ()
  (let* ((inventory (omnivox-espeak-variants-tests--inventory))
         (engine (car (plist-get inventory :engines)))
         (id "espeak:gmw/en-US+m1"))
    (should (tts--inventory-exact-voice engine id))
    (dolist (bad '("en-US+m1" "espeak:missing+m1" "espeak:gmw/en-US+missing"
                   "espeak:gmw/en-US+../m1" "espeak:gmw/en-US+m1+f1" "espeak:gmw/en-US+1"))
      (should-not (tts--inventory-exact-voice engine bad)))
    (with-temp-buffer
      (omnivox-espeak-variants-mode)
      (setq omnivox-espeak-variants--base "espeak:gmw/en-US")
      (should (equal (omnivox-espeak-variants--preview-state "m1" inventory) "Ready"))
      (plist-put inventory :stale t)
      (should (equal (omnivox-espeak-variants--preview-state "m1" inventory) "Waiting for speech"))
      (plist-put inventory :stale nil)
      (plist-put engine :availability "unavailable")
      (should (equal (omnivox-espeak-variants--preview-state "m1" inventory) "Unavailable"))
      (plist-put engine :availability "available")
      (push (list :voice-id id :availability "unavailable") (plist-get engine :voices))
      (should (equal (omnivox-espeak-variants--preview-state "m1" inventory) "Unavailable"))
      (plist-put engine :espeak-variants nil)
      (should (equal (omnivox-espeak-variants--preview-state "m1" inventory) "Update Omnivox for variants")))))

(ert-deftest omnivox-espeak-variants-normalization-requires-live-capability ()
  (let ((raw '(:id "espeak" :espeak_variants [(:id "m1" :display_name "Male one")])))
    (cl-letf (((symbol-function 'omnivox--control-feature-p) (lambda (_) t)))
      (should (equal (plist-get (omnivox--inventory-engine raw) :espeak-variants)
                     '((:id "m1" :display-name "Male one")))))
    (cl-letf (((symbol-function 'omnivox--control-feature-p) (lambda (_) nil)))
      (should-not (plist-get (omnivox--inventory-engine raw) :espeak-variants)))))

(ert-deftest omnivox-espeak-variants-use-drafts-and-saves-exact-palette-choice ()
  (emacsvox-test--with-voice-editor
   (let* ((inventory (omnivox-espeak-variants-tests--inventory))
          (before (emacsvox-aural-voice-runtime--resolve 'bolden 'reading-owned))
          (saved (emacsvox-aural-read-user-data))
          (source (generate-new-buffer " *variants-use-test*")))
     (unwind-protect
         (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory))
                   ((symbol-function 'tts-restart) (lambda () (ert-fail "Restarted speech"))))
           (switch-to-buffer source)
           (omnivox-espeak-variants-mode)
           (omnivox-espeak-variants--render)
           (emacsvox-aural-ui-goto-row "m1")
           (let ((answers '("reading-owned" "bolden")))
             (cl-letf (((symbol-function 'completing-read)
                        (lambda (&rest _) (or (pop answers) (ert-fail "Unexpected extra prompt")))))
               (call-interactively (key-binding (kbd "u"))))
             (should-not answers))
           (let* ((working (emacsvox-aural-voice-editor--working))
                  (selectors (plist-get working :selectors)))
             (should (equal (plist-get (car selectors) :voice-id) "espeak:gmw/en-US+m1"))
             (should (equal (cdr selectors) (plist-get before :selectors)))
             (should (equal (plist-get working :definition) (plist-get before :definition)))
             (should (eq (marker-buffer (emacsvox-aural-voice-editor--get :origin)) source)))
           (should (equal saved (emacsvox-aural-read-user-data)))
           (should-not callbacks)
           (emacsvox-aural-voice-editor-play)
           (should requests)
           (emacsvox-aural-voice-editor-save)
           (should (= (length callbacks) 1))
           (funcall (car callbacks) '(:status applied :processes ((:role speaker :status applied)
                                                                (:role notification :status applied))))
           (let ((resolved (emacsvox-aural-voice-runtime--resolve 'bolden 'reading-owned)))
             (should (equal (plist-get (car (plist-get resolved :selectors)) :voice-id) "espeak:gmw/en-US+m1"))
             (should (equal (cdr (plist-get resolved :selectors)) (plist-get before :selectors)))))
       (kill-buffer source)))))

(ert-deftest omnivox-espeak-variants-default-is-a-saveable-palette-destination ()
  "The existing Use in palette flow offers default, previews it and saves it."
  (emacsvox-test--with-voice-editor
   (let* ((inventory (omnivox-espeak-variants-tests--inventory))
          (saved (emacsvox-aural-read-user-data))
          (source (generate-new-buffer " *variants-default-test*")))
     (setf (plist-get (car (plist-get inventory :engines)) :espeak-variants)
           '((:id "max" :display-name "Max")))
     (unwind-protect
         (save-window-excursion
           (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory))
                     ((symbol-function 'tts-restart) (lambda () (ert-fail "Restarted speech"))))
             (switch-to-buffer source)
             (omnivox-espeak-variants-mode)
             (omnivox-espeak-variants--render)
             (emacsvox-aural-ui-goto-row "max")
             (cl-letf (((symbol-function 'completing-read)
                        (lambda (prompt collection &rest _)
                          (let ((answer (if (equal prompt "Destination palette: ")
                                            "reading-owned" "default")))
                            (should (member answer (all-completions "" collection)))
                            answer))))
               (call-interactively (key-binding (kbd "u"))))
             (should (eq (emacsvox-aural-voice-editor--get :voice) 'default))
             (when (display-graphic-p)
               (redisplay t)
               (should (eq (current-buffer) (window-buffer (selected-window))))
               (should (pos-visible-in-window-p (point))))
             (should (equal saved (emacsvox-aural-read-user-data)))
             (should-not callbacks)
             (emacsvox-aural-voice-editor-play)
             (should (equal (plist-get (car (plist-get (caar requests) :selectors)) :voice-id)
                            "espeak:gmw/en-US+max"))
             (emacsvox-aural-voice-editor-save)
             (should (= (length callbacks) 1))
             (funcall (car callbacks)
                      '(:status applied :processes ((:role speaker :status applied)
                                                   (:role notification :status applied))))
             (let ((resolved (emacsvox-aural-voice-runtime--resolve 'default 'reading-owned)))
               (should (equal (plist-get (car (plist-get resolved :selectors)) :voice-id)
                              "espeak:gmw/en-US+max")))
             (should-not (plist-get (emacsvox-aural-voice-runtime--resolve 'default 'acss-default)
                                    :selectors))
             (should (assq 'default
                           (plist-get (cl-find 'reading-owned
                                              (plist-get (emacsvox-aural-read-user-data) :voice-palettes)
                                              :key (lambda (p) (plist-get p :id))) :entries)))))
       (kill-buffer source)))))

(ert-deftest omnivox-espeak-variants-graphical-refresh-keeps-focus-and-parent ()
  (skip-unless (display-graphic-p))
  (let ((parent (get-buffer-create " *variant-parent*"))
        (picker (get-buffer-create " *variant-picker*"))
        (draft (get-buffer-create " *variant-draft*"))
        (inventory (omnivox-espeak-variants-tests--inventory)))
    (unwind-protect
        (save-window-excursion
          (pop-to-buffer picker)
          (omnivox-espeak-variants-mode)
          (setq omnivox-espeak-variants--parent parent)
          (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory)))
            (omnivox-espeak-variants--render))
          (goto-char (point-min))
          (pop-to-buffer draft)
          (insert "Unsubmitted draft")
          (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory)))
            (with-current-buffer picker (omnivox-espeak-variants--render)))
          (should (eq (window-buffer (selected-window)) draft))
          (should (equal (buffer-string) "Unsubmitted draft"))
          (pop-to-buffer picker)
          (should (equal (tabulated-list-get-id) "f1"))
          (omnivox-espeak-variants-back)
          (should (eq (window-buffer (selected-window)) parent)))
      (mapc #'kill-buffer (list parent picker draft)))))

(ert-deftest omnivox-espeak-variants-graphical-navigation-speaks-every-row ()
  (skip-unless (display-graphic-p))
  (require 'emacsvox-tabulated-list)
  (let ((picker (get-buffer-create " *variant-navigation*"))
        (inventory (omnivox-espeak-variants-tests--inventory))
        spoken)
    (unwind-protect
        (save-window-excursion
          (pop-to-buffer picker)
          (omnivox-espeak-variants-mode)
          (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory)))
            (omnivox-espeak-variants--render))
          (goto-char (point-min))
          (setq-local emacsvox-aural-ui-speech-function
                      (lambda (text) (push (substring-no-properties text) spoken)))
          (cl-letf (((symbol-function 'emacsvox-aural-submit)
                     (lambda (text &rest _) (push (substring-no-properties text) spoken))))
            (dolist (step '(("<down>" "m1" "Male one")
                            ("<up>" "f1" "Female one")
                            ("C-n" "m1" "Male one")
                            ("C-p" "f1" "Female one")))
              (setq spoken nil)
              (execute-kbd-macro (kbd (car step)))
              (should (equal (tabulated-list-get-id) (nth 1 step)))
              (should (equal (get-text-property (point) 'tabulated-list-column-name) "Variant"))
              (should (= (length spoken) 1))
              (should (string-match-p (nth 2 step) (car spoken)))))
          (execute-kbd-macro (kbd "<right>"))
          (should (= (emacsvox-aural-ui-tabulated-column-index) 1))
          (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory)))
            (omnivox-espeak-variants--render))
          (should (= (emacsvox-aural-ui-tabulated-column-index) 1))
          (should (= (window-point) (point)))
          (execute-kbd-macro (kbd "<left>"))
          (setq spoken nil)
          (execute-kbd-macro (kbd "<up>"))
          (should (equal (tabulated-list-get-id) "f1"))
          (should (string-match-p "Top of" (car spoken))))
      (kill-buffer picker))))

(ert-deftest omnivox-espeak-variants-sort-display-names-across-id-and-case-blocks ()
  "Whole-list alphabetical order is independent of IDs and capitalization."
  (let ((inventory (omnivox-espeak-variants-tests--inventory)))
    (setf (plist-get (car (plist-get inventory :engines)) :espeak-variants)
          '((:id "Amy" :display-name "Zoe") (:id "Bob" :display-name "bravo")
            (:id "adam" :display-name "alice") (:id "zoe" :display-name "Charlie")))
    (cl-letf (((symbol-function 'tts-voice-inventory) (lambda () inventory)))
      (with-temp-buffer
        (omnivox-espeak-variants-mode)
        (omnivox-espeak-variants--render)
        (should (equal (mapcar #'car tabulated-list-entries) '("adam" "Bob" "zoe" "Amy")))
        (should (eq (key-binding (kbd "P")) (key-binding (kbd "RET"))))
        (emacsvox-aural-ui-goto-row "Bob")
        (omnivox-espeak-variants--render)
        (should (equal (tabulated-list-get-id) "Bob"))
        (should (equal (mapcar (lambda (row) (plist-get row :id))
                              (plist-get (car (plist-get inventory :engines)) :espeak-variants))
                       '("Amy" "Bob" "adam" "zoe")))))))

(provide 'omnivox-espeak-variants-tests)
;;; omnivox-espeak-variants-tests.el ends here
