;;; run-tests.el --- Run Emacsvox tests in batch mode -*- lexical-binding: t; -*-

;;; Commentary:

;; Batch entry point for the Emacsvox ERT suite.

;;; Code:

(require 'ert)

(when (< emacs-major-version 31)
  (error "Emacsvox tests require Emacs 31 or later"))

(let* ((test-directory
        (file-name-directory (or load-file-name buffer-file-name)))
       (root-directory (expand-file-name "../" test-directory))
       (lisp-directory (expand-file-name "lisp/" root-directory))
       (utils-directory (expand-file-name "utils/" root-directory)))
  (add-to-list 'load-path test-directory)
  (add-to-list 'load-path lisp-directory)
  (add-to-list 'load-path utils-directory)
  ;; Load source explicitly so tests never exercise a stale .elc file.
  (load (expand-file-name "emacsvox-preamble.el" lisp-directory)
        nil nil)
  (require 'emacsvox-advice-tests)
  (require 'emacsvox-advice-audit-tests)
  (require 'emacsvox-converter-tests)
  (require 'emacsvox-dired-tests)
  (require 'emacsvox-mail-tests)
  (require 'emacsvox-core-migration-tests)
  (require 'emacsvox-completion-tests)
  (require 'emacsvox-input-tests)
  (require 'emacsvox-search-tests)
  (require 'emacsvox-file-tests)
  (require 'emacsvox-process-tests)
  (require 'emacsvox-vc-tests)
  (require 'emacsvox-overlay-tests)
  (require 'emacsvox-message-tests)
  (require 'emacsvox-timer-tests)
  (require 'emacsvox-navigation-tests)
  (require 'emacsvox-rectangle-tests)
  (require 'emacsvox-register-tests)
  (require 'emacsvox-button-tests)
  (require 'emacsvox-tooltip-tests)
  (require 'emacsvox-formatting-tests)
  (require 'emacsvox-help-tests)
  (require 'emacsvox-region-tests)
  (require 'emacsvox-eval-tests)
  (require 'emacsvox-narrowing-tests)
  (require 'emacsvox-undo-tests)
  (require 'emacsvox-position-tests)
  (require 'emacsvox-mark-tests)
  (require 'emacsvox-cleanup-tests)
  (require 'emacsvox-elint-tests)
  (require 'emacsvox-browser-tests)
  (require 'emacsvox-splash-tests)
  (require 'emacsvox-copyright-tests)
  (require 'emacsvox-keyboard-macro-tests)
  (require 'emacsvox-transpose-tests)
  (require 'emacsvox-toggle-tests)
  (require 'emacsvox-abbrev-tests)
  (require 'emacsvox-finder-tests)
  (require 'emacsvox-server-tests)
  (require 'emacsvox-customize-tests)
  (require 'emacsvox-editing-tests)
  (require 'emacsvox-display-tests)
  (require 'emacsvox-spinner-tests)
  (require 'emacsvox-key-definition-tests)
  (require 'emacsvox-suspend-tests)
  (require 'emacsvox-ange-ftp-tests)
  (require 'emacsvox-compile-tests)
  (require 'emacsvox-windmove-tests)
  (require 'emacsvox-ffap-tests)
  (require 'emacsvox-ido-tests)
  (require 'emacsvox-diff-mode-tests)
  (require 'emacsvox-project-tests)
  (require 'emacsvox-flymake-tests)
  (require 'emacsvox-package-tests)
  (require 'emacsvox-info-tests)
  (require 'emacsvox-debugger-tests)
  (require 'emacsvox-etable-tests)
  (require 'emacsvox-proced-tests)
  (require 'emacsvox-view-tests)
  (require 'emacsvox-calendar-tests)
  (require 'emacsvox-wdired-tests)
  (require 'emacsvox-tabulated-list-tests)
  (require 'emacsvox-net-utils-tests)
  (require 'emacsvox-forms-tests)
  (require 'emacsvox-xref-tests)
  (require 'emacsvox-org-tests)
  (require 'emacsvox-outline-tests)
  (require 'emacsvox-eww-tests)
  (require 'emacsvox-trace-tests))

(ert-run-tests-batch-and-exit)

;;; run-tests.el ends here
