#!/bin/sh
. ${HOME}/.bash_profile
EMACSVOX_DIR=${EMACSVOX_DIR:-${HOME}/src/emacsvox}
# one-time action for 4k display:

xrandr --output eDP-1 --mode 1680x1050 
xset dpms 0 0 0
setxkbmap -option ctrl:nocaps #-option compose:rctrl
xmodmap $HOME/.xmodmap 
pidof ibus-daemon && pkill ibus-daemon

xrdb -merge $HOME/.Xresources &
xterm  -title Retriever -fullscreen &
export LISP=sbcl
eval `ssh-agent -s`
eval $(/usr/bin/gnome-keyring-daemon --daemonize  --start --components =gpg,pkcs11,secrets,ssh)
export GPG_AGENT_INFO
export GNOME_KEYRING_PID  
${HOME}/bin/export_x_info &
light -S 5
mpv --no-video --really-quiet \
  "${EMACSVOX_DIR}/sounds/prompts/launch-wm.ogg" >/dev/null 2>&1 &
espeak-ng "Launching Window Manager" &
~/.fehbg & # wallpaper
"${EMACSVOX_DIR}/tvr/xcape.sh" &
#ssh-agent dbus-launch --exit-with-session /usr/bin/gnome-session
ssh-agent dbus-launch --exit-with-session /usr/local/bin/stumpwm
#ssh-agent dbus-launch --exit-with-session /usr/local/bin/emacs
