#!/bin/sh
#PreRequisites:
# Install piper-tts in a virtual environment available on PATH.
# Download a model into pip-data-dir, for example:
#python3 -m piper.download_voices \
#  --data-dir "$HOME/.local/share/voices-piper" en_US-lessac-medium

#usage: pipspeak model device
# where model is a fully-qualified path to the model.
# And device is an alsa device.

MODEL=$1
DEV=$2

piper -m $MODEL   --output-raw | \
aplay -M -D$DEV  -r 22050 -f S16_LE -t raw -
#  play -L -r 22050 -b 16 -c 1 -e signed-integer - # for sox
