#!/bin/sh
# usage: REMOTE=host EMACSVOX_DIR=/path/to/emacsvox \
#          remote-tts-setup [server-script] [tts-server]
# Also see .. bash-scripts/remote on GitHub
# starts a local server, then ssh to remote-host,
# and set up reverse port forwarding.
#Examples:
# remote-tts-setup speech-server outloud 
# remote-tts-setup 32-speech-server 32-outloud 
# remote-tts-setup speech-server mac

: "${REMOTE:?Set REMOTE to the SSH host}"
: "${EMACSVOX_DIR:?Set EMACSVOX_DIR to the Emacsvox installation}"

SPEECH_SERVER=${1:-speech-server}
TTS_SERVER=${2:-outloud}
SDIR=$EMACSVOX_DIR/servers
# Primary server listens on 2222
"$SDIR/$SPEECH_SERVER" 2222 "$SDIR/$TTS_SERVER" &
#notification stream listens on 3333
(export ALSA_DEFAULT="tts_mono_left"; \
  "$SDIR/$SPEECH_SERVER" 3333 "$SDIR/$TTS_SERVER" &)
beep -f 800 -l 50
ssh-agent ssh -R 2222:localhost:2222 -R 3333:localhost:3333 "$REMOTE"
