\input texinfo
@c$Id$
@finalout
@setfilename ./emacsvox.info
@include style.texi
@settitle Emacsvox User Manual
@dircategory Accessibility
@direntry
* Emacsvox:(emacsvox).		Speech-enabled Audio Desktop.
@end direntry
@dircategory Emacs
@direntry
* Emacsvox:(emacsvox).		Speech-enabled Audio Desktop.
@end direntry

@titlepage

@title Emacsvox@*The Complete Audio Desktop
@subtitle User Manual
@author T. V. Raman

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1994--2024 T. V. Raman. All Rights Reserved.

Permission is granted to make and distribute verbatim copies of this
manual without charge provided the copyright notice and this permission
notice are preserved on all copies.

@end titlepage

This manual documents @strong{Emacsvox, The Complete Audio Desktop}.

@summarycontents
@contents

@include preamble.texi
@include emacsvox-body.texi
@c trailer

@node Concept Index
@chapter Concept Index
@printindex cp

@bye
