(defun adventure ()
  (interactive)
  (comint-run "/usr/games/adventure")
  (unless emacspeak-comint-autospeak (emacspeak-toggle-comint-autospeak))
  (tts-set-punctuations 'some)
  (when tts-split-caps (tts-toggle-split-caps))
  (emacspeak-icon 'open-object))
