(defun adventure ()
  (interactive)
  (comint-run "/usr/games/adventure")
  (unless emacsvox-comint-autospeak (emacsvox-toggle-comint-autospeak))
  (tts-set-punctuations 'some)
  (when tts-split-caps (tts-toggle-split-caps))
  (emacsvox-icon 'open-object))
