#!/bin/sh
# Play prompt  from outside Emacs
#Usage emsicon<icon>
l="$@"
pidof -q `which emacs` && \
emacsclient -n -e "(emacsvox-icon '$l)"   2>&1 > /dev/null || {
        : "${EMACSVOX_DIR:?Set EMACSVOX_DIR to the Emacsvox checkout}"
        paplay "$EMACSVOX_DIR/sounds/chimes/$l.ogg"
}
