* Using Online Help With Emacsvox.
:PROPERTIES:
:TEXINFO_NODE_NAME: Using Online Help
:ALT_TITLE: Using Online Help
:DESCRIPTION: Use Emacs help effectively with speech.
:END:

#+cindex: Online Help

Emacs provides an extensive online help system for helping you learn
about various aspects of using Emacs.  Emacsvox provides online help
for its various extensions using this same help system.  This chapter
explains how to use the online help facilities in order to empower you
in discovering powerful and versatile working techniques that will
make you more and more productive in your day to day computing.

The online help options are accessed via the @@texinfo:@kbd{C-h}@@ prefix key,
which must be followed by an additional letter or control character to
designate the kind of help desired.  For example, @@texinfo:@kbd{C-h t}@@
~help-with-tutorial~ visits the Emacs tutorial in a new buffer;
@@texinfo:@kbd{C-h i}@@ ~info~ enters the Info documentation system, from
which you can read Texinfo manuals that have been installed on your
system, including the Emacs and Emacsvox documentation; and @@texinfo:@kbd{C-h k}@@ ~describe-key~ provides a description of the Emacs function
which is bound to the next key that you type.  For learning about the
various options that are available via the @@texinfo:@kbd{C-h}@@ mechanism
described above, view the online help for command ~help-for-help~
bound to @@texinfo:@kbd{C-h C-h}@@  @@texinfo:@MDash{}@@ using what has been described so far,
you would achieve this by pressing @@texinfo:@kbd{C-h k}@@ followed by @@texinfo:@kbd{C-h C-h}@@.

Emacsvox users should note that online help is typically displayed in
a separate Emacs window.  Where it makes sense to do so, Emacsvox
will automatically speak the displayed help.  Once you've asked for
help, you can hear the displayed documentation as many times as you
wish using Emacsvox command ~emacsvox-speak-help~ bound to
@@texinfo:@kbd{C-e h}@@.  If you want to move through the displayed help a line at
a time, switch to the buffer where the help is displayed  @@texinfo:@MDash{}@@ the
buffer is called ~*Help*~.

Often, in adding an auditory interface to an Emacs extension, such as
a web browser or mail reader, Emacsvox defines additional commands
and key bindings which enhance the functionality of the spoken
feedback provided by the application.  This manual does not purport to
document all such commands.  It is important, therefore, when learning
to use the various Emacs extensions which comprise the `audio desktop'
(@@texinfo:@pxref{Audio Desktop}@@) that you take advantage of online help to
obtain details of any context-specific features provided by Emacsvox.
The following two commands are of particular importance in this
regard:

- @@texinfo:@kbd{C-h m}@@ ~describe-mode~ explains which major and minor modes
   are currently in effect, and lists the commands and key bindings
   associated with them.

- @@texinfo:@kbd{C-h b}@@ ~describe-bindings~ lists all of the key bindings
   which are currently defined.

For example, after entering Dired or EWW, use @@texinfo:@kbd{C-h m}@@ to hear the
mode-specific commands and every active minor mode.  Use @@texinfo:@kbd{C-h b}@@ when you
need the exact effective bindings, including local package maps and personal
configuration.  These live descriptions are more reliable than copying a
large binding table into a tutorial.

Emacsvox supplements the online help facilities available within
Emacs by defining several commands of its own, as follows:

- @@texinfo:@kbd{C-h C-e}@@ ~emacsvox-describe-emacsvox~ presents a brief Emacsvox
   overview.

- @@texinfo:@kbd{C-e N}@@ ~emacsvox-view-emacsvox-news~ opens the versioned Emacsvox
   news, and @@texinfo:@kbd{C-e T}@@ ~emacsvox-view-emacsvox-tips~ opens the productivity
   tips.

- @@texinfo:@kbd{C-h C-l}@@ ~emacsvox-learn-emacs~ enters a loop in which the function
   of every key that you type is spoken; leave it with @@texinfo:@kbd{C-g}@@.

- @@texinfo:@kbd{C-e H}@@ ~emacsvox-aural~ opens Aural Home.  From an ordinary buffer,
   @@texinfo:@kbd{C-e E}@@ ~emacsvox-aural-explain-presentation~ explains why the object
   at point received its voices and auditory actions.
