* Voice Lock
:PROPERTIES:
:TEXINFO_NODE_NAME: Voice Lock
:DESCRIPTION: Use voice lock and aural highlighting.
:END:

See
[[http://tvraman.github.io/emacspeak/blog/voice-lock-refreshed.html]]
for a high-level overview of how Emacsvox Voice-Lock has evolved over
the years.

1. Emacsvox defines a number of voice overlays such as
   ~voice-bolden~, and ~voice-lighten~ that can be applied to a
   given voice to change what it sounds like.

1. Voice overlays are defined in terms of Aural CSS
   ([[http://www.w3.org/tr/css2/aural.html][ACSS]]) to keep them
   independent of a specific TTS engine.

1. For each such overlay there is a corresponding
   ~<OVERLAY-NAME>-settings~ variable that can be customized via
   custom.

1. The numbers in ~voice-bolden-settings~ as an example:

#+attr_texinfo: :columns 0.5 0.5
| Setting | Value |
| family | nil |
| average-pitch | 1 |
| pitch-range | 6 |
| stress | 6 |
| richness | nil |
| punctuation | nil |

Unset values (~nil~) show up as ``unspecified'' in the customize
interface.

1. Do not directly customize ~voice-bolden~ and friends, instead
   customize the corresponding ~voice-bolden-settings~, since that
   ensures that all voices that are defined in terms of
   ~voice-bolden~ get correctly updated.

1. Discovering what to customize:

Command ~emacsvox-show-personality-at-point~ (bound by default
to C-e M-v) will show you the value of properties personality and
face at point.  Describe-variable on these names should tell you
what to customize; so as an example:

Put point on a comment line, and hit @@texinfo:@kbd{C-e M-v}@@: you will hear

#+begin_example
Personality emacsvox-voice-lock-comment-personality
Face font-lock-comment-delimiter-face
#+end_example

Describe-variable of ~emacsvox-voice-lock-comment-personality~ gives:

#+begin_example
emacsvox-voice-lock-comment-personality's value is acss-p0-s0-all

Documentation: Personality used for font-lock-comment-face This
personality uses voice-monotone whose effect can be changed globally
by customizing voice-monotone-settings.
#+end_example

** How It All Works
:PROPERTIES:
:TEXINFO_NODE_NAME: How It All Works.
:ALT_TITLE: How It All Works.
:END:

Here is a brief explanation of the connection between
~voice-bolden~ and its associated ~voice-bolden-settings~.

1. Voice settings are initially in ~voice-bolden-settings~ which is
   a list of numbers.

1. That list of numbers needs to be translated to appropriate
   device-specific codes to send to the TTS engine.

1. You do not want to do this translation *each* time you
   speak something.

1. So when ~voice-bolden~ is defined, the definition happens in
   two steps:

   - The list of settings is stored away in
      ~voice-bolden-settings~,

   - A corresponding voice-name is generated   @@texinfo:@MDash{}@@
      ~acss-a<n>-p<n>-r<n>-s<n>~ and the corresponding control codes to
      send to the device are stored away in a hash-table keyed by the above symbol.

   - Finally, ~voice-bolden~ is assigned the above symbol.

** What this gives
:PROPERTIES:
:TEXINFO_NODE_NAME: What this gives.
:ALT_TITLE: What this gives.
:END:

1. The ability to customize the voice via custom by editing
   the list of numbers in ~voice-bolden-settings~

1. When that list is edited, ~voice-bolden~ is arranged to be
   updated automatically.

The following additional commands from the
@@texinfo:@ref{emacsvox-wizards,,,emacsvox-reference,Emacsvox Reference Manual}@@ module
are useful when designing aural styles.

1. ~emacsvox-wizards-generate-voice-sampler~

   Generate a buffer containing text that demonstrates the effect of
   various aural settings.

1. ~emacsvox-wizards-voice-sampler~

   Applied specified aural style to text in current region.
